### ISSUE TITLE
Configure test nodes using Dynamic DNS hosting

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#100]
Subtasks:
1. Register the hosts
2. Set up 'ntpdate' within cron for synchronized logging
3. (Optionally) open a port to the outside world on the router

**Comment by m21** [comment]
1. In the shared folder see : Development_P2P "Dynamic DNS setup" ; try it, provide feedback, comments

**Comment by m21** [comment]
@SirHalsell @JackXLu part 1 is ready -- setup & register your own (Ubuntu) nodes when you get a chance.

**Comment by m21** [comment]
2. ntpdate is in the document as well
3. Is router-specific. On Hold.

**Comment by drobertbaker** [comment]
unassigned m21

**Comment by drobertbaker** [comment]
unassigned m21

**Comment by drobertbaker** [comment]
unassigned m21

**Comment by PaulSnow** [comment]
don't need this one.
