### ISSUE TITLE
Ability to support duplicate entries in the same block or different blocks in the same chain

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#111]

**Comment by JackXLu** [comment]
the following code in eblock.go under database needs to be improved:

				// Create an EntryInfo and insert it into db
				var entryInfo = new (notaryapi.EntryInfo)
				entryInfo.EntryHash = ebEntry.Hash()
				entryInfo.EBHash = eblock.EBHash
				entryInfo.EBBlockNum = eblock.Header.BlockID
			 	var entryInfoKey [] byte = []byte{byte(TBL_ENTRY_INFO)} 
			 	entryInfoKey = append(entryInfoKey, entryInfo.EntryHash.Bytes ...) 
			 	binaryEntryInfo, _ := entryInfo.MarshalBinary()
				db.lbatch.Put(entryInfoKey, binaryEntryInfo)

**Comment by PaulSnow** [comment]
non-issue
