### ISSUE TITLE
Factoid Chain Integration Development Design

### ISSUE THREAD

**Issue by jaybny** [FactomProject/WorkItems#113]

**Comment by PaulSnow** [comment]
Need some details here.  What is this work item?

**Comment by JackXLu** [comment]
Paul - could u pls check w/ Jeff or Gavin and find out whether we can use their code?

**Comment by JackXLu** [comment]
https://blog.ethereum.org/team/

**Comment by BreakoutCoin** [comment]
UTXO vs Account  -pros vs cons 

both are state of ledger - a transaction is just a transition: https://www.ethereum.org/pdfs/EthereumWhitePaper.pdf

utxo con - must gather outputs to spend, must create change output: 
https://github.com/btcsuite/btcutil/tree/master/coinset

**Comment by jaybny** [comment]
UTXO vs Account -pros vs cons

both are state of ledger - a transaction is just a transition: https://www.ethereum.org/pdfs/EthereumWhitePaper.pdf

utxo con - must gather outputs to spend, must create change output: 
https://github.com/btcsuite/btcutil/tree/master/coinset

**Comment by jaybny** [comment]
https://github.com/FactomProject/FactomCode/commit/53279e263a941baf802419fc7ed9a390a658d176
