### ISSUE TITLE
op_return data needs height

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#116]
data in factom is currently anchored like this:

http://testnet.coinsecrets.org/?to=317188.000000
Factom!!h?e6?0-c??_???5???R>7??S}?????}~ 

http://blockexplorer.com/testnet/tx/d7bf4f826bcdbc9b79ecb71f773d11502e1001942de6f1ed095e3a55cdb7210c

should be FaHHHHHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Fa are ascii chars 0x46 and 0x61
H = factom block height 6 bytes
A = Anchor 32 bytes

from whitepaper page 34.

**Comment by m21** [comment]
https://github.com/FactomProject/FactomCode/commit/b89f214d5d3e27b7da6cba3632ba02c2218f9a52

The inner function is ready; but the block height needs to be passed in from upper layer(s).
TBD how later (?)
@carryforward  -- agreed?

**Comment by carryforward** [comment]
OK, Thank you. I will make a work item for that.
