### ISSUE TITLE
sha256: single vs double & preimage attacks

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#117]
Relevant recent discussion here - would just like an opinion from our top people, entering an item so as we don't forget. :)

https://bitcointalk.org/index.php?topic=928202.msg10189999#msg10189999
...and the whole thread

**Comment by m21** [comment]
Superceeded by https://github.com/FactomProject/WorkItems/issues/169

**Comment by jaybny** [comment]
I just take it at fact, that sha256 is a 100% one way function.  no need to
double it.

**Comment by carryforward** [comment]
mishmash.  mostly sha256 for everything except:  
doublesha256 for txid's per m21 request.  
sha3 for checksums of blocks.  
combination sha3 then sha256 for entry hashes.

**Comment by m21** [comment]
implementation task: https://github.com/FactomProject/WorkItems/issues/317
