### ISSUE TITLE
Fix the conformal reference issue

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#122]
conformal github has been renamed

**Comment by JackXLu** [comment]
Conformal renamed their project to btcsuite. When you pull the latest factom code, please do the following to refresh the conformal code as well:

1. Delete the old conformal source folder src/github.com/conformal
2. run "go get github.com/btcsuite/btcd" and "go get github.com/btcsuite/btcwallet"
3. rebuilt your projects

**Comment by michaelbeam** [comment]
push code into master

**Comment by carryforward** [comment]
master now compiles again.
