### ISSUE TITLE
MultiSig factoid address support

### ISSUE THREAD

**Issue by jaybny** [FactomProject/WorkItems#134]
design multisig address scheme for factoids. 

related to design of factoid transactions (script vs no script)

**Comment by jaybny** [comment]
## Schnorr signatures and ed25519

seems like there may be a way to have m signatures combined into a single signature and verified against a single public-key. public-key would have been generated by combining m signatures. 

if so, i believe we can implement n of m multisig, without the need of script. it may even be indistinguishable from a simple signature .

see: http://stackoverflow.com/questions/5486304/explain-merkle-trees-for-use-in-eventual-consistency

and the following quote from Adam Black here: http://sourceforge.net/p/bitcoin/mailman/message/31503959/
```
And we may want to add ECS (schnorr) because it's simpler and allows more
flexibility and efficiency (eg native n of n multisig at the storage cost of
1 signature vs n with ECDSA, and k of n threshold signature at the cost of 1
sig (but some threshold secret share setup up front).  The relying party
doesnt need to know how many multi-sigs there are there is a single public
key.
...
Adam
```

http://crypto.stackexchange.com/questions/20581/does-ed25519-support-cryptographic-threshold-signatures

**Comment by carryforward** [comment]
https://github.com/FactomProject/FactomDocs/blob/master/factomDataStructureDetails.md#factoid-transaction
