### ISSUE TITLE
replace DoubleSha256 with Sha256 

### ISSUE THREAD

**Issue by jaybny** [FactomProject/WorkItems#142]
code copied from btcd uses DoubleSha.. have not heard a valid reason for doing this extra work. Brian/paul, please confirm and assign to Michael Y?

**Comment by m21** [comment]
If we are still using SHA256 I'd use double just as before. I am not a better cryptographer than Bitcoin creators to say otherwise. :)
But I've heard Brian may have better ideas on hash functions.

**Comment by carryforward** [comment]
doublesha256 for only txid at this point per m21 request. single sha256 most other places.
