### ISSUE TITLE
Conformal's btcscript changed again today

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#157]
Most builds will be broken.
https://github.com/btcsuite/btcd/tree/master/txscript

Need to get the correct packages and re-point the code.

**Comment by m21** [comment]
They are still changing everything around:
go get -v github.com/btcsuite/...            
github.com/btcsuite/btcchain (download)
github.com/btcsuite/btcd (download)
../../../btcsuite/btcd/config.go:24:2: cannot find package "github.com/btcsuite/go-flags" in any of:

Now my main dev machine is screwed up :( Will try again in a few hours.

**Comment by jaybny** [comment]
Use https://github.com/FactomProject/facd

**Comment by jaybny** [comment]
stop doing go get. 

just do go install… use the code yo have on your local is its working.

**Comment by jaybny** [comment]
i reccomend forking all projects if needed.. are they doing this in master?

**Comment by m21** [comment]
Still missing "github.com/btcsuite/btcrpcclient" -- any clue what replaced it?
(btcscript is now btcd/txscript)
P.S. I am upgrading multiple machines here btw.

**Comment by m21** [comment]
https://github.com/FactomProject/FactomCode/commit/d87c7a68e582f04f0e6c2ce6bbe6ecfb9acc9fc9 points to the new script location now
