### ISSUE TITLE
Remove hardcoding, add proper size checks

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#158]
Here's one example of a hardcoded limit that needs to be cleaned up, introduced during rapid troubleshooting: https://github.com/FactomProject/FactomCode/commit/f83aa3a76ea3cb9948decdeff8b75e0b878c178a

**Comment by m21** [comment]
Another check needs to be put back later: https://github.com/FactomProject/FactomCode/commit/2e5a4e67cd5541cd331add36cd47a07d42839899

**Comment by PaulSnow** [comment]
Is this done?

Might be a bit too general.
