### ISSUE TITLE
Get peer address list for DHT implementation

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#162]

**Comment by JackXLu** [comment]
You might want to take a look here(server.go) as well:

// handleBroadcastMsg deals with broadcasting messages to peers.  It is invoked
// from the peerHandler goroutine.
func (s *server) handleBroadcastMsg(state *peerState, bmsg *broadcastMsg) {
	util.Trace()
	state.forAllPeers(func(p *peer) {
		excluded := false
		for _, ep := range bmsg.excludePeers {
			if p == ep {
				excluded = true
			}
		}

**Comment by m21** [comment]
Yes forAllPeers() is the correct call which gives as all peers.
But placing this work on hold due to today's discussions.

**Comment by drobertbaker** [comment]
unassigned m21

**Comment by PaulSnow** [comment]
Not needed for milestone 2.
