### ISSUE TITLE
Pondering the inifite loop

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#163]
Need a way for a node to know that the message it just got and is about to broadcast has already passed through -- i.e. to avoid an infinite loop.

**Comment by jaybny** [comment]
there is a design pattern that solves this common problem... I'm sure btcd already solves this. 

in general just never resend the same message twice

**Comment by carryforward** [comment]
As I understand bitcoin just offers up lists of inventory items.  The recieving node parses the list and determines which items it wants to request.  I was under the impression that only new items in the inventory list were posted as unsolicited advertizements to the peers.   we could do the same.

**Comment by jaybny** [comment]
we are just talking about the "unconfirmed" pool of transactions... so I dont think there needs to be any reply/request protocal. 

when a new NodeA connects to running NodeB, and they are both at the same block height, NodeB sends NodeA all the "unconfirmed" transactions, NodeA does not relay these to the network. 

when "live" nodes receive new messages they have not seen before they relay them to everyone except the node who sent it, then you mark it as "sent" and put it in unconfirmed list.

**Comment by jaybny** [comment]
https://github.com/btcsuite/btcd/blob/cf6fc57f27f515ecd48815fdb4de1fdef351843e/wire/msgmempool.go

https://github.com/btcsuite/btcd/blob/624bbb3216698df4ba53451891dab7a54bce23da/mempool.go

**Comment by m21** [comment]
@carryforward Well, any random message or junk can come into a Bitcoin node (including unsolicited TXs from days ago, as the nice inv/getdata model is not mandatory at all. TXs can always be simply pushed onto everyone).
Thus, the node has to be smart enough and nice enough to not forward this "junk" to other peers.
Bitcoin (implementation) accomplishes this by keeping track of TXs it has seen in mempool & blocks and validating sigs & other parameters as much as possible before rebroadcasting.
Same should happen here.

**Comment by m21** [comment]
Solved by the generic record-keeping function https://github.com/FactomProject/FactomCode/commit/c9ea445ac66355350481bd87b90f9b7900445bb9#diff-fb0b4d0bf47219232044cb7cade211e7R381 for the 5 Factom data messages currently.
Could easily be called for any other message.
