### ISSUE TITLE
Fix the compiling errors in factomexplorer

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#165]
# github.com/FactomProject/factomexplorer
./data.go:34: undefined: notaryapi.Key
./data.go:86: undefined: notaryapi.Key
./data.go:288: undefined: notaryapi.Key
./data.go:296: undefined: notaryapi.Key
./entry.go:137: cannot use rand (type io.Reader) as type []byte in function argument
./entry.go:137: too many arguments in call to k.Sign
./entry.go:137: assignment count mismatch: 2 = 1
./entry.go:149: cannot use e.signatures[s] (type notaryapi.Signature) as type *[64]byte in function argument
./entry.go:291: sig.MarshalBinary undefined (type notaryapi.Signature has no field or method MarshalBinary)
./entry.go:308: sig.MarshalledSize undefined (type notaryapi.Signature has no field or method MarshalledSize)
./entry.go:308: too many errors

**Comment by jaybny** [comment]
should compile against latest FactomCode in development branch. 

https://github.com/FactomProject/factomexplorer/commit/93dfdac4adf85a94c256c17e494813c5c940f5dd
