### ISSUE TITLE
Binary Encoding strategy - refactor

### ISSUE THREAD

**Issue by jaybny** [FactomProject/WorkItems#166]
decide how to encode factom data for hashing. currently notaryapi.Hash uses BigEndian, while BtcEncode/Serialize in factomwire uses little endian.

**Comment by carryforward** [comment]
lets use big endian whenever we can.  Bitcoin core devs would have liked to used big endian, but would require a hard fork.  https://en.bitcoin.it/wiki/Hardfork_Wishlist

big endian is also called network byte order.  It is odd that the wire protocol uses little endian.
