### ISSUE TITLE
Certainty

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#169]
Document (& implement ASAP) those "constants" that are 90+% clear right now:
* port numbers
* magic numbers
* hashing algo:
  https://github.com/FactomProject/WorkItems/issues/117
  https://github.com/FactomProject/WorkItems/issues/142
* endianness (already decided)
* key/address encoding
* EC algo (decided?)

I know it's never a good time, but basically these little "external" things will be harder & harder to change as more eyes start looking.

**Comment by m21** [comment]
Needed soon (a week or two):
* port numbers
* magic numbers

**Comment by m21** [comment]
for reference, bitcoin mainnet: F9 BE B4 D9
https://github.com/FactomProject/btcd/blob/ec4cde4840a10e47b6a81bc406e20b57c3b22af3/wire/protocol.go#L90
https://github.com/FactomProject/btcd/blob/ec4cde4840a10e47b6a81bc406e20b57c3b22af3/chaincfg/params.go#L102

**Comment by carryforward** [comment]
directory block has magic number of 0xFA92E5A1 for main net.  

https://github.com/FactomProject/FactomDocs/blob/master/factomDataStructureDetails.md#directory-block

there is no magic number for the factoid blocks under the directory blocks.

**Comment by m21** [comment]
Ah sorry; wasn't being clear -- the magic number needed here is for the network (wire) protocol, the P2P.
(The message/packet header; nothing to do with blocks/entries which are internal payload magic numbers).
https://en.bitcoin.it/wiki/Protocol_documentation#Message_structure

**Comment by PaulSnow** [comment]
Too general.

**Comment by carryforward** [comment]
port 8108 for main net: 0x1FAC
