### ISSUE TITLE
Handle messages that have been processed with errors

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#172]

**Comment by m21** [comment]
Current thinking (not implemented this way yet):
* Every Incoming Message of every Factom type gets passed to the PROCESSOR and shall not be immediately relayed; the peer it came from is also passed to the PROCESSOR
* The PROCESSOR (most likely) will organize all such (incoming) messages into their own queues based on message type (perhaps even tying in with the process-lists & handling) and will keep them around "for a while"
* After being processed some messages from each queue will get deleted and either: Dropped or Relayed (call FactomRelay less the original peer); SFMs may also be generated based on the outcome (?)
* Some messages will be kept around longer (much like Bitcoin's orphans); need a way to dump them (look at orhpans' cleanup)
Note: much like in Bitcoin -- these queues are planned to be in-memory only; i.e. if a node gets shut down & restarted -- it contains no such "pending" information.

**Comment by jaybny** [comment]
--yes, we need to design an internal event based message systems
--seems that btcd uses BlockManager to manage peers and messages. 

-- so each WireMsg should be sent to a "Processor", which will verify and then decide to either broadcast it or not. Then it will get added to a mempool, which contains a "process list" and an "orphan list" 

-- the responsible federated server will also send a conf message each time a tx is added to its process list. 

-- normal nodes will receive the conf message, verify, and broadcast, and add it to its mempool

-- so a mempool now has a list of valid tx, a list of orphan tx... a seperate list of confirmed tx will also be kept. 

Note: this is the same exact process for all messages, entry|chain commits, factoid|enrty-credit tx, as well as federated consensus messages.  not sure how reveal is handled. 

-- then an end-of-minute marker with hash of process list is sent. i believe this marker will be signed by a majority of federated servers.. 

....

**Comment by PaulSnow** [comment]
Duplicate
