### ISSUE TITLE
compile list of keys + balances for genesis block

### ISSUE THREAD

**Issue by jaybny** [FactomProject/WorkItems#182]

**Comment by m21** [comment]
Please add UTXOs for each one of our keys we have provided to the Genesis block.
(It is also a real life scenario).

**Comment by jaybny** [comment]
please add genesis block as first block processed

**Comment by m21** [comment]
Genesis Factoid coinbase TX is defined here:
https://github.com/FactomProject/btcd/blob/3c65f79a69762ed83fa750ab2e3a1407083648bd/chaincfg/genesis.go#L33

Need the spec for the genesis factoid block itself (and overall factoid block spec).

**Comment by PaulSnow** [comment]
Need the definition.  

Once that is done, we can finalize the genesis construction.

**Comment by PaulSnow** [comment]
Duplicate #457
