### ISSUE TITLE
factomclient: api call for creating new factoid transaction

### ISSUE THREAD

**Issue by jaybny** [FactomProject/WorkItems#188]

**Comment by michaelbeam** [comment]
url.Values{ address=walletaddr ammount=number }

**Comment by michaelbeam** [comment]
in git branch mjb/api. factomclient/serve.go: handleFactoidTx

**Comment by michaelbeam** [comment]
the wire message (type MsgTx) is built and needs to be sent on the p2p network

**Comment by m21** [comment]
https://github.com/FactomProject/FactomCode/commit/9fe084370e753ab89497c783bb1e659447188c6d#diff-58d1838b4972d08407654daabab734afR210
