### ISSUE TITLE
Handle orphan messages

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#207]
for out-of-order reveal messages

**Comment by JackXLu** [comment]
U were saying those message can go into the same pool as factoid transactions

**Comment by m21** [comment]
Correct, the pools' functionality should be extended to all Factom messages, not just Factoid TXs.

**Comment by drobertbaker** [comment]
unassigned m21

**Comment by PaulSnow** [comment]
Will be built into Milestone 2.  Don't need this item.
