### ISSUE TITLE
change name for factom-cli

### ISSUE THREAD

**Issue by michaelbeam** [FactomProject/WorkItems#218]
ftm
factom
fact
fctm
...
please comment with any more suggestions

**Comment by michaelbeam** [comment]
fctm

**Comment by m21** [comment]
I like "factom-cli" ; much like here: http://bitcoin.stackexchange.com/questions/32048/difference-between-bitcoin-tx-bitcoin-cli-and-bitcoind

And we already have "factomd" for our node binary.
(Jay also seemed to have liked "factom-cli" the way it is).

**Comment by michaelbeam** [comment]
no name change
