### ISSUE TITLE
Dump every msg to file and make it configurable

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#243]

**Comment by JackXLu** [comment]
Wireshark-type dump off of port 4012, a couple of machines.

**Comment by carryforward** [comment]
port changed to 8108: 0x1FAC

**Comment by m21** [comment]
We should record everything the very first time we go live.

**Comment by m21** [comment]
@PaulSnow - is this a real workitem? Or close it?

**Comment by m21** [comment]
Not needed for milestone1 - server logs serve the purpose.

**Comment by drobertbaker** [comment]
unassigned m21

**Comment by PaulSnow** [comment]
Don't know what this is.  If you don't either, then let's close it.

**Comment by drobertbaker** [comment]
OK
