### ISSUE TITLE
BTC anchor validation

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#255]
Please add validation details

**Comment by m21** [comment]
Related: https://github.com/FactomProject/WorkItems/issues/288
Related: https://github.com/FactomProject/WorkItems/issues/173

**Comment by m21** [comment]
NOTE: factombtc.go is being deleted : it contains anachronistic Bitcoin code that can't be part of our Factom source:
https://github.com/FactomProject/btcd/blob/3c65f79a69762ed83fa750ab2e3a1407083648bd/factombtc.go

**Comment by m21** [comment]
factombtc.go is now removed, pointers to old anchoring code:
https://github.com/FactomProject/btcd/commit/ec4cde4840a10e47b6a81bc406e20b57c3b22af3#diff-e94248ae718216bfec8373cf59d78eedR199

**Comment by PaulSnow** [comment]
Duplicate
