### ISSUE TITLE
RE-ENABLE: Factoid Block processing disabled for now (mostly catch-up mode related)

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#261]
https://github.com/FactomProject/btcd/commit/2b612828dad49d085077a55c29cd9a78e84ce6ba

(via the BFFactomFlag1)

**Comment by m21** [comment]
flag removed: BFFactomFlag1
catch-up of Factoid blockchain to be verified (probably interating with Bo's catch-up code; for at least the block height)

**Comment by PaulSnow** [comment]
Advise?  What is this?

**Comment by m21** [comment]
was done a while back, closing
