### ISSUE TITLE
Restore BTC anchors using different BTCD packages

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#288]

**Comment by m21** [comment]
This may be related: https://github.com/FactomProject/WorkItems/issues/173
Also: dropping anchors & collecting (& validating) anchors are 2 different and quite important tasks -- is that being tracked?

**Comment by m21** [comment]
old code for reference: https://github.com/FactomProject/btcd/commit/f93d49e60f5e315fc6b397bd506227ce8b19262d#diff-876630cdb97104f6a3795e6c38af53f8R224
(to be removed at some point)

**Comment by m21** [comment]
factombtc.go is now removed, pointers to old anchoring code:
https://github.com/FactomProject/btcd/commit/ec4cde4840a10e47b6a81bc406e20b57c3b22af3#diff-e94248ae718216bfec8373cf59d78eedR199

**Comment by PaulSnow** [comment]
Duplicate
