### ISSUE TITLE
pass existing unit tests in wire

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#291]

**Comment by m21** [comment]
85 out 120 passing, will come back to this task

**Comment by PaulSnow** [comment]
Moved broken tests into a wire/broken.   So far, I have fixed (or validated)
bench_test.go
common_test.go
fixedIO.test.go
internal_test.go

**Comment by PaulSnow** [comment]
Fixed 
blockheader_test.go

**Comment by PaulSnow** [comment]
Can skip the coin based tests now.  Only wire centric tests need to work, and that shouldn't be too hard.
