### ISSUE TITLE
implement bitfield in wire

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#301]
https://github.com/FactomProject/btcd/blob/91ab69347620670697cd8d2827a232b74d8fedc4/wire/fact-methods.go#L93

**Comment by PaulSnow** [comment]
Advise!

**Comment by m21** [comment]
bitfield is defined in the Factoid spec section, proper implementation, ideally with unit tests is needed.

**Comment by PaulSnow** [comment]
Bitfield isn't needed, so it has been removed.
