### ISSUE TITLE
design the current Factoid chain height determination

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#303]
Unlike in Bitcoin this height is controlled by DirBlock height.

**Comment by PaulSnow** [comment]
Advise!

**Comment by m21** [comment]
Mainly an integration task - agree what the current block height is for all components.

**Comment by m21** [comment]
related: https://github.com/FactomProject/WorkItems/issues/290

**Comment by m21** [comment]
redundant, see this item: https://github.com/FactomProject/WorkItems/issues/351
