### ISSUE TITLE
Factoid block header timestamps

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#305]
Timestamping is off.
Need a bit of spec, design & code here:
https://github.com/FactomProject/btcd/commit/e86aea2495362fbcbadba3243d49537ccb9790da#diff-b3b79366d4e0593a2c5fe3324fba4b3eR71

**Comment by m21** [comment]
@carryforward we probably do not need to keep track of time (timestamp) Factoid blocks since the DirBlockChain is in charge?

**Comment by m21** [comment]
Timestamp to be removed from the Factoid block (header) per spec: https://github.com/FactomProject/FactomDocs/commit/d0aac7148d50f35d73371b34ee966c0c2a8570d3

**Comment by m21** [comment]
When the real factoid header is done (https://github.com/FactomProject/WorkItems/issues/344), this item will also be taken care of.

**Comment by PaulSnow** [comment]
Removed Timestamping ... That is done in Factom.
