### ISSUE TITLE
pass existing tests in database

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#306]

**Comment by m21** [comment]
btcd/database that is

**Comment by m21** [comment]
btcd/database/memdb tests pass already

**Comment by m21** [comment]
Too much debug information is currently being printed: util.Trace() is triggering errors.
The .bz2 stored file test is now bypassed.

**Comment by PaulSnow** [comment]
Advise!

**Comment by m21** [comment]
This is a clean-up task, revisit in the future for Milestone1.

**Comment by PaulSnow** [comment]
Coin tests not needed for Factoid1, but still need wire tests.
