### ISSUE TITLE
Coinbase payout amount -- to be coded up

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#315]
https://github.com/FactomProject/btcd/blob/e97a4b60e5027c2a01154da2ceb5b67e2add7b69/mining.go#L269

Some algo determines the amount - or is it fixed (?)

**Comment by carryforward** [comment]
maximum payout will be a constant determined by the final number of factoids created by the token sale.  Until we get the full compliment of federated servers up and running, we are currently planning on setting it really low or zero.

**Comment by m21** [comment]
So it's ok to hard-code it to a low constant for Phase1?
Will it always be a constant (in 6months and on)?

**Comment by carryforward** [comment]
yes, the maximum will be constant and can be hard coded in.  the actual amount created can be equal or lower.  for phase1, yes, we can hard code it.

**Comment by m21** [comment]
For Phase1 we agree -- send the coinbase amount to an non-spendable address (rcdhas is all 0s):
https://github.com/FactomProject/btcd/commit/afac71bdd119c216c899ccea45ca4473608141ad#diff-968036f1f36873020c4c42843f1c1f75L87

The amount is currently .1 COIN, for testing:
https://github.com/FactomProject/btcd/commit/afac71bdd119c216c899ccea45ca4473608141ad#diff-d7ceea52c3db162b4d07071516f5d83dR61

**Comment by m21** [comment]
For those curious it now looks like this (rcd hash is all 0s, payout amout is 0.1 coin)
 TxOut: ([]*wire.TxOut) (len=1 cap=4) {
  (*wire.TxOut)(0xc2113fe270)({
   Value: (int64) 10000000,
   RCDHash: (wire.RCDHash) (len=32 cap=32) {
    00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
    00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
   }
  })
 },
 ECOut: ([]*wire.TxEntryCreditOut) (cap=4) {
 },
