### ISSUE TITLE
Add Sha3 and Sh2

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#317]
Entry - Sha3 then sha2
Merkle root - Sha2
Block hash - Sha3

**Comment by m21** [comment]
https://github.com/FactomProject/btcd/commit/0e09fb125b1cb9807e3a63e9f35cec068cdf234c
modeled after ShaHash, sha3.Sum256() is the computation call to use.

**Comment by carryforward** [comment]
done
