### ISSUE TITLE
Integrate factoid block with dir block via channel

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#320]

**Comment by carryforward** [comment]
send the MR to processor

**Comment by m21** [comment]
This one sends the Block Hash to the processor:
https://github.com/FactomProject/btcd/commit/6fbf0f1c13f269686446fcb0e439d7f1d6ec5348
Right here:
https://github.com/FactomProject/btcd/commit/6fbf0f1c13f269686446fcb0e439d7f1d6ec5348#diff-0dae4fab22d811d9adb5fb8316803b84R284

**Comment by m21** [comment]
Need a message from the processor to begin Factoid block construction.

**Comment by PaulSnow** [comment]
Need to record MR of Factoid blocks into the Directory Blockchain.
We are sending EOM (End of Minute) messages to btcd (Factoid code).
