### ISSUE TITLE
btcctl functionality (mostly testing)

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#324]
Ensure all applicable RPC commands work with btcctl.
Prerequisite: https://github.com/FactomProject/WorkItems/issues/308

**Comment by m21** [comment]
```rm -rf ~/.btcd/data/factoid0```
run "factomd" for a minute or so
```btcctl -utestuser -Pnotarychain getblockcount```
5
```btcctl -utestuser -Pnotarychain getblockhash 0```
320442d7fb5873368119cac11f0d0d98be58ada384194b69c26dad8a84d4fe2f
```btcctl -utestuser -Pnotarychain getblock 320442d7fb5873368119cac11f0d0d98be58ada384194b69c26dad8a84d4fe2f```
  "hash": "320442d7fb5873368119cac11f0d0d98be58ada384194b69c26dad8a84d4fe2f",
  "confirmations": 6,
  "size": 293,
  "height": 0,
  "version": 1,
  "merkleroot": "0000000000000000000000000000000000000000000000000000000000000000",
  "tx": [
    "1a6a56b69e0c25f9c66005afb60e6d4cc225fefdb4bc9dff60a8514c5097c90b"
  ],
  "time": 0,
  "nonce": 2083236893,
  "bits": "1d00ffff",
  "difficulty": 0,
  "previousblockhash": "0000000000000000000000000000000000000000000000000000000000000000",
  "nextblockhash": "2b823f3286a6d1f7e612d816469180e64eeaadbf33cc791a16058b9a68d059b1"
```btcctl -utestuser -Pnotarychain getrawtransaction 1a6a56b69e0c25f9c66005afb60e6d4cc225fefdb4bc9dff60a8514c5097c90b```
00000000000004ff000000012a05f2000000000000000000000000000000000000000000000000000000000000000000ff00000002540be4000101010101010101010101010101010128c34f3a5e332a1fc7b2b73cf188910fff00000004a817c8000202020202020202020202020202020228c34f3a5e332a1fc7b2b73cf188910fff00000006fc23ac000303030303030303030303030303030328c34f3a5e332a1fc7b2b73cf188910f00010000000000000000000000000000000000000000000000000000000000000000feffffffff0000
(that is the genesis block transaction) from https://github.com/FactomProject/btcd/blob/bfcd2b5525c4fd9ab26a2c21c1926dfe5b64bdcc/chaincfg/genesis.go#L33

**Comment by m21** [comment]
for a verbose TX json dump see an example here: https://github.com/FactomProject/WorkItems/issues/307

**Comment by PaulSnow** [comment]
Is this still untested?
