### ISSUE TITLE
Validate a factoid block by MR via channel

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#325]

**Comment by PaulSnow** [comment]
Not needed, best we can tell.

**Comment by m21** [comment]
This part of initial start-up/validation (https://github.com/FactomProject/WorkItems/issues/356) is to be done in this work item:
"processor sends an internal message with current block height and factoid block MR
btcd validates the block height and MR, then sends an internal msg thru inCtlMsgQ."

step 1: make rpcwebsocket.go:rescanBlock work
step 2: check what other routines can be used for start-up validation (first 288 blocks logic)
step 3: tie it to the processor init channel handshake
