### ISSUE TITLE
Identity management and key management for fed server

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#327]
Creating the code to generate an Identity for the single server in the Genesis block needed to document the keys we hard code into the first Milestone 1 server.

**Comment by PaulSnow** [comment]
Created the SpecialChains.md document detailing identities and other information needed in the genesis block for Factom.

**Comment by PaulSnow** [comment]
Identity just needs to be recorded in the Genesis block.  Doesn't have to be supported in the code for Milestone 1.

**Comment by PaulSnow** [comment]
Creating the code to generate an Identity for the single server needed to document the keys we hard code into the first Milestone 1 server.

**Comment by JackXLu** [comment]
Need to document it and make it public

**Comment by PaulSnow** [comment]
Part of #457
