### ISSUE TITLE
READ Anchors (was: Reading and validating anchors in btc)

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#335]

**Comment by m21** [comment]
There are already 3 other similar issues - maybe consolidate?
https://github.com/FactomProject/WorkItems/issues/255
https://github.com/FactomProject/WorkItems/issues/323
https://github.com/FactomProject/WorkItems/issues/288

**Comment by PaulSnow** [comment]
duplicate issue

**Comment by JackXLu** [comment]
Manual validation should be good enough for MS1

**Comment by SirHalsell** [comment]
verified as correct. now since we have anchor chain and factom explorer, it'll be easy to do.
