### ISSUE TITLE
A Master Alert to freeze the network should some terrible thing happen that we must respond to.

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#337]
Bitcoin style

**Comment by PaulSnow** [comment]
This is the shutdown alert in case of some sort of failure that requires developers to fix.  Keeps the amount of backtracking required to a minimum.  Bitcoin also has this feature.

**Comment by m21** [comment]
Detect & force clients to upgrade. Code to be tested is here: https://github.com/FactomProject/btcd/commit/fef90d2d1d7059768518203a51d27cce986e39f0

**Comment by m21** [comment]
Was done, but got broken by someone, to be tracked here: https://github.com/FactomProject/WorkItems/issues/541
