### ISSUE TITLE
Factoid block header implementation, per spec

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#344]

**Comment by m21** [comment]
Actually do the header here: structs, genesis block rework, etc.
See item https://github.com/FactomProject/WorkItems/issues/346 for SHA & MR computations.

**Comment by m21** [comment]
This file & methods must conform to the spec: https://github.com/FactomProject/btcd/blob/c9e2360d9d299a67e9340fb53f1fdc16fb90f4c3/wire/blockheader.go#L33

**Comment by PaulSnow** [comment]
Was done, but now we need to consider changing the specification to remove the transaction count from the header, if it is critical to Factoids.

**Comment by m21** [comment]
Added TransCnt back for future use(s). Keeping the serializer/deserializer code same though.
https://github.com/FactomProject/btcd/commit/ff46a82231312671d0aca7e83f31a30d4a2af169#diff-5e7a68243613d7cd4ba7d60d067abb36R50
