### ISSUE TITLE
btcwallet integration

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#345]
WIP:
 [DBG] RPCS: Received command <getcurrentnet> from 127.0.0.1:58756
 [DBG] RPCS: Received command <getbestblock> from 127.0.0.1:58756
 [DBG] RPCS: Received command <notifyblocks> from 127.0.0.1:58756
 [DBG] RPCS: Received command <getblock> from 127.0.0.1:58756
 [DBG] RPCS: Received command <rescan> from 127.0.0.1:58756

**Comment by PaulSnow** [comment]
What is this?  How much time will it take?

**Comment by m21** [comment]
break it up into btcctl with commands
