### ISSUE TITLE
Factoid block header computations

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#346]
The logic & code to compute and insert/update the newly defined fields everywhere needed.

**Comment by PaulSnow** [comment]
What are these fields?  Just the Merkle root generation?   What is a "bad getblock output"?

**Comment by m21** [comment]
I'll watch the "bad getblock output" (a separate issue should disappear since we are changing the whole Factoid block header).
Before this WorkItem can be worked on, this one needs to be done: https://github.com/FactomProject/WorkItems/issues/344 ; the details of the Factoid block (header) are specified here: https://github.com/FactomProject/FactomDocs/blob/master/factomDataStructureDetails.md#factoid-block

But yes, computing the 2 MRs, the PrevHash3 of the block (header), BodySize (if affected in some manner) again everything in the spec document: https://github.com/FactomProject/FactomDocs/blob/master/factomDataStructureDetails.md#factoid-block is the effort I was trying to capture in this item.

**Comment by PaulSnow** [comment]
Not needed at this point.
