### ISSUE TITLE
genesis block insert check

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#348]
[DBG] BCDB: insert block sha c4861d09c53c10e6c9b80bde33251869aa1c64e79e9f65881be0cfb8a5c19c04
 [INF] BTCD: Inserted genesis block 320442d7fb5873368119cac11f0d0d98be58ada384194b69c26dad8a84d4fe2f
 [INF] BTCD: Block database loaded with block height 0
 [INF] BMGR: Generating initial block node index.  This may take a while...

Mismatch in expected hash is not detected in any way (?)

**Comment by PaulSnow** [comment]
What does this mean?   What is the estimate to fix?

**Comment by m21** [comment]
This is to verify the Factoid genesis block's hash is what it's expected to be:
compute the hash of the factoid genesis block and compare it to a hard-coded string

**Comment by m21** [comment]
insert check is here: https://github.com/FactomProject/btcd/commit/037d7aa1f8b9fbaef900e55682a24e66ebfce8db

**Comment by m21** [comment]
https://github.com/FactomProject/btcd/commit/d2c6b7d7e26c06ec112b6fadef53daf831c5884f
