### ISSUE TITLE
Apply Entry Credit/Factoid exchange rate changes on Factoid Component

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#354]
1. Store hard coded Exchange rate in Factoid block header
2. Send Entry Credits instead of factoids in the following obj

// Factoid Obj to carry factoid transation data to constuct the Process lit item.
type MsgInt_FactoidObj struct {
	FactoidTx    *MsgTx
	TxSha        *ShaHash
	EntryCredits map[ShaHash]uint64 // TODO: this should really be a single-hash per Brian (?)
}

**Comment by m21** [comment]
How would the wire (btcd) side know/be-told the Exchange Rate?

**Comment by m21** [comment]
The rate will get to the btcd-side possibly via the type MsgInt_EOM struct?

**Comment by JackXLu** [comment]
Added the rate into the MsgInt_EOM
