### ISSUE TITLE
Integration between Processor and Factoid component

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#356]
System startup:
If Block height = 0
processor sends an EOM message with block height (0)
btcd creates a Genesis block and send an internal message to doneFBlockQ
If Block height > 0
processor sends an internal message with current block height and factoid block MR
btcd validates the block height and MR, then sends an internal msg thru inCtlMsgQ. 
Error legs - if BlockHeight of Processor != that of btcd
processor > btcd : panic or send out P2P catch-up request
processor < btcd : btcd must delete all offending/invalid blocks above the given BlockHeight ASAP

**Comment by m21** [comment]
Step1: Processor will explicitly force genesis block creation via this message: https://github.com/FactomProject/btcd/commit/14a3ab92adbc03f8751bd78802519e8d264f51b3#diff-024a7c657872439e12ec87cde73ce164R31.
The returned hash will be sent to doneFBblockQ.
