### ISSUE TITLE
Download the missing blocks if Factoid chain has fallen behind DirBlock chain.

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#357]
Here (https://github.com/FactomProject/WorkItems/issues/356) the task is listed as:
"if BlockHeight of Processor != that of btcd i.e. processor > btcd : panic or send out P2P catch-up request"

**Comment by JackXLu** [comment]
Somehow this happens to me on Server:

## eomMsg 111 to inCtlMsgQueue #### TRACE: 2015-05-04.14:49:11 line 43 github.com/FactomProject/btcd.(*BlockTimer).StartBlockTimer file: /home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factomtimer.go
PROCESSOR: in ctlMsg, msg:&{EOM_Type:9 NextDBlockHeight:8 EC_Exchange_Rate:0}
## TRACE: 2015-05-04.14:49:11 line 365 github.com/FactomProject/btcd.serveMsgRequest file: /home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factomprocessor.go
## CmdInt_EOM #### TRACE: 2015-05-04.14:49:11 line 422 github.com/FactomProject/btcd.serveMsgRequest file: /home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factomprocessor.go
PROCESSOR: End of minute msg - wire.CmdInt_EOM:&{EOM_Type:9 NextDBlockHeight:8 EC_Exchange_Rate:0}
## eomMsg 111 to inCtlMsgQueue #### TRACE: 2015-05-04.14:49:17 line 43 github.com/FactomProject/btcd.(*BlockTimer).StartBlockTimer file: /home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factomtimer.go
PROCESSOR: in ctlMsg, msg:&{EOM_Type:10 NextDBlockHeight:8 EC_Exchange_Rate:0}
## TRACE: 2015-05-04.14:49:17 line 365 github.com/FactomProject/btcd.serveMsgRequest file: /home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factomprocessor.go
## CmdInt_EOM #### TRACE: 2015-05-04.14:49:17 line 422 github.com/FactomProject/btcd.serveMsgRequest file: /home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factomprocessor.go
PROCESSOR: End of minute msg - wire.CmdInt_EOM:&{EOM_Type:10 NextDBlockHeight:8 EC_Exchange_Rate:0}
## Notify the factoid component to start building factoid block #### TRACE: 2015-05-04.14:49:17 line 442 github.com/FactomProject/btcd.serveMsgRequest file: /home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factomprocessor.go
## TRACE: 2015-05-04.14:49:17 line 1059 github.com/FactomProject/btcd.buildBlocks file: /home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factomprocessor.go
in range outCtlMsgQueue, msg:&{EOM_Type:10 NextDBlockHeight:8 EC_Exchange_Rate:1000}
## next DB height= 8, type= 10
 #### TRACE: 2015-05-04.14:49:17 line 83 github.com/FactomProject/btcd.func·011 file: /home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom.go
## TRACE: 2015-05-04.14:49:17 line 51 github.com/FactomProject/btcd.generateFactoidBlock file: /home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom-gen.go
randRCD len= 32
## TRACE: 2015-05-04.14:49:17 line 312 github.com/FactomProject/btcd.factom_NewBlockTemplate file: /home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom-gen.go
panic: ERROR: globalHeight is 8 and nextBlockHeight is 9


goroutine 36 [running]:
runtime.panic(0xa01140, 0xc21060eaf0)
	/usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/FactomProject/btcd.factom_NewBlockTemplate(0xc210613e00, 0xed2f765501c79524, 0x44036eb768d9594, 0x501e06d84e6b6fcc, 0xfd17a1916785147e, ...)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom-gen.go:323 +0x225
github.com/FactomProject/btcd.generateFactoidBlock(0x7fce00000008)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom-gen.go:82 +0x298
github.com/FactomProject/btcd.func·011()
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom.go:89 +0x35d
created by github.com/FactomProject/btcd.factomForkInit
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom.go:139 +0xa9

goroutine 1 [chan receive]:
github.com/FactomProject/btcd.btcdMain(0x0, 0x0, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/btcd.go:148 +0x870
github.com/FactomProject/btcd.Start_btcd()
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom.go:179 +0x3dd
main.factomdMain(0x0, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:96 +0xba
main.main()
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:69 +0x21c

**Comment by m21** [comment]
Actually the factoid chain is longer than the dirblock chain, so the correct item to take of this condition is : https://github.com/FactomProject/WorkItems/issues/358
I'll make the wording a little more clear in the meantime (global = dirblock height):
```
panic: ERROR: globalHeight is 8 and nextBlockHeight is 9
```
What the error means: (during the previous run of factomd) a factoid block was ordered to be written and it got written, but the dirblock for the same height did not.
