### ISSUE TITLE
btcd/wire Tests are broken

### ISSUE THREAD

**Issue by PaulSnow** [FactomProject/WorkItems#373]
These tests are very complex.  Spent some hours trying to fix them, but wasn't too successful.  I'm particularly interested in tests that involve the header (since I am trying to fix the header to conform).

$ go test

This produces (among other results):

--- FAIL: TestBlockHeaderWire (0.00s)
	blockheader_test.go:120: Running 5 tests
	blockheader_test.go:131: writeBlockHeader #0
		 got: ([]uint8) (len=100 cap=160) {
		 00000000  00 00 00 01 6f e2 8c 0a  b6 f1 b3 72 c1 a6 a2 46  |....o......r...F|
		 00000010  ae 63 f7 4f 93 1e 83 65  e1 5a 08 9c 68 d6 19 00  |.c.O...e.Z..h...|
		 00000020  00 00 00 00 3b a3 ed fd  7a 7b 12 b2 7a c7 2c 3e  |....;...z{..z.,>|
		 00000030  67 76 8f 61 7f c8 1b c3  88 8a 51 32 3a 9f b8 aa  |gv.a......Q2:...|
		 00000040  4b 1e 5e 4a 00 00 00 00  00 00 00 00 00 00 00 00  |K.^J............|
		 00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
		 00000060  00 00 00 00                                       |....|
		}
		 want: ([]uint8) (len=80 cap=80) {
		 00000000  00 00 00 01 6f e2 8c 0a  b6 f1 b3 72 c1 a6 a2 46  |....o......r...F|
		 00000010  ae 63 f7 4f 93 1e 83 65  e1 5a 08 9c 68 d6 19 00  |.c.O...e.Z..h...|
		 00000020  00 00 00 00 3b a3 ed fd  7a 7b 12 b2 7a c7 2c 3e  |....;...z{..z.,>|
		 00000030  67 76 8f 61 7f c8 1b c3  88 8a 51 32 3a 9f b8 aa  |gv.a......Q2:...|
		 00000040  4b 1e 5e 4a 49 5f ab 29  1d 00 ff ff 00 01 e0 f3  |K.^JI_.)........|
		}

**Comment by PaulSnow** [comment]
We should comment out the tests we don't need.  Some of them look like we might have issues.

The "write to wire" and "read from wire" tests should be pitted against each other rather than hard coding binary data.  But that is just me.  If they worked, maybe keeping them up to date wouldn't be so hard.

**Comment by PaulSnow** [comment]
I am most concerned about the tests that ensure our wire protocol works, and that the data is being properly marshaled and unmarshaled.

**Comment by m21** [comment]
This is a duplicate, please see: https://github.com/FactomProject/WorkItems/issues/291
Also please see my comments on "Bits":
https://github.com/FactomProject/btcd/commit/d198280b026aa9946852000c3468001ded5253f4#commitcomment-11124044

**Comment by PaulSnow** [comment]
Duplicate
