### ISSUE TITLE
rename "btcwallet" to "fwallet"

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#376]
new repo; WIP

**Comment by m21** [comment]
@carryforward ideas here please

**Comment by m21** [comment]
https://github.com/FactomProject/fwallet/commit/e0240d5add43ed32f6929277a1b4c780328adade

**Comment by carryforward** [comment]
talked with more market oriented people here.  Lets do factwallet

**Comment by m21** [comment]
https://github.com/FactomProject/fctwallet/tree/development

**Comment by m21** [comment]
compiling, done : https://github.com/FactomProject/fctwallet/commit/4e6b61654d9bcccc9fa76812f2449199b9d64ca1
