### ISSUE TITLE
Wire message for simple coin transaction

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#399]
M.Y - Pls check with Paul on this. Thanks!

**Comment by JackXLu** [comment]
Paul has checked in the msg transaction. Can u take it from here?

**Comment by m21** [comment]
This could probably be pushed out to MS2, right @JackXLu  ?

**Comment by m21** [comment]
The last remaining piece: https://github.com/FactomProject/FactomCode/commit/1806cfbc1a1c560110514bee01a6fbcb94480e0d
Needs testing.
