### ISSUE TITLE
panic: checkpoints must be disabled and they are NOT !!!

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#403]
## init RPC client #### TRACE: 2015-06-11.18:30:16 line 325 github.com/FactomProject/FactomCode/anchor.i
13:30:16 2015-06-11 [WRN] BTCD: open \tmp\factoid.conf: The system cannot find the file specified.
2015/06/11 13:30:16 read factom config file:  C:\Users\luxujun/.factom/factomd.conf
cannot read rpc.cert file: open C:\Users\luxujun\AppData\Local\Btcwallet\rpc.cert: The system cannot fin
2015/06/11 13:30:16 dBlock.Header.MerkleRoot:  67a08a4e64b468d5a2355129730e44968e16f92fe31e9d3fe1dad8763
2015/06/11 13:30:16 entry.MerkleRoot:  c922aeac89eedf19bdded51757d26571c79b8c0c4e8f4a460446cc3612c67d4a
2015/06/11 13:30:16 entry.MerkleRoot:  e29a284df131b20396bcd1786699e5e6fe1beaecf3e8b8edcf1ff46a708f40c3
2015/06/11 13:30:16 entry.MerkleRoot:  85cd60721b5e92080b0bfdc0102868cbea2a4672907cf35ba86fe19e17199d2d
PROCESSOR: in ctlMsg, msg:&{EOM_Type:1 NextDBlockHeight:1 EC_Exchange_Rate:0}
## ## TRACE: 2015-06-11.18:30:16 line 292 github.com/FactomProject/btcd.serveMsgRequest file: C:/Go/work
TRACE: 2015-06-11.18:30:16 line 1447 github.com/FactomProject/btcd.newBlockManager file: C:/Go/workspace
## CmdInt_EOM #### ## testuser #### TRACE: 2015-06-11.18:30:16 line 335 github.com/FactomProject/btcd.se
TRACE: 2015-06-11.18:30:16 line 532 github.com/FactomProject/btcd.newRPCServer file: C:/Go/workspace/src
## notarychain #### TRACE: 2015-06-11.18:30:16 line 534 github.com/FactomProject/btcd.newRPCServer file:
PROCESSOR: End of minute msg - wire.CmdInt_EOM:&{EOM_Type:1 NextDBlockHeight:1 EC_Exchange_Rate:0}
## ## TRACE: 2015-06-11.18:30:16 line 263 github.com/FactomProject/btcd.(*blockManager).factomChecks fil
panic: checkpoints must be disabled and they are NOT !!!

goroutine 67 [running]:
github.com/FactomProject/btcd.(*blockManager).factomChecks(0xc0821560a0)
        C:/Go/workspace/src/github.com/FactomProject/btcd/factom.go:273 +0x37c
github.com/FactomProject/btcd.(*blockManager).Start(0xc0821560a0)
        C:/Go/workspace/src/github.com/FactomProject/btcd/blockmanager.go:1350 +0x153
github.com/FactomProject/btcd.(*server).peerHandler(0xc08217e000)
        C:/Go/workspace/src/github.com/FactomProject/btcd/server.go:566 +0x7c
created by github.com/FactomProject/btcd.(*server).Start
        C:/Go/workspace/src/github.com/FactomProject/btcd/server.go:904 +0x279

goroutine 1 [runnable]:
sync.(*Mutex).Lock(0xc08200e140)
        c:/go/src/sync/mutex.go:66 +0xda
os.(*File).write(0xc082044008, 0xc082064200, 0x92, 0x100, 0x0, 0x0, 0x0)
        c:/go/src/os/file_windows.go:375 +0x8a
os.(*File).Write(0xc082044008, 0xc082064200, 0x92, 0x100, 0x4, 0x0, 0x0)
        c:/go/src/os/file.go:139 +0x9e
fmt.Fprintf(0x3021b8, 0xc082044008, 0xd72c70, 0x1e, 0xc08268fce0, 0x4, 0x4, 0xc0820c8860, 0x0, 0x0)
        c:/go/src/fmt/print.go:189 +0xb3
fmt.Printf(0xd72c70, 0x1e, 0xc08268fce0, 0x4, 0x4, 0xc082687920, 0x0, 0x0)
        c:/go/src/fmt/print.go:197 +0xa2
github.com/FactomProject/FactomCode/util.Trace(0x0, 0x0, 0x0)
        C:/Go/workspace/src/github.com/FactomProject/FactomCode/util/misc.go:30 +0x58e
github.com/FactomProject/btcd.factomForkInit(0xc08217e000)
        C:/Go/workspace/src/github.com/FactomProject/btcd/factom.go:45 +0x63
github.com/FactomProject/btcd.btcdMain(0x0, 0x0, 0x0)
        C:/Go/workspace/src/github.com/FactomProject/btcd/btcd.go:140 +0x719
github.com/FactomProject/btcd.Start_btcd()
        C:/Go/workspace/src/github.com/FactomProject/btcd/factom.go:164 +0x93
main.factomdMain(0x0, 0x0)
        C:/Go/workspace/src/github.com/FactomProject/FactomCode/factomd/factomd.go:91 +0xb8
main.main()
        C:/Go/workspace/src/github.com/FactomProject/FactomCode/factomd/factomd.go:76 +0x344

**Comment by m21** [comment]
Sometimes running clean, such as "go clean -r -i -x" helps.

**Comment by m21** [comment]
done: https://github.com/FactomProject/btcd/commit/3d63bf6ecbb1068fa9e155c318897b5caeafbabc
