### ISSUE TITLE
Add Random Source for Address Generation

### ISSUE THREAD

**Issue by PaulSnow** [FactomProject/WorkItems#412]
This is required for secure deterministic wallets.  The user should be able to add some random data, and the wallet provide a set of words.  Those words can be used to recreate the random source and thus recover the wallet.

**Comment by PaulSnow** [comment]
Looks like we will start with 128 bits of random source

Use Sha512 to hash to a 64 byte value, the low order 32 bytes will be the private key 

Brian will provide a library that lets me gen the public key

Then we will use Sha512 to hash to get the next key in the sequence.  Etc.

**Comment by PaulSnow** [comment]
Provide the link to the library.

**Comment by carryforward** [comment]
closed
https://github.com/FactomProject/factoid/commit/32995b8afddf7181dddca71eecc9f70fa0ce8377
