### ISSUE TITLE
CLI Cleanup

### ISSUE THREAD

**Issue by PaulSnow** [FactomProject/WorkItems#419]
Need to make things nicer and cleaner

Add Verbose mode
Decimal places in Factoid amounts.
?

**Comment by PaulSnow** [comment]
Looking much cleaner.  Assigned to Robert to Validate

**Comment by drobertbaker** [comment]
Some interesting results in trying to create transactions:

~$ factom-cli getfee
Fee: 0.00666667

~$ factom-cli newtransaction transaction112
Success building a transaction
~$ factom-cli addinput transaction112 factoidwalletaddressname03 0.00666667
Success adding Input
~$ factom-cli sign transaction112
Success signing transaction
~$ factom-cli submit transaction112
The transaction did not validate
~
~$ factom-cli newtransaction transaction212
Success building a transaction
~$ factom-cli addinput transaction212 factoidwalletaddressname03 0.00666668
strconv.ParseInt: parsing "00666668": invalid syntax
~$ factom-cli sign transaction212
Must have at least one input
~$ factom-cli submit transaction212
Could not validate all the signatures of the transaction

~$ factom-cli newtransaction transaction412
Success building a transaction
~$ factom-cli addinput transaction412 factoidwalletaddressname03 0.0066667
Success adding Input
~$ factom-cli sign transaction412
Success signing transaction
~$ factom-cli submit transaction412
The transaction did not validate

~$ factom-cli newtransaction transaction612
Success building a transaction
~$ factom-cli addinput transaction612 factoidwalletaddressname03 0.006667
Success adding Input
~$ factom-cli sign transaction612
Success signing transaction
~$ factom-cli submit transaction612
The transaction did not validate

~$ factom-cli newtransaction transaction712
Success building a transaction
~$ factom-cli addinput transaction712 factoidwalletaddressname03 0.00667
Success adding Input
~$ factom-cli sign transaction712
Success signing transaction
~$ factom-cli submit transaction712
The transaction did not validate

~$ factom-cli newtransaction transaction812
Success building a transaction
~$ factom-cli addinput transaction812 factoidwalletaddressname03 0.0067
Success adding Input
~$ factom-cli sign transaction812
Success signing transaction
~$ factom-cli submit transaction812
The transaction did not validate
~
~$ factom-cli newtransaction transaction912
Success building a transaction
~$ factom-cli addinput transaction912 factoidwalletaddressname03 0.007
Success adding Input
~$ factom-cli sign transaction912
Success signing transaction
~$ factom-cli submit transaction912
The transaction did not validate

~$ factom-cli newtransaction transaction1012
Success building a transaction
~$ factom-cli addinput transaction1012 factoidwalletaddressname03 0.07
Success adding Input
~$ factom-cli sign transaction1012
Success signing transaction
~$ factom-cli submit transaction1012
Successfully submitted the transaction
~



On Sun, Jul 5, 2015 at 5:15 PM, Paul Snow <notifications@github.com> wrote:

> Assigned #419 <https://github.com/FactomProject/WorkItems/issues/419> to
> @drobertbaker <https://github.com/drobertbaker>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FactomProject/WorkItems/issues/419#event-348128919>.
>



-- 
Thanks,
D. Robert Baker
Process Integration Manager, factom
drobertbaker@factom.org
