### ISSUE TITLE
Put config files in the right directory

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#42]

**Comment by sugruedes** [comment]
My vote is $FACTOM_HOME env to act as a base for the [multiple] config files, log files, etc. the system will need. Although I can see the need for a config server in the near future. Something that can hash passwds at a minimum as clear text passwds in config files is a no-no.
basedir := Getenv("FACTOM_HOME")

**Comment by michaelbeam** [comment]
util.ReadConfig() currently looks for the conf file in $HOME/.factom/ and used a default conf if the file isn't found. Adding $FACTOM to env is under consideration.
