### ISSUE TITLE
fctctl now just hangs

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#420]
after all the latest code

**Comment by PaulSnow** [comment]
Not sure what this is.

**Comment by m21** [comment]
fctctl is the btcd-side RPC client/tool to manage the peer network & other things (used to be wallet). MS2

**Comment by m21** [comment]
fixed in tags 00001:
https://github.com/FactomProject/FactomCode/releases/tag/00001
https://github.com/FactomProject/btcd/releases/tag/00001
with help from:
https://github.com/FactomProject/WorkItems/issues/614
