### ISSUE TITLE
Panic error in building factoid MR

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#439]
goroutine 17 [running]:
runtime.panic(0xaf41e0, 0x16edc60)
	/usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/FactomProject/factoid.BuildMerkleTreeStore(0x1705af0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jlu/workspace2/go/src/github.com/FactomProject/factoid/merkle.go:51 +0x77
github.com/FactomProject/factoid.ComputeMerkleRoot(0x1705af0, 0x0, 0x0, 0x1705af0, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/factoid/merkle.go:40 +0x3b
github.com/FactomProject/factoid/block.(*FBlock).CalculateHashes(0xc210159900)
	/home/jlu/workspace2/go/src/github.com/FactomProject/factoid/block/scblock.go:285 +0x1b8
github.com/FactomProject/factoid/block.(*FBlock).GetHash(0xc210159900, 0xc2101eb9a0, 0xbc)
	/home/jlu/workspace2/go/src/github.com/FactomProject/factoid/block/scblock.go:88 +0xf6
github.com/FactomProject/FactomCode/database/ldb.(*LevelDb).ProcessFBlockBatch(0xc2100f8690, 0x7fd2fe4ade40, 0xc210159900, 0x0, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/database/ldb/scblock.go:28 +0x124
github.com/FactomProject/FactomCode/process.newFactoidBlock(0xc2100c0a80, 0xc2100c0480, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/processor.go:1016 +0x288
github.com/FactomProject/FactomCode/process.buildBlocks(0xc2100202d0, 0xa2c2b)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/processor.go:818 +0x1b7
github.com/FactomProject/FactomCode/process.serveMsgRequest(0x7fd2fe4ae4a0, 0xc210114ec0, 0x1e, 0x7fd2fe30af00)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/processor.go:285 +0x2ac8
github.com/FactomProject/FactomCode/process.Start_Processor(0x7fd2fe4ac530, 0xc2100f8690, 0xc210110000, 0xc210110800, 0xc210111000, ...)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/processor.go:199 +0x423
created by main.factomdMain
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:88 +0x7a

goroutine 1 [chan receive]:
github.com/FactomProject/btcd.btcdMain(0x0, 0x0, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/btcd.go:156 +0x69f
github.com/FactomProject/btcd.Start_btcd(0x7fd2fe4ac530, 0xc2100f8690, 0xc210110000, 0xc210110800, 0xc210111000, ...)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom.go:186 +0x1b6
main.factomdMain(0x0, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:108 +0x291
main.main()
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:79 +0x238

goroutine 3 [syscall]:
os/signal.loop()
	/usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 4 [semacquire]:
sync.runtime_Syncsemacquire(0xc21009b690)
	/usr/local/go/src/pkg/runtime/sema.goc:257 +0xca
sync.(*Cond).Wait(0xc21009b680)
	/usr/local/go/src/pkg/sync/cond.go:62 +0x89
github.com/FactomProject/seelog.(*asyncLoopLogger).processItem(0xc21004f9c0, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:50 +0x95
github.com/FactomProject/seelog.(*asyncLoopLogger).processQueue(0xc21004f9c0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:63 +0x31
created by github.com/FactomProject/seelog.newAsyncLoopLogger
	/home/jlu/workspace2/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:40 +0x74

goroutine 5 [semacquire]:
sync.runtime_Syncsemacquire(0xc21009b810)
	/usr/local/go/src/pkg/runtime/sema.goc:257 +0xca
sync.(*Cond).Wait(0xc21009b800)
	/usr/local/go/src/pkg/sync/cond.go:62 +0x89
github.com/FactomProject/seelog.(*asyncLoopLogger).processItem(0xc21004fae0, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:50 +0x95
github.com/FactomProject/seelog.(*asyncLoopLogger).processQueue(0xc21004fae0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:63 +0x31
created by github.com/FactomProject/seelog.newAsyncLoopLogger
	/home/jlu/workspace2/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:40 +0x74

goroutine 7 [semacquire]:
sync.runtime_Syncsemacquire(0xc21000a750)
	/usr/local/go/src/pkg/runtime/sema.goc:257 +0xca
sync.(*Cond).Wait(0xc21000a740)
	/usr/local/go/src/pkg/sync/cond.go:62 +0x89
github.com/btcsuitereleases/seelog.(*asyncLoopLogger).processItem(0xc21004f6c0, 0x419300)
	/home/jlu/workspace2/go/src/github.com/btcsuitereleases/seelog/behavior_asynclooplogger.go:50 +0x95
github.com/btcsuitereleases/seelog.(*asyncLoopLogger).processQueue(0xc21004f6c0)
	/home/jlu/workspace2/go/src/github.com/btcsuitereleases/seelog/behavior_asynclooplogger.go:63 +0x31
created by github.com/btcsuitereleases/seelog.newAsyncLoopLogger
	/home/jlu/workspace2/go/src/github.com/btcsuitereleases/seelog/behavior_asynclooplogger.go:40 +0x74

goroutine 8 [semacquire]:
sync.runtime_Syncsemacquire(0xc21000aa90)
	/usr/local/go/src/pkg/runtime/sema.goc:257 +0xca
sync.(*Cond).Wait(0xc21000aa80)
	/usr/local/go/src/pkg/sync/cond.go:62 +0x89
github.com/btcsuitereleases/seelog.(*asyncLoopLogger).processItem(0xc21004f7e0, 0x0)
	/home/jlu/workspace2/go/src/github.com/btcsuitereleases/seelog/behavior_asynclooplogger.go:50 +0x95
github.com/btcsuitereleases/seelog.(*asyncLoopLogger).processQueue(0xc21004f7e0)
	/home/jlu/workspace2/go/src/github.com/btcsuitereleases/seelog/behavior_asynclooplogger.go:63 +0x31
created by github.com/btcsuitereleases/seelog.newAsyncLoopLogger
	/home/jlu/workspace2/go/src/github.com/btcsuitereleases/seelog/behavior_asynclooplogger.go:40 +0x74

goroutine 9 [syscall]:
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1394

goroutine 10 [select]:
github.com/FactomProject/goleveldb/leveldb/util.(*BufferPool).drain(0xc210045a80)
	/home/jlu/workspace2/go/src/github.com/FactomProject/goleveldb/leveldb/util/buffer_pool.go:205 +0x1e7
created by github.com/FactomProject/goleveldb/leveldb/util.NewBufferPool
	/home/jlu/workspace2/go/src/github.com/FactomProject/goleveldb/leveldb/util/buffer_pool.go:236 +0x224

goroutine 12 [select]:
github.com/FactomProject/goleveldb/leveldb.(*DB).compactionError(0xc210057dc0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/goleveldb/leveldb/db_compaction.go:120 +0x397
created by github.com/FactomProject/goleveldb/leveldb.openDB
	/home/jlu/workspace2/go/src/github.com/FactomProject/goleveldb/leveldb/db.go:126 +0x4d8

goroutine 13 [select]:
github.com/FactomProject/goleveldb/leveldb.(*DB).mpoolDrain(0xc210057dc0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/goleveldb/leveldb/db_state.go:73 +0x104
created by github.com/FactomProject/goleveldb/leveldb.openDB
	/home/jlu/workspace2/go/src/github.com/FactomProject/goleveldb/leveldb/db.go:127 +0x4ef

goroutine 14 [select]:
github.com/FactomProject/goleveldb/leveldb.(*DB).tCompaction(0xc210057dc0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/goleveldb/leveldb/db_compaction.go:812 +0x6a8
created by github.com/FactomProject/goleveldb/leveldb.openDB
	/home/jlu/workspace2/go/src/github.com/FactomProject/goleveldb/leveldb/db.go:130 +0x530

goroutine 15 [select]:
github.com/FactomProject/goleveldb/leveldb.(*DB).mCompaction(0xc210057dc0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/goleveldb/leveldb/db_compaction.go:759 +0x1f3
created by github.com/FactomProject/goleveldb/leveldb.openDB
	/home/jlu/workspace2/go/src/github.com/FactomProject/goleveldb/leveldb/db.go:131 +0x547

goroutine 16 [select]:
github.com/FactomProject/goleveldb/leveldb.(*DB).jWriter(0xc210057dc0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/goleveldb/leveldb/db_write.go:37 +0x13d
created by github.com/FactomProject/goleveldb/leveldb.openDB
	/home/jlu/workspace2/go/src/github.com/FactomProject/goleveldb/leveldb/db.go:132 +0x55e

goroutine 18 [IO wait]:
net.runtime_pollWait(0x7fd2fe4adad8, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc210147450, 0x72, 0x7fd2fe4a4098, 0xb)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc210147450, 0xb, 0x7fd2fe4a4098)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).accept(0xc2101473f0, 0xd69710, 0x0, 0x7fd2fe4a4098, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:382 +0x2c2
net.(*TCPListener).AcceptTCP(0xc21011b380, 0x18, 0xc21011f810, 0x64a023)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:233 +0x47
net.(*TCPListener).Accept(0xc21011b380, 0x50, 0x1706f00, 0x18, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:243 +0x27
net/http.(*Server).Serve(0xc2100f8eb0, 0x7fd2fe4acb10, 0xc21011b380, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1622 +0x91
net/http.Serve(0x7fd2fe4acb10, 0xc21011b380, 0x7fd2fe4adb80, 0xc21012cb70, 0x7fd2fe4acb10, ...)
	/usr/local/go/src/pkg/net/http/server.go:1561 +0x70
github.com/hoisie/web.(*Server).Run(0xc2101021c0, 0xc210118190, 0xe)
	/home/jlu/workspace2/go/src/github.com/hoisie/web/server.go:155 +0x4ae
created by github.com/FactomProject/FactomCode/wsapi.Start
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/wsapi/wsapi.go:63 +0x6bd

goroutine 19 [sleep]:
time.Sleep(0x165a0bc00)
	/usr/local/go/src/pkg/runtime/time.goc:31 +0x31
github.com/FactomProject/FactomCode/process.(*BlockTimer).StartBlockTimer(0xc2100f5320)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/timer.go:39 +0x100
created by github.com/FactomProject/FactomCode/process.Start_Processor
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/processor.go:180 +0x117

goroutine 20 [semacquire]:
sync.runtime_Syncsemacquire(0xc2101b4190)
	/usr/local/go/src/pkg/runtime/sema.goc:257 +0xca
sync.(*Cond).Wait(0xc2101b4180)
	/usr/local/go/src/pkg/sync/cond.go:62 +0x89
github.com/FactomProject/seelog.(*asyncAdaptiveLogger).processItem(0xc210149380, 0xc2101d3300, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/seelog/behavior_adaptivelogger.go:94 +0x9e
github.com/FactomProject/seelog.(*asyncAdaptiveLogger).processQueue(0xc210149380)
	/home/jlu/workspace2/go/src/github.com/FactomProject/seelog/behavior_adaptivelogger.go:119 +0x31
created by github.com/FactomProject/seelog.newAsyncAdaptiveLogger
	/home/jlu/workspace2/go/src/github.com/FactomProject/seelog/behavior_adaptivelogger.go:84 +0x3a8

goroutine 21 [select]:
github.com/FactomProject/btcd.mainInterruptHandler()
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/signal.go:38 +0x3c4
created by github.com/FactomProject/btcd.addInterruptHandler
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/signal.go:86 +0xdd

goroutine 22 [IO wait]:
net.runtime_pollWait(0x7fd2fe4ada30, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc2101af6f0, 0x72, 0x7fd2fe4a4098, 0xb)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc2101af6f0, 0xb, 0x7fd2fe4a4098)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).accept(0xc2101af690, 0xd69710, 0x0, 0x7fd2fe4a4098, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:382 +0x2c2
net.(*TCPListener).AcceptTCP(0xc21011ba38, 0xc2101cc000, 0x2, 0x2)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:233 +0x47
net.(*TCPListener).Accept(0xc21011ba38, 0x0, 0x25, 0xc2101cc000, 0x2)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:243 +0x27
github.com/FactomProject/btcd.(*server).listenHandler(0xc2101132a0, 0x7fd2fe4acb10, 0xc21011ba38)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/server.go:504 +0x175
created by github.com/FactomProject/btcd.(*server).Start
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/server.go:922 +0x18d

goroutine 23 [select]:
github.com/FactomProject/btcd.(*server).peerHandler(0xc2101132a0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/server.go:612 +0xb4c
created by github.com/FactomProject/btcd.(*server).Start
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/server.go:928 +0x1ec

goroutine 24 [chan receive]:
github.com/FactomProject/btcd.func·010()
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom.go:47 +0x51
created by github.com/FactomProject/btcd.factomForkInit
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom.go:70 +0x9b

goroutine 25 [chan receive]:
github.com/FactomProject/btcd.func·011()
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom.go:73 +0x3e
created by github.com/FactomProject/btcd.factomForkInit
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom.go:131 +0xa9

goroutine 26 [select]:
github.com/FactomProject/btcd/addrmgr.(*AddrManager).addressHandler(0xc2100a6c00)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/addrmgr/addrmanager.go:344 +0x1d6
created by github.com/FactomProject/btcd/addrmgr.(*AddrManager).Start
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/addrmgr/addrmanager.go:555 +0x1c6

goroutine 27 [select]:
github.com/FactomProject/btcd.(*blockManager).blockHandler(0xc210149480)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/blockmanager.go:1072 +0xa9d
created by github.com/FactomProject/btcd.(*blockManager).Start
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/blockmanager.go:1359 +0x140

goroutine 29 [semacquire]:
sync.runtime_Semacquire(0xc2100f3008)
	/usr/local/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*WaitGroup).Wait(0xc210113348)
	/usr/local/go/src/pkg/sync/waitgroup.go:127 +0x14b
github.com/FactomProject/btcd.(*server).WaitForShutdown(0xc2101132a0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/server.go:994 +0x36
github.com/FactomProject/btcd.func·004()
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/btcd.go:149 +0x29
created by github.com/FactomProject/btcd.btcdMain
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/btcd.go:152 +0x683

goroutine 34 [sleep]:
time.Sleep(0x4a817c800)
	/usr/local/go/src/pkg/runtime/time.goc:31 +0x31
github.com/FactomProject/btcd.func·021()
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/peer.go:2105 +0x19d
created by github.com/FactomProject/btcd.newOutboundPeer
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/peer.go:2127 +0x54d

**Comment by JackXLu** [comment]
It happened again on server:
02:29:39 2015-07-03 [DBG] PEER: write: Sending pong to 24.55.15.67:61953 (inbound)
02:29:39 2015-07-03 [DBG] PEER: write: (*wire.MsgPong)(0xc210c57cb8)({
 Nonce: (uint64) 2998529037763703870
})

## CmdInt_EOM #### TRACE: 2015-07-03.02:30:00 line 266 github.com/FactomProject/FactomCode/process.serveMsgRequest file: /home/factom/go/src/github.com/FactomProject/FactomCode/process/processor.go
## TRACE: 2015-07-03.02:30:00 line 798 github.com/FactomProject/FactomCode/process.buildBlocks file: /home/factom/go/src/github.com/FactomProject/FactomCode/process/processor.go
processor: currentBlock=Transaction Block
  ChainID:       000000000000000000000000000000000000000000000000000000000000000f
  MerkleRoot:    0000000000000000000000000000000000000000000000000000000000000000
  PrevBlock:     0000000000000000000000000000000000000000000000000000000000000000
  PrevHash3:     0000000000000000000000000000000000000000000000000000000000000000
  ExchRate:      00000000000a2c2b
  DBHeight:      000000bc
  UTXOCommit:    0000000000000000000000000000000000000000000000000000000000000000
  #Transactions: 0000000000000000
  Body Size:     0000000000000000


panic: runtime error: makeslice: len out of range

goroutine 17 [running]:
runtime.panic(0xaf63c0, 0x16f1c60)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/FactomProject/factoid.BuildMerkleTreeStore(0x1709b10, 0x0, 0x0, 0x0, 0x0, ...)
	/home/factom/go/src/github.com/FactomProject/factoid/merkle.go:51 +0x77
github.com/FactomProject/factoid.ComputeMerkleRoot(0x1709b10, 0x0, 0x0, 0x1709b10, 0x0)
	/home/factom/go/src/github.com/FactomProject/factoid/merkle.go:40 +0x3b
github.com/FactomProject/factoid/block.(*FBlock).CalculateHashes(0xc2104aa380)
	/home/factom/go/src/github.com/FactomProject/factoid/block/scblock.go:285 +0x1b8
github.com/FactomProject/factoid/block.(*FBlock).GetHash(0xc2104aa380, 0xc210c372c0, 0xbc)
	/home/factom/go/src/github.com/FactomProject/factoid/block/scblock.go:88 +0xf6
github.com/FactomProject/FactomCode/database/ldb.(*LevelDb).ProcessFBlockBatch(0xc2103fc500, 0x7f7a1d9a6780, 0xc2104aa380, 0x0, 0x0)
	/home/factom/go/src/github.com/FactomProject/FactomCode/database/ldb/scblock.go:28 +0x124
github.com/FactomProject/FactomCode/process.newFactoidBlock(0xc2104799f0, 0xc2101805a0, 0x0)
	/home/factom/go/src/github.com/FactomProject/FactomCode/process/processor.go:1016 +0x288
github.com/FactomProject/FactomCode/process.buildBlocks(0xc21001f2d0, 0xa2c2b)
	/home/factom/go/src/github.com/FactomProject/FactomCode/process/processor.go:818 +0x1b7
github.com/FactomProject/FactomCode/process.serveMsgRequest(0x7f7a1c08fc70, 0xc2100fe3c0, 0x1e, 0x7f7a1d7e6f00)
	/home/factom/go/src/github.com/FactomProject/FactomCode/process/processor.go:285 +0x2ac8
github.com/FactomProject/FactomCode/process.Start_Processor(0x7f7a1d9988c8, 0xc2103fc500, 0xc2100f4000, 0xc2100f4800, 0xc2100f5000, ...)
	/home/factom/go/src/github.com/FactomProject/FactomCode/process/processor.go:199 +0x423
created by main.factomdMain
	/home/factom/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:88 +0x7a

goroutine 1 [chan receive]:
github.com/FactomProject/btcd.btcdMain(0x0, 0x0, 0x0)
	/home/factom/go/src/github.com/FactomProject/btcd/btcd.go:156 +0x69f
github.com/FactomProject/btcd.Start_btcd(0x7f7a1d9988c8, 0xc2103fc500, 0xc2100f4000, 0xc2100f4800, 0xc2100f5000, ...)
	/home/factom/go/src/github.com/FactomProject/btcd/factom.go:186 +0x1b6
main.factomdMain(0x0, 0x0)
	/home/factom/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:108 +0x291
main.main()
	/home/factom/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:79 +0x238

goroutine 3 [syscall]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 4 [semacquire]:
sync.runtime_Syncsemacquire(0xc2100a2650)
	/usr/lib/go/src/pkg/runtime/sema.goc:257 +0xca
sync.(*Cond).Wait(0xc2100a2640)
	/usr/lib/go/src/pkg/sync/cond.go:62 +0x89
github.com/FactomProject/seelog.(*asyncLoopLogger).processItem(0xc210056960, 0x0)
	/home/factom/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:50 +0x95
github.com/FactomProject/seelog.(*asyncLoopLogger).processQueue(0xc210056960)
	/home/factom/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:63 +0x31
created by github.com/FactomProject/seelog.newAsyncLoopLogger
	/home/factom/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:40 +0x74

**Comment by PaulSnow** [comment]
Fixed Initialization of Factoids on reboot.
