### ISSUE TITLE
factom API WALLET ADDRESS NAMEs need to be filtered

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#440]
Allowable FACTOID WALLET and entry credit wallet
ADDRESS  NAMES 
need TO BE LIMITED TO:
length <=32 characters
and CHARACTER Set:
[A-Z 0-9 a-z -_ ]

1. Disallow creation of names that do not meet these criteria
2. Disallow request for balance of names that do not meet these criteria
3. Return rejection message with explanation on rejection

**Comment by PaulSnow** [comment]
Assigned to Robert to validate

**Comment by drobertbaker** [comment]
OK
