### ISSUE TITLE
Factoid transaction infinite loop issue on the network

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#441]

**Comment by JackXLu** [comment]
case wire.CmdFactoidTX:
		util.Trace("some mode: CmdFactoidTX")

		if nodeMode == common.SERVER_NODE {
			util.Trace("server mode; TODO")
			t := (msg.(*wire.MsgFactoidTX)).Transaction
			if common.FactoidState.AddTransaction(t) {
				fmt.Println("Recorded:")
				for _, ecout := range t.GetECOutputs() {

					pub := new([32]byte)
					copy(pub[:], ecout.GetAddress().Bytes())
					th := common.NewHash()
					th.SetBytes(t.GetHash().Bytes())
					credits := int32(ecout.GetAmount() / uint64(FactoshisPerCredit))
					processBuyEntryCredit(pub, credits, th)
					incBal := common.NewIncreaseBalance(pub, th, credits)

					ecchain.NextBlock.AddEntry(incBal)
				}
			} else {
				fmt.Println("Failed:")
			}
			fmt.Println(t)
		} else {
			// client-mode, milestone 1 - transmit to the server node
			util.Trace("client mode; TODO")
			// TODO: test ...
			outMsgQueue <- msg
		}

**Comment by m21** [comment]
@JackXLu @SirHalsell -- any obvious issues here?

**Comment by m21** [comment]
A fluke, the code path is exactly the same for commits, reveals, factoids.
