### ISSUE TITLE
factom API transaction parameters must be restricted

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#444]
All parameters in a factom API transaction
(input, output, and ecoutput)
must be filtered and limited to be:
> 0, and
< 9223372036854775806
If outside of this range, the adding of the parameter to the transaction must be rejected and the user informed as to the reason why.

**Comment by PaulSnow** [comment]
Because factom is fixed point, the actual maximum number we can deal with is 
9223372036854775806 / 100000000, or
92,233,720,368.54775806

Which is just over 92 billion, plenty of space give we are starting out with only ~8 million factoids and a maximum inflation rate of 2400 factoids per day.

**Comment by PaulSnow** [comment]
Fixed.  Assigned to Robert to validate

**Comment by drobertbaker** [comment]
OK
