### ISSUE TITLE
Monitor factom main server with nagios

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#446]
Pls add back the email notification program

**Comment by michaelbeam** [comment]
! send email if factomd or btcd go down
! send email if ec2 instance goes down

**Comment by michaelbeam** [comment]
email will be send if runfactom.sh stops

**Comment by michaelbeam** [comment]
Nagios server is setup with some basic monitoring.

! create custom nagios plugin to monitor the factomd process

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/18/2016
