### ISSUE TITLE
Capture errors when server goes down

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#451]

**Comment by m21** [comment]
Need some examples of when that happened: approximate time & exact date.

**Comment by JackXLu** [comment]
The server appeared to have stopped unexpectedly. Please look into the following log files:

/home/factom/.factom/logs/backup/factom-d.log
/home/factom/backup/logs/factomd_18815_19465.log

16:00:57 2015-07-10 [DBG] PEER: Can't read message from 72.177.124.211:58215 (inbound): EOF
16:00:57 2015-07-10 [INF] PEER: disconnecting 72.177.124.211:58215 (inbound)
16:00:57 2015-07-10 [DBG] SRVR: Removed peer 72.177.124.211:58215 (inbound)
16:00:57 2015-07-10 [INF] BMGR: Lost peer 72.177.124.211:58215 (inbound)

**Comment by m21** [comment]
The messages above are harmless: they indicate a client has disconnected.
I see you tweaked the run*sh script -- it won't capture errors anymore like that; will chat offline.

**Comment by m21** [comment]
Restored script to ensure capture of all panics: https://github.com/FactomProject/FactomCode/commit/0049624b6f2db1b68e37c55aa12c7f9f904b807b
