### ISSUE TITLE
Find out whether BTCD configurations come from factomd.conf

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#454]

**Comment by m21** [comment]
Of primary interest here are debug levels for the BTCD component.
Can they be set up in the .conf file (same way they can be done via command line).
Secondary - check out port # & peer address.

**Comment by PaulSnow** [comment]
Where are we on this?

**Comment by m21** [comment]
The "processor" side uses the factomd.conf file, but does not see the command like options.
The "btcd" side is the complete opposite: sees the command line options, but not the .conf file.
Question: what is desired and when?

**Comment by m21** [comment]
We decided that the config file will be in charge.
