### ISSUE TITLE
develop process to turn genesis csv file into transaction list

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#457]
See #182 as well.

**Comment by carryforward** [comment]
after https://github.com/FactomProject/WorkItems/issues/182

**Comment by carryforward** [comment]
https://github.com/FactomProject/genesisblockmaker is where the genesis block lives.  there are more updates still to come from koinify corrections and adding the early contributors to this list, but it will be in this same format.  

The genesis block will have RCDs, which are like a P2SH address with these ed25519 keys being part of a 1-of-1 in the script.  the RCDs will be a hash of the pubkey plus some extra data.

**Comment by ThePiachu** [comment]
Sounds good. So I'm guessing I should create a package that reads the CSV, parses it into some transaction format and possibly saves that as a JSON-encoded file as well?

**Comment by ThePiachu** [comment]
Is there any specific transaction format the records should be converted to, or is the data structure still to be decided?

**Comment by carryforward** [comment]
I'll do some audits after #633
