### ISSUE TITLE
Compilation error in factoid/fctwallet/WalletApp/transaction.go

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#465]
Not sure why but it only shows up on my eclipse:

# github.com/FactomProject/factoid/fctwallet/WalletApp
./transactions.go:350: invalid operation: ! string
./transactions.go:354: cannot assign bool to valid (type string) in multiple assignment
./transactions.go:358: invalid operation: ! string
./transactions.go:422: invalid operation: ! string

**Comment by PaulSnow** [comment]
Are you still having this problem?

**Comment by PaulSnow** [comment]
Are you still having this problem?
