### ISSUE TITLE
commit-chain crashing bug

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#467]
here is a screenshot reported by a Community Tester over the weekend.

![crash1](https://cloud.githubusercontent.com/assets/7833030/8530090/78ca4164-23e4-11e5-9cf4-4c35e9c0fb21.jpg)

**Comment by michaelbeam** [comment]
chain-commits, finding eblock, ...?

**Comment by PaulSnow** [comment]
Not reproducible.
