### ISSUE TITLE
API: FACTOID WALLET ADDRESS NAME starting with a "/" character is incorrectly accepted as a valid name

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#470]
Trying to create a FACTOID WALLET ADDRESS NAME starting with a "/" character (/F02) results in a FACTOID WALLET ADDRESS NAME being generated despite starting with an invalid character.

However, the resulting name is not "/F02", but instead "F02".

**Comment by PaulSnow** [comment]
the slash is interpreted by bash, so there isn't anything to do about that character.

Updated and fixed error reporting on invalid names.
