### ISSUE TITLE
import Koinify words to wallet

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#473]
factoid app should be able to import the 12 words written down from the koinify website to spend the factoids.

**Comment by carryforward** [comment]
this might be a good place to start

**Comment by carryforward** [comment]
this is the python code to turn words into a private key: https://github.com/FactomProject/FactomDocs/blob/master/token_sale/words_to_factoid_purchase.py

Here are my test vectors to make private keys from the seed:
https://github.com/FactomProject/factoidGenesisManager/blob/master/goTestVectors/createVectors.go

**Comment by carryforward** [comment]
test vectors can be generated with https://github.com/FactomProject/factoidGenesisManager

since the 12 words themselves have checksums builtin, some word groups that pass the checksum are here https://github.com/tyler-smith/go-bip39/blob/master/bip39_test.go#L90  all these will produce valid private keys.

**Comment by carryforward** [comment]
assign this back to me when you are done.  I'll do some testing too.

**Comment by ThePiachu** [comment]
Added the functionality to import addresses by private key, human readable private key and mnemonic:

https://github.com/FactomProject/fctwallet/tree/PrivateKeyImport
https://github.com/FactomProject/factoid/tree/PrivateKeyImport
https://github.com/FactomProject/factom-cli/tree/PrivateKeyImport

Probably the documentation needs to be updated.

NOTE: importing the same private key more than once causes the wallet to generate random addresses to avoid duplication.

**Comment by ThePiachu** [comment]
Also https://github.com/FactomProject/factom/tree/PrivateKeyImport
