### ISSUE TITLE
Admin Block header updated

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#474]
https://github.com/FactomProject/FactomDocs/blob/master/factomDataStructureDetails.md#administrative-block

Chain head commitment replaced with Header Expansion Area.
Sha3 replaced with SHA512[:256]
KeyMR replaced with serial hash

**Comment by ThePiachu** [comment]
Added HeaderExpansionArea and HeaderExpansionSize, replaced SHA with SHA512[:256] - https://github.com/FactomProject/FactomCode/commit/d93f31eb03d8118f4b49a066e2f00590fd19a5a6
