### ISSUE TITLE
factom-cli error handling needs clarity

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#484]
for example `factom-cli get dblock baddeadf00dbaddeadf00dbaddeadf00dbaddeadf00dbaddeadf00dbaddead11`

returns `unexpected end of JSON input: `

this is not a helpful error to describe when something doesn't exist.

**Comment by michaelbeam** [comment]
I wrote more meaningful errors for all of the api calls that do a db lookup
