### ISSUE TITLE
API: transaction fee of complicated transaction showing the same as tranaction fee of simple transaction

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#485]
~$ factom-cli getfee
Fee: 0.00666667
~$ factom-cli newtransaction transaction207
Success building a transaction
~$ factom-cli addinput transaction207 factoid-wallet-address-name01 100
Success adding Input
~$ factom-cli addinput transaction207 factoid-wallet-address-name01 300
Success adding Input
~$ factom-cli addinput transaction207 factoid-wallet-address-name02 200
Success adding Input
~$ factom-cli addoutput transaction207 factoid-wallet-address-name01 4.44444444
Success adding output
~$ factom-cli addoutput transaction207 factoid-wallet-address-name01 5.55555555
Success adding output
~$ factom-cli addoutput transaction207 factoid-wallet-address-name02 6.66666666
Success adding output
~$ factom-cli addecoutput transaction207 EC2WfSMMRUdkpNRhxUgp9wpSgtpPZU6i8tV1PVu2DvmKsFfhLYwo 7
Success adding Entry Credit Output
~$ factom-cli addecoutput transaction207 EC2WfSMMRUdkpNRhxUgp9wpSgtpPZU6i8tV1PVu2DvmKsFfhLYwo 8
Success adding Entry Credit Output
~$ factom-cli addecoutput transaction207 EC2WfSMMRUdkpNRhxUgp9wpSgtpPZU6i8tV1PVu2DvmKsFfhLYwo 9
Success adding Entry Credit Output
~$ factom-cli getfee transaction207
Fee: 0.00666667
~$ factom-cli sign transaction207
Success signing transaction
~$ factom-cli submit transaction207
Successfully submitted the transaction
~$ 
~$ factom-cli getfee
Fee: 0.00666667
~$ factom-cli newtransaction transaction307
Success building a transaction
~$ factom-cli addinput transaction307 factoid-wallet-address-name01 100
Success adding Input
~$ factom-cli addinput transaction307 factoid-wallet-address-name01 300
Success adding Input
~$ factom-cli addinput transaction307 factoid-wallet-address-name02 200
Success adding Input
~$ factom-cli addoutput transaction307 factoid-wallet-address-name01 4.44444444
Success adding output
~$ factom-cli addoutput transaction307 factoid-wallet-address-name01 5.55555555
Success adding output
~$ factom-cli addoutput transaction307 factoid-wallet-address-name02 6.66666666
Success adding output
~$ factom-cli addecoutput transaction307 EC2WfSMMRUdkpNRhxUgp9wpSgtpPZU6i8tV1PVu2DvmKsFfhLYwo 7
Success adding Entry Credit Output
~$ factom-cli addecoutput transaction307 EC2WfSMMRUdkpNRhxUgp9wpSgtpPZU6i8tV1PVu2DvmKsFfhLYwo 8
Success adding Entry Credit Output
~$ factom-cli addecoutput transaction307 EC2WfSMMRUdkpNRhxUgp9wpSgtpPZU6i8tV1PVu2DvmKsFfhLYwo 9
Success adding Entry Credit Output
~$ factom-cli sign transaction307
Success signing transaction
~$ factom-cli getfee transaction307
Fee: 0.00666667
~$ factom-cli submit transaction307
Successfully submitted the transaction
~$ factom-cli getfee
Fee: 0.00666667
~$ factom-cli newtransaction transaction407
Success building a transaction
~$ factom-cli addinput transaction407 factoid-wallet-address-name01 100
Success adding Input
~$ factom-cli addinput transaction407 factoid-wallet-address-name01 300
Success adding Input
~$ factom-cli addinput transaction407 factoid-wallet-address-name02 200
Success adding Input
~$ factom-cli addoutput transaction407 factoid-wallet-address-name01 4.44444444
Success adding output
~$ factom-cli addoutput transaction407 factoid-wallet-address-name01 5.55555555
Success adding output
~$ factom-cli addoutput transaction407 factoid-wallet-address-name02 6.66666666
Success adding output
~$ factom-cli addecoutput transaction407 EC2WfSMMRUdkpNRhxUgp9wpSgtpPZU6i8tV1PVu2DvmKsFfhLYwo 7
Success adding Entry Credit Output
~$ factom-cli addecoutput transaction407 EC2WfSMMRUdkpNRhxUgp9wpSgtpPZU6i8tV1PVu2DvmKsFfhLYwo 8
Success adding Entry Credit Output
~$ factom-cli addecoutput transaction407 EC2WfSMMRUdkpNRhxUgp9wpSgtpPZU6i8tV1PVu2DvmKsFfhLYwo 9
Success adding Entry Credit Output
~$ factom-cli sign transaction407
Success signing transaction
~$ factom-cli submit transaction407
Successfully submitted the transaction
~$ factom-cli getfee transaction407
Fee: 0.00666667
~$

**Comment by PaulSnow** [comment]
This call just gets the cost in factoids for an entry credit.  The idea is that the user can calculate the fee required.  The cost is:

1 entry credit's worth of factoids per 1K transaction size.
1 entry credit's worth of factoids per signature (which is per input currently)
10 entry credit's worth of factoids per output and per ecoutput

So the function is as designed, even if we should expand it to accept a transaction and do the calculation.
