### ISSUE TITLE
factoid unmarshal should do proper bounds checking

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#492]
https://github.com/FactomProject/factoid/blob/master/transaction.go#L449

we might get an evil transaction over the wire which underflows and segfaults.

**Comment by PaulSnow** [comment]
Go doesn't segfault, it panics.  So that isn't so possible.  Added code to catch panics and report errors instead.

Beefed up transaction checks to prevent bad transactions from getting into blocks regardless of where they come from.

Updated state/test to check for lost transaction data.
