### ISSUE TITLE
Create factomd.conf by default if it's not present, or display proper error

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#502]
I recently ran into this problem - if factomd.conf is not present, the code won't run since it doesn't know where to put the database. The error message for this is misleading:

panic: Database was not found, and could not be created.

goroutine 1 [running]:
github.com/FactomProject/factoid/database.(*BoltDB).Init(0xc08200e2a0, 0xc082025d78, 0x3, 0x3)
        C:/GoogleAppEngine/gopath/src/github.com/FactomProject/factoid/database/boltdb.go:108 +0x247
github.com/FactomProject/factoid/state/stateinit.GetDatabase(0x6c04f0, 0x14, 0x0, 0x0)
        C:/GoogleAppEngine/gopath/src/github.com/FactomProject/factoid/state/stateinit/stateinit.go:92 +0x1127
github.com/FactomProject/factoid/state/stateinit.NewFactoidState(0x6c04f0, 0x14, 0x0, 0x0)
        C:/GoogleAppEngine/gopath/src/github.com/FactomProject/factoid/state/stateinit/stateinit.go:35 +0x28f
github.com/FactomProject/FactomCode/common.init()
        C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/common/ftcblock.go:16 +0xd9
command-line-arguments_test.init()

Either the factomd.conf file should be created by default if it's not present, or a proper error indicating that the conf file is not found should be displayed.

**Comment by ThePiachu** [comment]
Also, the error appears to be thrown if the database directory is not present (at least under Windows). It would be nice to create that directory in that case and try again if possible.

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/18/2016

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/18/2016
