### ISSUE TITLE
API: ADDING LARGEST ALLOWABLE INPUT OF 92233720368.54775806 FACTOIDS TO TRANSACTION

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#505]
IT IS ACCEPTED AS A TRANSACTION, BUT BALANCE IS NOT UPDATED. HOWEVER AS THE AMOUNT IS GREATER THAN THE AVAILABLE BALANCE, THE TRANSACTION SHOULD NOT BE ACCEPTED.

echo 2.9.7 ADD LARGEST ALLOWABLE INPUT OF 92233720368.54775806 FACTOIDS TO TRANSACTION        
Balance of  factoid-wallet-address-name03  =  1999.98666666
factom-cli newtransaction transaction14
Success building a transaction
factom-cli addinput transaction14 factoid-wallet-address-name03 92233720368.54775806
Success adding Input
factom-cli sign transaction14
Success signing transaction
factom-cli submit transaction14
Successfully submitted the transaction
factom-cli balance fct factoid-wallet-address-name03
Balance of  factoid-wallet-address-name03  =  1999.98666666

**Comment by PaulSnow** [comment]
Fixed in blockchanges branch.

**Comment by drobertbaker** [comment]
OK
