### ISSUE TITLE
dblock: timestamp not set

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#509]
this is intentional, but we shouldn't forget when we launch.  

@carryforward needs to recheck when we have a timestamp placed.

**Comment by JackXLu** [comment]
The time stamp only shows up with 10 min blocks:

Test Blocks===========================================================================
2015-07-14T14:45:05-05:00 [INFO] FTMD: Database started from: /tmp/ldb9
--- PASS: TestBlocks (0.00 seconds)
	blocks_test.go:22: dblk=(*common.DirectoryBlock)(0xc2103fa820)({
		 Header: (*common.DBlockHeader)(0xc2100fd870)({
		  Version: (uint8) 0,
		  NetworkID: (uint32) 4203931042,
		  BodyMR: (*common.Hash)(0xc2103fc0a0)(4094fac6a6e30e9ddf9cd5541ba7421ffccc5432cde1582ceb40a45426bf9907),
		  PrevKeyMR: (*common.Hash)(0xc2103fc0c0)(3a6aca0347aa04eac1f81e3995e1b37db00c47021db73ffcfd459fa27f1b903e),
		  PrevFullHash: (*common.Hash)(0xc2103fc0e0)(ffd28a99e953ded71b47b53b6bcc9d6ec9d41c111e48ffa8854e033193a34148),
		  Timestamp: (uint32) 23948370,
		  DBHeight: (uint32) 1,
		  BlockCount: (uint32) 3
		 }),

**Comment by PaulSnow** [comment]
Fixed
