### ISSUE TITLE
API: update ebentry timestamps in eblock return to reflect minute changes in the 10 min block

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#511]

**Comment by drobertbaker** [comment]
07/15/2015 
Entry Time Stamp now is still 0
ENTRY BLOCK  Time Stamp now seems to be in minutes, e.g. 23949627
DIRECTORY BLOCK looks correct, e.g. 1436977260

**Comment by michaelbeam** [comment]
x entry block updated.
! entry timestamp pending

**Comment by michaelbeam** [comment]
EBEntry timestamp currently set to EBlock timestamp

**Comment by michaelbeam** [comment]
EBEntry timestamps currently same as timestamp in Header
