### ISSUE TITLE
factoid coinbase millitimestamp

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#519]
the factoid coinbase transaction shows a time which does not fall on a 10 minute boundary.  coinbase transaction should have milllitimestamp of the block time, so that servers can coordinate.

**Comment by PaulSnow** [comment]
To be decided, but as we discussed, the server adding the coinbase transaction SHOULD broadcast the transaction to the network.  At which point, the timestamp can be an indication of delays in the system in processing Factoid transactions, and this should not be changed.
