### ISSUE TITLE
factoid genesis block exchange rate

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#520]
exchange rate is 1 million in genesis block and 666,667 in subsequent blocks

**Comment by PaulSnow** [comment]
What is the problem here?

**Comment by carryforward** [comment]
The problem is when future users examine the factoid/EC exchange rate, it will not match.

This is still a problem even after https://github.com/FactomProject/WorkItems/issues/588

block 0: 00 00 00 00 00 0F 42 40 

Block 1: 00 00 00 00 00 0A 2C 2A

**Comment by PaulSnow** [comment]
Fixed

**Comment by carryforward** [comment]
hmm, the config file now shows the exchange rate as 00666600 giving block 1+ an exchange value of 00 00 00 00 00 0A 2B E8

in the genesis block, it is 666,667, giving an exchange value of 00 00 00 00 00 0A 2C 2A

Should we stick with one?

**Comment by PaulSnow** [comment]
Still fixed.
