### ISSUE TITLE
Client with high CPU usage and 0 peerCount

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#524]
100%+ cpu usage and the following msg is logged 163750 times between:
17:36:27 2015-07-15 [INF] SRVR: nconnected= 0 (peerCount)
18:36:28 2015-07-15 [INF] SRVR: nconnected= 0 (peerCount)

**Comment by JackXLu** [comment]
It could be just specific to my environment: 1) run factomd inside a VM 2) disconnect WIFI outside of VM

Pls close this one if it doesn't happen to u. Thanks!

**Comment by JackXLu** [comment]
It can be easily reproduced by running factomd without internet connection

**Comment by PaulSnow** [comment]
Duplicate #524
