### ISSUE TITLE
Remove the trace code in process package

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#527]

**Comment by JackXLu** [comment]
Could you please scan and find out whether we have more trace statement in the code as well? I found one in process package yesterday. Thanks!

**Comment by ThePiachu** [comment]
Trace statements found in packages:

- btcd (a lot)
- btcd/wire
- btcutil (a lot)
- btcutil/hdkeychain
- FactomCode/Factoid
- FactomCode/process
- FactomCode/wallet

Will proceed to remove the trace code from FactomCode/process . Let me know if I should remove it from other FactomCode packages.

**Comment by JackXLu** [comment]
I'd suggest u comment out the ones in btcd related packages just in case M.Y needs them. You can remove the ones under FactomCode. Thanks!

**Comment by ThePiachu** [comment]
Okay, commented out everything but one or two occurrences in init().
