### ISSUE TITLE
Error in .all.sh script 

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#539]
+================+
|     btcd       |
+================+

# github.com/FactomProject/btcutil
btcutil/address.go:14: imported and not used: "github.com/FactomProject/btcd/btcec" as __emptyarchive__
btcutil/address.go:19: imported and not used: "github.com/davecgh/go-spew/spew"
btcutil/address_unused.go:14: imported and not used: "github.com/FactomProject/btcd/btcec" as __emptyarchive__
btcutil/address_unused.go:19: imported and not used: "github.com/davecgh/go-spew/spew"
btcutil/address_unused.go:112: undefined: btcec
btcutil/wif.go:11: imported and not used: "github.com/FactomProject/btcd/btcec" as __emptyarchive__
FAIL	github.com/FactomProject/btcd [build failed]
?   	github.com/FactomProject/btcd/addrmgr	[no test files]
?   	github.com/FactomProject/btcd/blockchain	[no test files]

**Comment by JackXLu** [comment]
This is the issue that came up during our standup today

**Comment by m21** [comment]
How did you run the shell script?
How can I reproduce?

**Comment by PaulSnow** [comment]
Right now this bug is limited to displaying the following when running the all.sh script:
```
+================+
|     btcd       |
+================+

go build github.com/FactomProject/btcd/btcec: no buildable Go source files in 
FAIL	github.com/FactomProject/btcd [build failed]
?   	github.com/FactomProject/btcd/addrmgr	[no test files]
?   	github.com/FactomProject/btcd/blockchain	[no test files]
ok  	github.com/FactomProject/btcd/btcjson	0.166s
?   	github.com/FactomProject/btcd/btcjson/btcws	[no test files]
?   	github.com/FactomProject/btcd/btcjson/v2/btcjson	[no test files]
?   	github.com/FactomProject/btcd/chaincfg	[no test files]
?   	github.com/FactomProject/btcd/cmd/addblock	[no test files]
?   	github.com/FactomProject/btcd/cmd/dropafter	[no test files]
?   	github.com/FactomProject/btcd/cmd/fctctl	[no test files]
?   	github.com/FactomProject/btcd/cmd/findcheckpoint	[no test files]
?   	github.com/FactomProject/btcd/cmd/gencerts	[no test files]
?   	github.com/FactomProject/btcd/limits	[no test files]
?   	github.com/FactomProject/btcd/wire	[no test files]
```

I have looked at how to get rid of that last FAIL, but haven't had any luck.

**Comment by m21** [comment]
How exactly do you invoke the script?

**Comment by m21** [comment]
This fixes issue I see: https://github.com/FactomProject/btcd/commit/52d624e8f5c577807c0cd2f9f677ee8c4293bc70

**Comment by m21** [comment]
Make sure you delete obsolete repositories from your FactomProject on your PC, these are the only ones I have:
```
btcd
btclog
dynrsrc
ed25519
factoid
factom
factom-cli
FactomCode
fastsha256
gocoding
go-flags
goleveldb
go-socks
seelog
snappy-go
websocket
```
