### ISSUE TITLE
Limit /factoid/state/test to a reasonable time for all.sh

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#540]
I just tried running the unit test from /factoid/state/test . It looks like it takes 4-5 seconds per block and expects to run for 5000 blocks, which means it's a 5-7 hour test. This is all well and good for a stress test, but not for a unit test that is supposed to be ran through all.sh whenever one updates to the newest code. Please make the execution time reasonable for that script at least - perhaps make it a short test instead?

**Comment by ThePiachu** [comment]
I guess this issue has been addressed in https://github.com/FactomProject/FactomCode/commit/771e99a977bdacc3775b556ae9dc47a48c1f9296 , can still be a problem when first updating into the code as expected.

**Comment by PaulSnow** [comment]
Well, the test does check the short flag.   I could move the stress test into its own application, but that is annoying in that it isn't easily removed from everything else.  (unit tests are auto culled...)

I think I'll close this until someone can come up with an idea that is better than go test.
