### ISSUE TITLE
API: TRY TO CREATE FACTOID WALLET ADDRESS NAME ENDING WITH %

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#544]
factom-cli generateaddress fct "'F02%'"
yields
parse http://localhost:8089/v1/factoid-generate-address/'F02%': invalid URL escape "%'"

**Comment by PaulSnow** [comment]
Well, it is an annoying error, but it is being caught by the bash shell....  

Added code to catch it right in the CLI, but it doesn't get a chance.
