### ISSUE TITLE
check dates on the clients when downloading blocks from the network

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#545]

**Comment by PaulSnow** [comment]
We will have to do this as we build the consensus algorithm.   Without a reasonable action to take, a full node on the network will just have to accept the blocks.

Other federated servers can serverfault a server that doesn't create valid blocks.  Audit servers can cry foul.  And full nodes should be warned.

I think we could go ahead and produce the warning...  But it is more than just dates, but also valid transactions, and other accounting.

**Comment by PaulSnow** [comment]
Doen
