### ISSUE TITLE
All.sh should handle repositories not being present on disk

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#546]
It looks like all.sh currently presumes all repositories are present on disk before proceeding to synchronize with them. This can cause some errors:

********************************************************
*     Compiling fctwallet, the cli, and factomd
********************************************************

Compiling:  factoid/fctwallet
C:\GoogleAppEngine\gopath\src\github.com\FactomProject\FactomCode\all.sh: line 94: cd: factom-cli: No such file or directory
Compiling:  factom-cli
can't load package: package github.com/FactomProject: no buildable Go source files in C:\GoogleAppEngine\gopath\src\github.com\FactomProject
Compiling:  FactomCode/factomd

*******************************************************
*     Running Unit Tests    Now safe to Ctrl+C
*******************************************************

It would be nice if the script checked whether the repositories are present on disk before trying to access them.

**Comment by PaulSnow** [comment]
The trhee things that all.sh attempts to compile are factom-cli, fctwallet,
and factomd.   I am not sure how reasonable it is to assume any of these
repositories might be missing.

Paul Snow
Texas Bitcoin Conference
Factom.org
phone: (512) 627-8841
skype: paulsnx2

**Comment by ThePiachu** [comment]
They were missing for me for some reason.

**Comment by PaulSnow** [comment]
Then.... Doesn't the fact that all.sh failed help you realize you need to get more stuff?

Can we agree that we have to have some basic repositories, and that all.sh failing here tells you that?  If so, I think we can close this.

**Comment by ThePiachu** [comment]
If it would be easy for all.sh to fetch the missing repositories, it might be useful to do so for convenience. If it is a hassle, sure, we can close it.
