### ISSUE TITLE
create web console for factomd

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#547]
connect to a local webpage to give you a status update about what factom is doing.

**Comment by PaulSnow** [comment]
First cut done and checked into development.  

You run factomd.  Then go to http://localhost:8090/controlpanel

You can just keep the page up, and it updates as you bring up and down factomd as you work.

Need to figure out how to publish from the server, so we can see the status of the server.

**Comment by PaulSnow** [comment]
Removed the worst of the curses.  There are still more maybe, but I don't think so.
