### ISSUE TITLE
for milestone 1 launch, reintroduce panic about genesis hash

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#549]
Since directory block and factoid genesis timestamps are now changed every time the server starts, we should not panic during development.  

We have turned it from a panic to a warning. 
https://github.com/FactomProject/FactomCode/commit/257f6220945ed8346853558043f78033386ba402

When we get to milestone 1, we should reintroduce the panic.

**Comment by JackXLu** [comment]
done
