### ISSUE TITLE
API: Input greater than balance being accepted

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#550]
Balance of  factoid-wallet-address-name01  =  2399.0
~$ factom-cli newtransaction transaction108
Success building a transaction
~$ factom-cli addinput transaction108 factoid-wallet-address-name01 21000
Success adding Input
~$ factom-cli balance fct factoid-wallet-address-name01
Balance of  factoid-wallet-address-name01  =  2399.0

**Comment by PaulSnow** [comment]
This isn't a bug.  You are allowed to construct any transaction you like.  For all the software knows, someone else is just about to drop 22000 factoids into factoid-wallet-address-name01 any minute now.

You can even sign the transaction.

But if you submit it, and nobody came through with the needed factoids to cover the 21000, then the transaction will be rejected.
