### ISSUE TITLE
Double check the comments with ???

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#551]
examples:

	INFO_CURRENT_HEIGHT // info message to the wire-side to indicate the current known block height; a duplicate of FORCE_FACTOID_VALIDATION (???)

	BTCTxHash *Hash // use string or *btcwire.ShaHash ???

	//BTCBlockHash *Hash // use string or *btcwire.ShaHash ???

**Comment by JackXLu** [comment]
Please assign it to MY if it's not yours

**Comment by SirHalsell** [comment]
removed
