### ISSUE TITLE
API: very large transaction amounts are rejected as negative amounts, rather than too large amounts

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#555]
~$ factom-cli newtransaction transaction115
Success building a transaction
~$ factom-cli addinput transaction115 factoid-wallet-address-name03 92233720369
Negative amounts are not allowed

**Comment by PaulSnow** [comment]
92233720369 creates 9223372036900000000 in hex (remember it is fixed point).

This number is 8000 0000 02B2 1100 (spaces added) in hex, which is negative, or

**Comment by drobertbaker** [comment]
Please change message to be non-specific, e.g. "Value outside of acceptable range"

**Comment by PaulSnow** [comment]
by design.

**Comment by drobertbaker** [comment]
Please change message to be non-specific, e.g. "Value outside of acceptable range" rather than give the "Negative amounts are not allowed" message which is incorrect in this situation.

**Comment by PaulSnow** [comment]
Okay, done.

**Comment by drobertbaker** [comment]
OK
