### ISSUE TITLE
EBlock not found

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#557]
After fixing issue https://github.com/FactomProject/WorkItems/issues/556 , now calling factom.GetEBlock returns an error of "EBlock not found", despite the EBlock being searched for is fetched straight from the current DBlock.

**Comment by JackXLu** [comment]
If this is not working, it needs to fixed for MS1. can u check it?

**Comment by michaelbeam** [comment]
Yes. I'll take a look.

On Fri, Jul 24, 2015 at 1:10 PM, JackXLu <notifications@github.com> wrote:

> If this is not working, it needs to fixed for MS1. can u check it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FactomProject/WorkItems/issues/557#issuecomment-124604058>
> .
>



-- 

[image: Factom] <http://vanbex.com/>

Michael Beam
Core Developermichael@factom.org

Factomhttp://factom.org <http://vanbex.com/>

**Comment by carryforward** [comment]
000f/000a/000c blocks are not entry blocks
