### ISSUE TITLE
Server should not sync up from other peers

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#560]
I thought we had this code in place. can u double check?

**Comment by PaulSnow** [comment]
This is the fact that blocks can flow up to the server from the clients.  If this doesn't break the server, then I think we can ignore.  But if the same blocks can be pushed to the server over and over, then we need to stop that.  Keep the blocks in the inventory or something.

The question is if there is a risk.  No risk, we can ignore.  If it breaks our server, we have to fix.

**Comment by m21** [comment]
This sounds like a consensus issue - which chain is the main one from processor point-of-view.

**Comment by m21** [comment]
Signature verification issue.

**Comment by m21** [comment]
On the btcd side please disable sends or receives of certain messages based on "ClientOnly bool" provided from the processor side. That should stop any looping scenarios.
Caution: MS1 only!

**Comment by JackXLu** [comment]
this might be related to the looping issue
