### ISSUE TITLE
We appear to have only 9 periods, not 10 per block and per the spec.

### ISSUE THREAD

**Issue by PaulSnow** [FactomProject/WorkItems#565]
Brian is holding out that the observation may be flawed, but I am only seeing 9, 5 second intervals (for a total of 45 seconds) per block.  We should have one more, bringing us to 54 seconds and 10 intervals.

Please look at this.

**Comment by JackXLu** [comment]
It's the time rounding for the 1 minute block. works fine for 10 min blocks though
