### ISSUE TITLE
API: asking for balance of non-existent factoid wallet address starting with $ causes panic

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#566]
~$ factom-cli balance fct $murh
panic: runtime error: index out of range

goroutine 1 [running]:
main.balance(0xc20800a020, 0x1, 0x1, 0x0, 0x0)
	/home/factom/go/src/github.com/FactomProject/factom-cli/balance.go:31 +0x276
main.main()
	/home/factom/go/src/github.com/FactomProject/factom-cli/main.go:57 +0x6e6

**Comment by PaulSnow** [comment]
$anything    is Bash to look up a value of a variable.   In this case, $murh was undefined, so absolutely nothing was passed along to the factom-cli.   You get the same error just typing:

factom-cli balance fct

Fixed
