### ISSUE TITLE
Client is connected and disconnected in a loop

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#568]
Need to find out whether we can reproduce it

**Comment by JackXLu** [comment]
Can u take a look at the log files on server and figure out what was going on yesterday?
We can't find the log file on the client side. Thanks!

/home/factom/.factom/logs/072315

**Comment by m21** [comment]
Nothing useful in the logs. But continue with @carryforward since he can reproduce it.

**Comment by JackXLu** [comment]
It cannot be reproduced any more
