### ISSUE TITLE
Make sure unmarshalling is not greedy

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#572]
Some of the unmarshalling functions, like ecblock.go's (b *ECBlockBody) UnmarshalBinaryData are greedy - they unmarshal data until they run out of input. It might be better for them to unmarshal only as much data as was actually stored, based on some counts / sizes from headers or other places. This way if we have more than one piece of data to unmarshal we can safely start calling UnmarshalBinaryData and know we would get a proper result.

**Comment by michaelbeam** [comment]
fixed for eblock and ecblock unmarshaling
