### ISSUE TITLE
During startup, DirBlockInfo is unmarshalled with incomplete data

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#573]
During initialization, we seem to be unmarshalling some incomplete data:

(b *DirBlockInfo) UnmarshalBinaryData - 1A5C37458AA5F8DB9C23F7BD7D8E16D48136E06923E84F426DFFC22E9C72A350000000000000000000000000000000000000000000000000000000000000000000000000C21CE651A016DDDFE8575EEBDA6DAAD2D71D80D6C230FCDF5CF229619C69B77F00

1A5C37458AA5F8DB9C23F7BD7D8E16D48136E06923E84F426DFFC22E9C72A350 - DBHash
0000000000000000000000000000000000000000000000000000000000000000 - BTCTxHash
00000000 - BTCTxOffset
C21CE651 - BTCBlockHeight
A016DDDFE8575EEBDA6DAAD2D71D80D6C230FCDF5CF229619C69B77F00 - DBMerkleRoot? (too short), and there is nothing left for BTCConfirmed

stack:
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/common/directoryBlock.go:654 (0x451467)
        (*DirBlockInfo).UnmarshalBinaryData: debug.PrintStack()
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/database/ldb/dblock.go:436 (0x4653e7)
        (*LevelDb).FetchAllUnconfirmedDirBlockInfo: _, err := dBInfo.UnmarshalBinaryData(iter.Value())
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/anchor/anchor.go:327 (0x659a9e)
        InitAnchor: dirBlockInfoMap, err = db.FetchAllUnconfirmedDirBlockInfo()
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:131 (0x472e88)
        initProcessor: anchor.InitAnchor(db)
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:178 (0x47342f)
        Start_Processor: initProcessor()
c:/go/src/runtime/asm_amd64.s:2232 (0x42b631)
        goexit:

This error if left unchecked will later manifest itself as:

panic: assignment to entry in nil map

goroutine 18 [running]:
github.com/FactomProject/FactomCode/anchor.UpdateDirBlockInfoMap(0xc0826571d0)
        C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/anchor/anchor.go:509 +0x1f1
github.com/FactomProject/FactomCode/process.newDirectoryBlock(0xc0821380c0, 0xc082d3d858)
        C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:1053 +0x3ae
github.com/FactomProject/FactomCode/process.buildBlocks(0x0, 0x0)
        C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:867 +0x5fa
github.com/FactomProject/FactomCode/process.serveMsgRequest(0x319bc50, 0xc082078b30, 0x0, 0x0)
        C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:289 +0x2da0
github.com/FactomProject/FactomCode/process.Start_Processor(0x3185630, 0xc08200f860, 0xc0820fe780, 0xc0820fe7e0, 0xc0820fe840, 0xc0820fe8a0)
        C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:204 +0x39c
created by main.factomdMain
        C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/factomd/factomd.go:69 +0x97

Temporary workaround was put in place for now:

https://github.com/FactomProject/FactomCode/commit/2e77f23433830aeb0a5c1bdb18c9ee7ef50034df#diff-01e1981f7297910ddb7c605da26e09b2R438

**Comment by SirHalsell** [comment]
it's verified. the Temporary workaround is the RIGHT FIX :)

**Comment by ThePiachu** [comment]
Sorry, but if you are passing DirBlockInfo to be unmarshalled and that data is not sufficient, something is wrong. Either you are passing some wrong data to be unmarshalled, you are missing some data, or the unmarshalling function is wrong. A function returning an error is not a proper execution path, since it may mask a future problem we might have.

**Comment by SirHalsell** [comment]
Piotr is right. the current fix is only good for Anchor but the unmarshal error still persists. We need to look at the binary data in db to see what's missing.  reopen this and assign it to Jack

**Comment by SirHalsell** [comment]
To reproduce it
1. roll back Piotr's change
2. clean run factomd server and allow a few blocks to be created. 
3. kill factomd
4. restart factomd
5. find unmarshall error in log.

**Comment by SirHalsell** [comment]
the impact of this bug, if unfixed, is: there could potentially cause one dir block un-anchored. 

it's definitely not critical but should be fixed.

**Comment by JackXLu** [comment]
It seems that the issue has been fixed by:
https://github.com/FactomProject/FactomCode/commit/9c693c4a28df9fc4d5c109906a05d4123ca64d3c

Pls double check
