### ISSUE TITLE
addrmgr uses lots of CPU

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#577]
Profiler shows this:

![unnamed](https://cloud.githubusercontent.com/assets/7833030/8919068/2f072ec6-3482-11e5-8bac-f372b3d50392.png)

it looks like it is busy making random numbers.

**Comment by PaulSnow** [comment]
Likely fixed.

**Comment by PaulSnow** [comment]
Okay, the bug is like this.  Disconnect from the network.  THEN run as a Full Node (as a client).  Pegs the processor at 100%.

The code I added did no good.  What needs to happen is have a delay in the loop looking for connections.  Added a sleep.  This calms the processor down significantly.
