### ISSUE TITLE
API: using an address key rather than an address name in a transaction causes a "Key is too long" error

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#578]
e.g.
factom-cli addecoutput transaction06 EC3QeegGid2C7gbpbeYoseX2gSkiYsSamsX46RXqY6v8ewfwR7hK 6
yields:
Key is too long.  Keys must be less than 32 characters

**Comment by PaulSnow** [comment]
Fixed

**Comment by drobertbaker** [comment]
Yay!

**Comment by drobertbaker** [comment]
This is back! It was just reported by a community tester.

**Comment by drobertbaker** [comment]
False alarm. User was using outdated version of the code.
