### ISSUE TITLE
client stops downloading blocks

### ISSUE THREAD

**Issue by michaelbeam** [FactomProject/WorkItems#580]
the client will stop downloading blocks when it encounters an error with its local store.

I was able to use this script to produce the error. Increase the number in the loop to extend the test. It will currently run for 10 min at 1 entry / sec

	#!/bin/bash
	
	rand=$(openssl rand -base64 8)
	chainid=$(echo testing | factom-cli mkchain -e $rand -e test app | awk -F': ' '{print $2}')
	
	echo ChainID: $chainid >>testchainid
	
	for ((i=0; i < 600; i++)); do
	        echo $i | factom-cli put -c $chainid -e $i app &
	        sleep 1
	done

**Comment by michaelbeam** [comment]
In my test the server is creating 1 min blocks

**Comment by PaulSnow** [comment]
Isn't this fixed?
