### ISSUE TITLE
factoid and entry credit balances are out of sync

### ISSUE THREAD

**Issue by michaelbeam** [FactomProject/WorkItems#581]
After creating a few hundred entries on the server I am seeing a difference in ec and fct balances between the client and server. They were in sync before the test, and it appears the ec balances have increased on the client side.

Client
---
	ubuntu@ip-172-31-25-86:~$ factom-cli getaddresses
	
	  Factoid Addresses
	
	    michael    FA2BcC66Ljzd6EymroHw94P7y86vobLHjQpxanefi9AkD5Yxk9jh          5949.0
	
	  Entry Credit Addresses
	
	        app    EC2x8oEKJSjsciQKAwd9TEfXJTs6BEX2da6Db3KKWMqC3DvbRQ9k        3000170
	
	ubuntu@ip-172-31-25-86:~$ ls /tmp/store/seed/*0c
	store.000000000.block  store.000000018.block  store.000000036.block  store.000000054.block  store.000000072.block  store.000000090.block  store.000000108.block
	store.000000001.block  store.000000019.block  store.000000037.block  store.000000055.block  store.000000073.block  store.000000091.block  store.000000109.block
	store.000000002.block  store.000000020.block  store.000000038.block  store.000000056.block  store.000000074.block  store.000000092.block  store.000000110.block
	store.000000003.block  store.000000021.block  store.000000039.block  store.000000057.block  store.000000075.block  store.000000093.block  store.000000111.block
	store.000000004.block  store.000000022.block  store.000000040.block  store.000000058.block  store.000000076.block  store.000000094.block  store.000000112.block
	store.000000005.block  store.000000023.block  store.000000041.block  store.000000059.block  store.000000077.block  store.000000095.block  store.000000113.block
	store.000000006.block  store.000000024.block  store.000000042.block  store.000000060.block  store.000000078.block  store.000000096.block  store.000000114.block
	store.000000007.block  store.000000025.block  store.000000043.block  store.000000061.block  store.000000079.block  store.000000097.block  store.000000115.block
	store.000000008.block  store.000000026.block  store.000000044.block  store.000000062.block  store.000000080.block  store.000000098.block  store.000000116.block
	store.000000009.block  store.000000027.block  store.000000045.block  store.000000063.block  store.000000081.block  store.000000099.block  store.000000117.block
	store.000000010.block  store.000000028.block  store.000000046.block  store.000000064.block  store.000000082.block  store.000000100.block  store.000000118.block
	store.000000011.block  store.000000029.block  store.000000047.block  store.000000065.block  store.000000083.block  store.000000101.block  store.000000119.block
	store.000000012.block  store.000000030.block  store.000000048.block  store.000000066.block  store.000000084.block  store.000000102.block  store.000000120.block
	store.000000013.block  store.000000031.block  store.000000049.block  store.000000067.block  store.000000085.block  store.000000103.block
	store.000000014.block  store.000000032.block  store.000000050.block  store.000000068.block  store.000000086.block  store.000000104.block
	store.000000015.block  store.000000033.block  store.000000051.block  store.000000069.block  store.000000087.block  store.000000105.block
	store.000000016.block  store.000000034.block  store.000000052.block  store.000000070.block  store.000000088.block  store.000000106.block
	store.000000017.block  store.000000035.block  store.000000053.block  store.000000071.block  store.000000089.block  store.000000107.block

Server
---
	factom@ip-172-31-2-25:~$ factom-cli getaddresses
	
	  Factoid Addresses
	
	    michael    FA2BcC66Ljzd6EymroHw94P7y86vobLHjQpxanefi9AkD5Yxk9jh          5999.0
	
	  Entry Credit Addresses
	
	        app    EC2x8oEKJSjsciQKAwd9TEfXJTs6BEX2da6Db3KKWMqC3DvbRQ9k        3000008

	factom@ip-172-31-2-25:~$ ls .factom/data/export/*0c
	store.000000000.block  store.000000018.block  store.000000036.block  store.000000054.block  store.000000072.block  store.000000090.block  store.000000108.block
	store.000000001.block  store.000000019.block  store.000000037.block  store.000000055.block  store.000000073.block  store.000000091.block  store.000000109.block
	store.000000002.block  store.000000020.block  store.000000038.block  store.000000056.block  store.000000074.block  store.000000092.block  store.000000110.block
	store.000000003.block  store.000000021.block  store.000000039.block  store.000000057.block  store.000000075.block  store.000000093.block  store.000000111.block
	store.000000004.block  store.000000022.block  store.000000040.block  store.000000058.block  store.000000076.block  store.000000094.block  store.000000112.block
	store.000000005.block  store.000000023.block  store.000000041.block  store.000000059.block  store.000000077.block  store.000000095.block  store.000000113.block
	store.000000006.block  store.000000024.block  store.000000042.block  store.000000060.block  store.000000078.block  store.000000096.block  store.000000114.block
	store.000000007.block  store.000000025.block  store.000000043.block  store.000000061.block  store.000000079.block  store.000000097.block  store.000000115.block
	store.000000008.block  store.000000026.block  store.000000044.block  store.000000062.block  store.000000080.block  store.000000098.block  store.000000116.block
	store.000000009.block  store.000000027.block  store.000000045.block  store.000000063.block  store.000000081.block  store.000000099.block  store.000000117.block
	store.000000010.block  store.000000028.block  store.000000046.block  store.000000064.block  store.000000082.block  store.000000100.block  store.000000118.block
	store.000000011.block  store.000000029.block  store.000000047.block  store.000000065.block  store.000000083.block  store.000000101.block  store.000000119.block
	store.000000012.block  store.000000030.block  store.000000048.block  store.000000066.block  store.000000084.block  store.000000102.block  store.000000120.block
	store.000000013.block  store.000000031.block  store.000000049.block  store.000000067.block  store.000000085.block  store.000000103.block
	store.000000014.block  store.000000032.block  store.000000050.block  store.000000068.block  store.000000086.block  store.000000104.block
	store.000000015.block  store.000000033.block  store.000000051.block  store.000000069.block  store.000000087.block  store.000000105.block
	store.000000016.block  store.000000034.block  store.000000052.block  store.000000070.block  store.000000088.block  store.000000106.block
	store.000000017.block  store.000000035.block  store.000000053.block  store.000000071.block  store.000000089.block  store.000000107.block

**Comment by PaulSnow** [comment]
fixed.
