### ISSUE TITLE
API: getfee key command not implemented

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#582]
The getffee command gives only the minimum transaction fee, not the fee for a particular transaction, no matter what transaction is specified.

**Comment by PaulSnow** [comment]
Fixed

**Comment by drobertbaker** [comment]
The response is now:

"Currently, Entry Credits are 0.0 Factoids each"

factom-cli transactions also reports:

"Fee Due: 0.0"

no matter the transaction

It seems fees are deducted correctly, so it seems like incorrect reporting of the correct value.

**Comment by drobertbaker** [comment]
OK
