### ISSUE TITLE
Entry Credit block should have server index number

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#586]
For milestone 1, add an item to every entry credit block.  The first entry should be 00 00.  This indicates that all the following data is acknowledged by the server with "Server Index Number" and its index number is zero.  It should be in all the entry blocks, even the empty ones.

https://github.com/FactomProject/FactomDocs/blob/master/factomDataStructureDetails.md#ecid-bytes

**Comment by michaelbeam** [comment]
I've added the code for the ecblock to handle the number. the processor will still need to set its index number and write the entry to the ecblock
