### ISSUE TITLE
RCD address hashes the incorrect data

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#592]
The RCD hash (address) should be the hash of the version appended with the ed25519 key.

correct: sha256(sha256(Type | Pubkey 0))

The code currently leaves off the Type byte

implemented: sha256(sha256(Pubkey 0))

https://github.com/FactomProject/FactomDocs/blob/master/factomDataStructureDetails.md#redeem-condition-datastructure-rcd

**Comment by PaulSnow** [comment]
Fixed
