### ISSUE TITLE
factoid merkle trees minute markers

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#596]
merkle trees should be built with minute markers being sha(0x00) instead of sha(0000000000000000000000000000000000000000000000000000000000000000)

**Comment by carryforward** [comment]
solution 1:
https://github.com/FactomProject/factoid/blob/development/constants.go#L38 should be 0x00

solution 2:
https://github.com/FactomProject/factoid/blob/development/block/scblock.go#L106
https://github.com/FactomProject/factoid/blob/development/block/scblock.go#L395

should hash "MARKER"
https://github.com/FactomProject/factoid/blob/development/constants.go#L30

**Comment by PaulSnow** [comment]
Fixed
