### ISSUE TITLE
Discuss how short, reoccurring entries should be presented in Factom Explorer

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#601]
Working on the Explorer, I came across a few different Entries that are very short. These include Entry Credit Block's Server Index Number and Minute Number, as well as Admin Block's Minute Number. As such, it doesn't make much sense for those entries to be first displayed as hashes and have their own page where people can see more information about them. However, since those entries occur in between  bigger entries, it's not always easy to use special display for them.

We should discuss how we want to present those entries in the explorer

**Comment by PaulSnow** [comment]
Let's set up a meeting for this.
