### ISSUE TITLE
API: entries can be put using a factom wallet address at no cost rather than an entry credit address

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#602]
~$ echo 1.1.1.1 CREATE LEGITIMATE FACTOID WALLET ADDRESS CONTAINING 2000 FACTOIDS        
1.1.1.1 CREATE LEGITIMATE FACTOID WALLET ADDRESS CONTAINING 2000 FACTOIDS
~$ factom-cli generateaddress fct dummy0
fct  =  FA2BcC66Ljzd6EymroHw94P7y86vobLHjQpxanefi9AkD5Yxk9jh
~$ factom-cli generateaddress fct dummy1
fct  =  FA2zobvdqxZG8z3XnN1nkbupiyyMkyJCfmNyZzuTPfTW4KZTjtdx
~$ factom-cli generateaddress fct dummy2
fct  =  FA3BXfx7NQ8heEwtygPk8eHo4KPtt8sid5cJg4JuYKKnFGzzxSRZ
~$ factom-cli generateaddress fct dummy3
fct  =  FA2YtWo2gPvoxP1sFWJ6NSD9kkZgGz5TspbcdBc1wm38WDF8FQvW
~$ factom-cli generateaddress fct dummy4
fct  =  FA25pxBr6QrPXf8YjgsjFZupWxgLekG6R8w6qqo7z9n6uLG6z7EM
~$ factom-cli generateaddress fct dummy5
fct  =  FA38HwWN3jRWHYofyC44uKRcUby5PhzWGABmSMFWHXhB5C2FNwjV
~$ factom-cli generateaddress fct dummy6
fct  =  FA3aEtwGrTaJgW85H19MJmCVkvHHkUN22MQrjMBH6CEWGWFLwzjf
~$ factom-cli generateaddress fct dummy7
fct  =  FA2U2GP5R7o4ZRAzxVjZSpYT81bbJityLEri48CDUmGzoF4J275d
~$ factom-cli generateaddress fct dummy8
fct  =  FA3fAakRgNZjsna9s7fjdUMrumnVhUYH1fy9wAFLjB7GFZKygAtD
~$ factom-cli generateaddress fct dummy9
fct  =  FA3krF8rqvXnjU5HyZ2sZsi2J5bacwFG1uTtFedxFa2Pj9i1M4Wt
~$ FACTOIDWALLETADDRESSKEY01=$(factom-cli generateaddress fct factoid-wallet-address-name01 | awk '{print $3}')
~$ echo factoid-wallet-address-name01 = $FACTOIDWALLETADDRESSKEY01
factoid-wallet-address-name01 = FA2P87J1QkuZ1QSi84pMJpMs7yvnV949How2BcQ58AVteXXs2ZwV
~$ factom-cli newtransaction dummytransaction1
Success building a transaction
~$ factom-cli addinput dummytransaction1 dummy1 2001
Success adding Input
~$ factom-cli addoutput dummytransaction1 factoid-wallet-address-name01 2000
Success adding output
~$ factom-cli sign dummytransaction1
Success signing transaction
~$ factom-cli submit dummytransaction1
Successfully submitted the transaction
~$ factom-cli balance fct factoid-wallet-address-name01
Balance of  factoid-wallet-address-name01  =  2000.0
~$ echo 

~$ 
~$ echo 1.2.1 CREATE ENTRY CREDIT WALLET ADDRESSES
1.2.1 CREATE ENTRY CREDIT WALLET ADDRESSES
~$ ECWALLETADDRESSKEY01=$(factom-cli generateaddress ec ec-wallet-address-name01 | awk '{print $3}')
~$ echo ec-wallet-address-name01 = $ECWALLETADDRESSKEY01
ec-wallet-address-name01 = EC1pUfktSZKAV8z24YSkNLjUnVDzDAzaz37jNEVncFnCtF66cL4L
~$ echo

~$ 
~$ echo 2.5 CREATE TRANSACTION WITH INPUT TO ENTRY CREDITS
2.5 CREATE TRANSACTION WITH INPUT TO ENTRY CREDITS
~$ factom-cli newtransaction transaction04
Success building a transaction
~$ factom-cli addinput transaction04 factoid-wallet-address-name01 100
Success adding Input
~$ factom-cli addecoutput transaction04 ec-wallet-address-name01 6
Success adding Entry Credit Output
~$ factom-cli sign transaction04
Success signing transaction
~$ factom-cli submit transaction04
Successfully submitted the transaction
~$ factom-cli balance fct factoid-wallet-address-name01
Balance of  factoid-wallet-address-name01  =  1900.0
~$ factom-cli balance ec ec-wallet-address-name01
Balance of  ec-wallet-address-name01  =  9000
~$ echo

~$ 
~$ echo 3.1.3 MAKE CHAIN USING ENTRY CREDIT ADDRESS NAME
3.1.3 MAKE CHAIN USING ENTRY CREDIT ADDRESS NAME
~$ echo

~$ echo Proposed New Chain ID
Proposed New Chain ID
~$ CHAINIDGOOD=$(factom-cli mkchain -e 123456 -e 123456 ec-wallet-address-name01 <~/testing/testing/test-plans-and-scripts/Robert-API/entries/2nd-entry | awk '{printf $3}')
~$ echo $CHAINIDGOOD
5f0efe39ef99fddd366785608dd821091e63d0c102d27e3147aa9f13c2fcd3cb
~$ echo

~$ echo WAITING 60 SECONDS FOR DIRECTORY BLOCK TO CLOSE
WAITING 60 SECONDS FOR DIRECTORY BLOCK TO CLOSE
~$ sleep 60
~$ echo

~$ echo Chain Head Merkelroot
Chain Head Merkelroot
~$ HEAD=$(factom-cli get chain $CHAINIDGOOD)
~$ echo $HEAD
3096c30bad79147205f9543695bec979b0897af1a6a8c4e515ea3765c469b21d
~$ factom-cli balance fct factoid-wallet-address-name01
Balance of  factoid-wallet-address-name01  =  1900.0
~$ factom-cli balance ec ec-wallet-address-name01
Balance of  ec-wallet-address-name01  =  8989
~$ echo

~$ 
~$ echo MAKE ENTRY USING FACTOID WALLET ADDRESS RATHER THAN ENTRY CREDIT WALLET ADDRESS
MAKE ENTRY USING FACTOID WALLET ADDRESS RATHER THAN ENTRY CREDIT WALLET ADDRESS
~$ ENTRYHASH=$(echo $(date +%S) | factom-cli put -c $CHAINIDGOOD factoid-wallet-address-name01 | awk '{printf $3}')
~$ echo Entry Hash = $ENTRYHASH
Entry Hash = 4eed962ad112eccb676cf8db4317bcc174040d5be7db55541ec069b03d4a1b57
~$ echo WAITING 60 SECONDS FOR DIRECTORY BLOCK TO CLOSE
WAITING 60 SECONDS FOR DIRECTORY BLOCK TO CLOSE
~$ sleep 60
~$ echo

~$ factom-cli get entry $ENTRYHASH
ChainID: 5f0efe39ef99fddd366785608dd821091e63d0c102d27e3147aa9f13c2fcd3cb
Content:
30 33 0a
                |                           || "03\n"
~$ 
~$ factom-cli balance fct factoid-wallet-address-name01
Balance of  factoid-wallet-address-name01  =  1900.0
~$ factom-cli balance ec ec-wallet-address-name01
Balance of  ec-wallet-address-name01  =  8989

**Comment by PaulSnow** [comment]
I believe this to be fixed.

**Comment by drobertbaker** [comment]
OK
