### ISSUE TITLE
Review interface refactorization

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#603]
After learning that some of the ways we were handling interfaces were improper (http://stackoverflow.com/q/31753282/953732), I went ahead and fixed the code to explicitly enforce interfaces. This uncovered that a lot of functions were missing a number of methods, which meant placeholder functions had to be added:

https://github.com/FactomProject/FactomCode/commit/6c0bc7e952b0fd61c10af9e27d94bab5b69c119e

https://github.com/FactomProject/factoid/commit/50c5fa706226915742f12df34152342789de5567

Some were rather minor, but others were missing sizable chunks of their functions:

https://github.com/FactomProject/factoid/commit/50c5fa706226915742f12df34152342789de5567#diff-2d4a3195d962b7fdb50aea8f7a6bddceR23

 https://github.com/FactomProject/factoid/commit/50c5fa706226915742f12df34152342789de5567#diff-62cbad112cbc6de5d194571e8da21ed6R20

It would be useful to go over the placeholder functions and figure out whether any of them need to be implemented and which can be left as placeholders for now. This refactoring broke some tests, meaning that somehow the improper interface code was probably somehow masking some problems.

**Comment by PaulSnow** [comment]
Done
