### ISSUE TITLE
PrevLedgerKeyMR field shows PrevLedgerBodyMR

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#608]
Note: This error behaviour is masked by https://github.com/FactomProject/WorkItems/issues/605

I add:
------------------------------- block/scblock.go -------------------------------
index 62af82b..44ad3b2 100644
@@ -115,6 +115,8 @@ func (b *FBlock) GetFullHash() fct.IHash {
         hashes = append(hashes,fct.Sha(fct.ZERO_HASH))
     }
     fullHash := fct.ComputeMerkleRoot(hashes) 
+    fmt.Printf("ledger body mr:\n")
+    fmt.Printf("%v\n", fullHash)
     return fullHash
 }
 
@@ -199,11 +201,15 @@ func (b *FBlock) MarshalHeader() ([]byte,error) {
     out.Write(data)
     
     if b.PrevFullHash == nil {b.PrevFullHash = new(fct.Hash)}
+    
     data, err = b.PrevFullHash.MarshalBinary()
     if err != nil {
         return nil, err
     }
+    fmt.Printf("prevLedgerKeyMR:\n")
+    fmt.Printf("%x\n", data)
     out.Write(data)
+

and I get:
```
ledger body mr:
85839816144de5861e0c3c88e2904af9582777eb8404e3daddcdceea83894457
prevLedgerKeyMR:
85839816144de5861e0c3c88e2904af9582777eb8404e3daddcdceea83894457
```

The LedgerKeyMR should be a hash of the header hashed with the LedgerBodyMR, not the Body MR itself.

**Comment by PaulSnow** [comment]
fixed
