### ISSUE TITLE
explorer frontend bug

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#609]
Wayne let me know that "the Explorer's current ripple effect has a bug and should be replaced with this code:"

http://db2k.github.io/MaterialRipple/

**Comment by ThePiachu** [comment]
Downloaded the code, but I'm not sure what goes where. I couldn't find the specific files from the package. I don't think I will be able to fix this - perhaps we can ask Wayne sometime down the line to fix that bug and do some other frontend tweaks as well in one go?

**Comment by carryforward** [comment]
In some browsers, the old ripple.js was causing users to have to click on an element twice. 


Old one is called ripple.js.  Get rid of that.
Some of the elements in the project will have the class .withripple.  Get rid of that too
remove the reference to materialdesign/ripple effects at the top of main.js
I’m unsure if material.js is used if ripple.js is removed.

**Comment by hannemennah** [comment]
Fixed!
