### ISSUE TITLE
2nd runtime instance of factomd just hangs

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#614]
Run 'factomd'.
Wait a minute.
Run 'factomd' again w/o shutting down the first instance -- this new instance just hangs.

Would be nice to display some error message and quit.

**Comment by PaulSnow** [comment]
Fixed

**Comment by m21** [comment]
@PaulSnow - where exactly was this fixed? I'd like to pull the exact fix into the P2P branch(es).

**Comment by PaulSnow** [comment]
I dunno.  Factomd now exits with:

2015/08/06 14:56:23 listen tcp :8090: bind: address already in use

I think I originally closed this bug when I thought I had the block error stuff hanging systems.  But I didn't do anything to make factomd stop (at least that I am aware of).  Let's ask around and see if anyone knows what changed.

**Comment by PaulSnow** [comment]
I appreciate you reopening this issue, M21, but I can't get factomd to hang.  And it does give a reasonable if cryptic error message.

**Comment by m21** [comment]
agreed. works now; thanks!
