### ISSUE TITLE
alert on bug with zeros as chainid in directory block

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#615]
Robert observed that occasionally directory blocks will be created with zeros in the chainid field instead of the chainid.

there is some code which returns zeros for hashes when an error occurs.  

the suggestion is to detect that error when a directory block is being created, and leave out, alert, or do something with the zeroed chain ID.

here are the databases robert generated: http://dropjar.com/#115e4j16

**Comment by ThePiachu** [comment]
We could also get to the root of the problem and make sure we never return zeroed hash without throwing an error as well.

**Comment by ThePiachu** [comment]
Here is the code to capture those errors in case we can't create a hash: https://github.com/FactomProject/FactomCode/commit/ae359f6830e1e3cf3613c4c46b72bce95d16fcff

**Comment by JackXLu** [comment]
Robert, can u try again? 
We added checks in multiple places. Thanks!

**Comment by drobertbaker** [comment]
I haven't been able to reproduce this error, Jack.

On Thu, Aug 6, 2015 at 1:34 PM, JackXLu <notifications@github.com> wrote:

> Robert, can u try again?
> We added checks in multiple places. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FactomProject/WorkItems/issues/615#issuecomment-128468394>
> .
>



-- 
Thanks,
D. Robert Baker
Process Integration Manager, factom
drobertbaker@factom.org
