### ISSUE TITLE
API: entry credit balances of factoid wallet addresses can be requested and vice versa

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#618]
~$ factom-cli getaddresses

  Factoid Addresses

                           dummy1    FA2HehwmxdvrEfBxuHQjeL1h3V6UGEK14KchsEdE4mYqvSHtx4hM          2199.0
                          dummy10    FA3Mtqn1yK1KqySDn4G6dQLjhPydNh8ue96yfgqi15KHucpvBw1u          4200.0
                           dummy2    FA2LcjuxeyBaXx4JfvH6iopizupoyztFqAq4FsKxALWewPxdH2mg          2199.0
                           dummy3    FA39GYnRRVeSP48bqxHPzZoKhReD5p3xTKTunTLW3QtrRESY7nyd          2199.0
                           dummy4    FA28cPaEwaKSm6Wa2uE9BeAyU7vk1eNbccjWPti9WynR2qLmYWhG          4200.0
                           dummy5    FA3eNd17NgaXZA3rXQVvzSvWHrpXfHWPzLQjJy2PQVQSc4ZutjC1          4200.0
                           dummy6    FA2t8BtoZUYMpt2tPJC1u6poPzxfKfaXahWu5DKXTZvav4ZY6RHv          4200.0
                           dummy7    FA3gBUV33eL2F12EbiNZGeAVECiUY8kR7viDDDcJwrrM1KXsEPjY          4200.0
                           dummy8    FA38F8fY6duMqDLyCNUYWemdFSWgXDSteeNvNCmJ1Eyb86Z3VNZo          4200.0
                           dummy9    FA2UojuPrDPNXMvaoNd5mV9gYrPtC8PSmb9Ku8oeCJKnWMjk7SN5          4200.0
    factoid-wallet-address-name01    FA3m8Z79SUeboR59B9dEZtpUzjnC3z1td6a5cWXWEguyuRpPjjHK          2000.0
    factoid-wallet-address-name02    FA3AjTLqzUAFGRzFLVa2THeEd8ZrWnBt49P72P4yiY1pAHkL2FkV          2000.0
    factoid-wallet-address-name03    FA3RCKaePTq1ffUdokTxiJd4CgFjwqEEW4QvRoi38bsy9V2QJP7R          2000.0

  Entry Credit Addresses

         ec-wallet-address-name01    EC3QeegGid2C7gbpbeYoseX2gSkiYsSamsX46RXqY6v8ewfwR7hK              0
         ec-wallet-address-name02    EC2TXCo8ZFaz2GeQUTjPy1VVDo1B5ALkWEzp7G4EDCRoEyfxGaPK              0

~$ factom-cli balance fct xxx
encoding/hex: odd length hex string
~$ factom-cli balance fct xxxx
encoding/hex: invalid byte: U+0078 'x'
~$ factom-cli balance fct ec-wallet-address-name01
Balance of  ec-wallet-address-name01  =  0.0

~$ factom-cli balance ec xxx
encoding/hex: odd length hex string
~$ factom-cli balance ec xxxx
encoding/hex: invalid byte: U+0078 'x'
~$ factom-cli balance ec factoid-wallet-address-name01
Balance of  factoid-wallet-address-name01  =  0.0

**Comment by PaulSnow** [comment]
fixed

**Comment by drobertbaker** [comment]
OK
