### ISSUE TITLE
Factoid block PrevKeyMR is incorrect in block 2

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#627]
In block 2 (the one right after Genesis Block), the factoid block's PrevKeyMR is incorrect - it does not match Genesis Factoid Block's KeyMR or hash. It seems that every time the chain is initialized, the PrevKeyMR is different, even though the genesis block is the same...

**Comment by ThePiachu** [comment]
It looks like the issue is caused by FactoidState not being initialized with the genesis block when it's created. Because of this, ProcessEndOfBlock2 creates a new block to serve as the Genesis Block instead, which causes the confusion.

**Comment by carryforward** [comment]
paul was zeroing in on that, when he had to take a call

**Comment by ThePiachu** [comment]
Looks like FactomCode/process/init.go initFctChain() can be to blame - it doesn't appear to be adding the Genesis Block to FactomState.

**Comment by ThePiachu** [comment]
The initialization order appears to be all wrong, perhaps that has something to do with it. With a clean database, there are three crucial calls being made early on. First, ProcessEndOfBlock2 is being called by:

C:/GoogleAppEngine/gopath/src/github.com/FactomProject/factoid/state/factoidstate.go:281 (0x5be8ae)
        (*FactoidState).ProcessEndOfBlock2: debug.PrintStack()
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/init.go:203 (0x48e1dd)
        initFctChain: common.FactoidState.ProcessEndOfBlock2(dchain.NextDBHeight)
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:129 (0x492861)
        initProcessor: initFctChain()
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:181 (0x49301f)
        Start_Processor: initProcessor()
c:/go/src/runtime/asm_amd64.s:2232 (0x42c1c1)
        goexit:

Then, ProcessEndOfBlock2 is being called by

C:/GoogleAppEngine/gopath/src/github.com/FactomProject/factoid/state/factoidstate.go:281 (0x5be8ae)
        (*FactoidState).ProcessEndOfBlock2: debug.PrintStack()
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:1039 (0x49ca87)
        newFactoidBlock: common.FactoidState.ProcessEndOfBlock2(chain.NextBlockHeight)
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:801 (0x49a996)
        buildGenesisBlocks: FBlock := newFactoidBlock(fchain)
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:137 (0x492ade)
        initProcessor: buildGenesisBlocks()
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:181 (0x49301f)
        Start_Processor: initProcessor()
c:/go/src/runtime/asm_amd64.s:2232 (0x42c1c1)
        goexit

And only then, AddTransactionBlock is being called with the proper genesis block by:

C:/GoogleAppEngine/gopath/src/github.com/FactomProject/factoid/state/factoidstate.go:151 (0x5bd2df)
        (*FactoidState).AddTransactionBlock: debug.PrintStack()
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:808 (0x49ace0)
        buildGenesisBlocks: common.FactoidState.AddTransactionBlock(FBlock)
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:137 (0x492ade)
        initProcessor: buildGenesisBlocks()
C:/GoogleAppEngine/gopath/src/github.com/FactomProject/FactomCode/process/processor.go:181 (0x49301f)
        Start_Processor: initProcessor()
c:/go/src/runtime/asm_amd64.s:2232 (0x42c1c1)
        goexit:

**Comment by ThePiachu** [comment]
So the problem was caused by two things - first, the Genesis Block was not saved into the FactoidState in initFctChain(), and secondly, after that problem was fixed, the code wasn't prepared to handle factoid blocks if ProcessEndOfBlock2 was called one time too many (it would leave a gap in the factoid blocks).

**Comment by ThePiachu** [comment]
Looks like the issue is back in the latest code.

**Comment by ThePiachu** [comment]
It looks like the current version of the bug is caused by https://github.com/FactomProject/factoid/blob/master/state/factoidstate.go#L293 - setting the exchange rate changes the block hash. The block itself may have already been saved into the database under a different hash, hence the issue.

**Comment by carryforward** [comment]
paul, this doesn't seem like it was fixed.

I look in the binaries to determine this:
in the directory block 0, the KeyMR of the factoid block is 38 E8 AF 4A AF...
in the factoid block 1, the PrevKeyMR is 3A 5E EB 69 7D...

**Comment by carryforward** [comment]
ok, checked on latest code and it works
