### ISSUE TITLE
factoid fountain generating 150 rather than 2000 factoids per 1st 10 factoid wallet addresses

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#631]
echo WAITING 60 SECONDS FOR FACTOMD TO INITIALIZE
sleep 60
echo
echo 1 WALLETS
echo
echo 1.1 FACTOID WALLET
echo
echo 1.1.1 CREATE FACTOID WALLET ADDRESSES        
echo
echo 1.1.1.1 CREATE LEGITIMATE FACTOID WALLET ADDRESSES CONTAINING 2000 FACTOIDS        
for ((i=1; i < 11; i++)); do echo "dummy$i ="$(factom-cli generateaddress fct dummy$i | awk '{print $3}'); done
dummy1 =FA2HehwmxdvrEfBxuHQjeL1h3V6UGEK14KchsEdE4mYqvSHtx4hM
dummy2 =FA2LcjuxeyBaXx4JfvH6iopizupoyztFqAq4FsKxALWewPxdH2mg
dummy3 =FA39GYnRRVeSP48bqxHPzZoKhReD5p3xTKTunTLW3QtrRESY7nyd
dummy4 =FA28cPaEwaKSm6Wa2uE9BeAyU7vk1eNbccjWPti9WynR2qLmYWhG
dummy5 =FA3eNd17NgaXZA3rXQVvzSvWHrpXfHWPzLQjJy2PQVQSc4ZutjC1
dummy6 =FA2t8BtoZUYMpt2tPJC1u6poPzxfKfaXahWu5DKXTZvav4ZY6RHv
dummy7 =FA3gBUV33eL2F12EbiNZGeAVECiUY8kR7viDDDcJwrrM1KXsEPjY
dummy8 =FA38F8fY6duMqDLyCNUYWemdFSWgXDSteeNvNCmJ1Eyb86Z3VNZo
dummy9 =FA2UojuPrDPNXMvaoNd5mV9gYrPtC8PSmb9Ku8oeCJKnWMjk7SN5
dummy10 =FA3Mtqn1yK1KqySDn4G6dQLjhPydNh8ue96yfgqi15KHucpvBw1u
echo 1.1.2 GET FACTOID WALLET ADDRESS BALANCES        
echo
echo 1.1.2.1 LIST ALL WALLET ADDRESS BALANCES        
factom-cli getaddresses
echo 
                           dummy1    FA2HehwmxdvrEfBxuHQjeL1h3V6UGEK14KchsEdE4mYqvSHtx4hM           150.0
                          dummy10    FA3Mtqn1yK1KqySDn4G6dQLjhPydNh8ue96yfgqi15KHucpvBw1u           150.0
                           dummy2    FA2LcjuxeyBaXx4JfvH6iopizupoyztFqAq4FsKxALWewPxdH2mg           150.0
                           dummy3    FA39GYnRRVeSP48bqxHPzZoKhReD5p3xTKTunTLW3QtrRESY7nyd           150.0
                           dummy4    FA28cPaEwaKSm6Wa2uE9BeAyU7vk1eNbccjWPti9WynR2qLmYWhG           150.0
                           dummy5    FA3eNd17NgaXZA3rXQVvzSvWHrpXfHWPzLQjJy2PQVQSc4ZutjC1           150.0
                           dummy6    FA2t8BtoZUYMpt2tPJC1u6poPzxfKfaXahWu5DKXTZvav4ZY6RHv           150.0
                           dummy7    FA3gBUV33eL2F12EbiNZGeAVECiUY8kR7viDDDcJwrrM1KXsEPjY           150.0
                           dummy8    FA38F8fY6duMqDLyCNUYWemdFSWgXDSteeNvNCmJ1Eyb86Z3VNZo           150.0
                           dummy9    FA2UojuPrDPNXMvaoNd5mV9gYrPtC8PSmb9Ku8oeCJKnWMjk7SN5           150.0

**Comment by drobertbaker** [comment]
more tesxxxxxt

**Comment by ThePiachu** [comment]
Okay, the addresses were added to the genesis block and should receive proper balances. That being said, some other bug surfaced and the balances appear to be doubled at the moment.

**Comment by drobertbaker** [comment]
OK
