### ISSUE TITLE
log statement in factomd.go needs fixing

### ISSUE THREAD

**Issue by PaulSnow** [FactomProject/WorkItems#644]
the statement FactomCode/factomd/factomd.go line 49:

ftmdLog.Warning("Go compiler version: %s",runtime.Version())  

should not have the %s.  This isn't a printf like interface, but a print like interace.

**Comment by michaelbeam** [comment]
in the log package I wrote there are 2 methods for each log level. e.g. flog.Warning() and flog.Warningf() which behave like fmt.Println() and fmt.Printf() respectively. 

So you should be able to fix this just by changing the Warning to Warningf.
