### ISSUE TITLE
Explorer is broken due to minute markers

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#645]
We added minute markers to the Entry Blocks to show the time.  I tried running the explorer and it tried to interpret the minute markers as entries.  I added this code to make it ignore them:

https://github.com/FactomProject/factomexplorer/blob/ExplorerV3/Synchronization.go#L394
```
	j := 0
	for _, v := range eBlock.Body.EBEntries {
		if !bytes.Equal(v.Bytes()[:31],common.ZERO_HASH[:31]) {
			entry, err:=FetchAndParseEntry(v.String(), blockTime)
			if err != nil {
				return nil, err
			}
			answer.EntryList[j] = entry
			j+=1
		}
	}
```

but then it started complaining about null entries here:
https://github.com/FactomProject/factomexplorer/blob/ExplorerV3/database.go#L79

It looks like we need to have a more intelligent way to handle minute markers than to ignore them.

**Comment by ThePiachu** [comment]
I guess this is a related issue - https://github.com/FactomProject/WorkItems/issues/601 . Depending on how we want to handle the minute markers and how to display the information they encode, we could either prune them, display them as some special entries or do something else entirely.

**Comment by ThePiachu** [comment]
Looking at the issue, yes, the minute entries can clog up the explorer page a bit, but it's mostly harmless otherwise. I will add some special "entry" handling along the line, but for now I think it's low priority.

**Comment by ThePiachu** [comment]
Okay, now I get that you were referring to minute markers in entry chains rather than admin block. Those appear to be more complicated...

**Comment by ThePiachu** [comment]
Fixed on branch https://github.com/FactomProject/factomexplorer/tree/RC2.1 with https://github.com/FactomProject/FactomCode/tree/Issue_%23595 code on FactomCode.
