### ISSUE TITLE
API:  1st 10 factoid wallet addresses being initialized to 2000 and staying at that value rather than increasing over time

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#647]

**Comment by ThePiachu** [comment]
On my machine they seem to be increasing over time. Heck, straight after the genesis block they already have a balance of 2050. How do you reproduce the bug?

**Comment by drobertbaker** [comment]
Piotr:

I switched over to the RC2 code. Now I'm getting all 0 balances.

1 WALLETS

1.1 FACTOID WALLET

1.1.1 CREATE FACTOID WALLET ADDRESSES

1.1.1.1 CREATE LEGITIMATE FACTOID WALLET ADDRESSES CONTAINING 2000 FACTOIDS

for ((i=1; i < 11; i++)); do echo "dummy$i ="$(factom-cli generateaddress fct dummy$i | awk '{print $3}'); done

dummy1 =FA2HehwmxdvrEfBxuHQjeL1h3V6UGEK14KchsEdE4mYqvSHtx4hM
dummy2 =FA2LcjuxeyBaXx4JfvH6iopizupoyztFqAq4FsKxALWewPxdH2mg
dummy3 =FA39GYnRRVeSP48bqxHPzZoKhReD5p3xTKTunTLW3QtrRESY7nyd
dummy4 =FA28cPaEwaKSm6Wa2uE9BeAyU7vk1eNbccjWPti9WynR2qLmYWhG
dummy5 =FA3eNd17NgaXZA3rXQVvzSvWHrpXfHWPzLQjJy2PQVQSc4ZutjC1
dummy6 =FA2t8BtoZUYMpt2tPJC1u6poPzxfKfaXahWu5DKXTZvav4ZY6RHv
dummy7 =FA3gBUV33eL2F12EbiNZGeAVECiUY8kR7viDDDcJwrrM1KXsEPjY
dummy8 =FA38F8fY6duMqDLyCNUYWemdFSWgXDSteeNvNCmJ1Eyb86Z3VNZo
dummy9 =FA2UojuPrDPNXMvaoNd5mV9gYrPtC8PSmb9Ku8oeCJKnWMjk7SN5
dummy10 =FA3Mtqn1yK1KqySDn4G6dQLjhPydNh8ue96yfgqi15KHucpvBw1u

1.1.2 GET FACTOID WALLET ADDRESS BALANCES

1.1.2.1 LIST ALL WALLET ADDRESS BALANCES
  Factoid Addresses

                           dummy1    FA2HehwmxdvrEfBxuHQjeL1h3V6UGEK14KchsEdE4mYqvSHtx4hM             0.0
                          dummy10    FA3Mtqn1yK1KqySDn4G6dQLjhPydNh8ue96yfgqi15KHucpvBw1u             0.0
                           dummy2    FA2LcjuxeyBaXx4JfvH6iopizupoyztFqAq4FsKxALWewPxdH2mg             0.0
                           dummy3    FA39GYnRRVeSP48bqxHPzZoKhReD5p3xTKTunTLW3QtrRESY7nyd             0.0
                           dummy4    FA28cPaEwaKSm6Wa2uE9BeAyU7vk1eNbccjWPti9WynR2qLmYWhG             0.0
                           dummy5    FA3eNd17NgaXZA3rXQVvzSvWHrpXfHWPzLQjJy2PQVQSc4ZutjC1             0.0
                           dummy6    FA2t8BtoZUYMpt2tPJC1u6poPzxfKfaXahWu5DKXTZvav4ZY6RHv             0.0
                           dummy7    FA3gBUV33eL2F12EbiNZGeAVECiUY8kR7viDDDcJwrrM1KXsEPjY             0.0
                           dummy8    FA38F8fY6duMqDLyCNUYWemdFSWgXDSteeNvNCmJ1Eyb86Z3VNZo             0.0
                           dummy9    FA2UojuPrDPNXMvaoNd5mV9gYrPtC8PSmb9Ku8oeCJKnWMjk7SN5             0.0

**Comment by drobertbaker** [comment]
Paul fixed it by updating my factom.conf file.
