### ISSUE TITLE
check for errors better in factom-cli and fctwallet

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#662]
https://github.com/FactomProject/factom-cli/blob/master/transaction.go#L32

we just check length and alphabet.  We probably want to differentiate betwen hex, human readable, and nickname addresses.

This may be handled at the fctwallet layer already.

**Comment by ThePiachu** [comment]
First implementation - https://github.com/FactomProject/fctwallet/commit/8c299b4bd90ca7500c0c452c02cf27b6f7d8b078#diff-7fe0c1ce18330ec62965216820826e68R1

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/19/2016
