### ISSUE TITLE
blocks_test.go is broken in RC2.1

### ISSUE THREAD

**Issue by PaulSnow** [FactomProject/WorkItems#663]
Run:
       ./all.sh RC2.1 development

Result:

+================+
|  FactomCode    |
+================+

?   	github.com/FactomProject/FactomCode/anchor	[no test files]
# github.com/FactomProject/FactomCode/factomd/test
FactomCode/factomd/test/blocks_test.go:16: undefined: loadConfigurations
FactomCode/factomd/test/blocks_test.go:18: undefined: initDB
FactomCode/factomd/test/blocks_test.go:21: undefined: db in db.FetchDBlockByHeight
FactomCode/factomd/test/blocks_test.go:39: undefined: db in db.FetchECBlockByHash
FactomCode/factomd/test/blocks_test.go:42: undefined: db in db.FetchABlockByHash
FactomCode/factomd/test/blocks_test.go:45: undefined: db in db.FetchFBlockByHash
FactomCode/factomd/test/blocks_test.go:48: undefined: db in db.FetchEBlockByMR
FactomCode/factomd/test/blocks_test.go:52: undefined: db in db.FetchEntryByHash

Not sure if this is a valid test?  Did something break?  Maybe doesn't belong in RC2.1?

**Comment by JackXLu** [comment]
removed the test
