### ISSUE TITLE
human readable addresses hash incomplete data

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#664]
https://github.com/FactomProject/factoid/blob/master/util.go#L210
and 
https://github.com/FactomProject/factoid/blob/master/util.go#L248

code currently makes addresses like: EC34f3BoBdqspeJ5J8tX82xmkMfTqKfVJsgKL9nv9PcBob7hqmBd

which has the checksum as a hash of the pubkey alone.

The checksum should cover the prefix and the pubkey.
https://github.com/FactomProject/FactomDocs/blob/master/factomDataStructureDetails.md#entry-credit-address

**Comment by PaulSnow** [comment]
Fixed

**Comment by carryforward** [comment]
verified ok for ec and factoid addresses
