### ISSUE TITLE
factom wallet cannot send ECs to address not in wallet

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#666]
This check stops me from sending entry credits to an address not in the wallet.

https://github.com/FactomProject/factoid/blob/master/wallet/scwallet.go#L363

to replicate:
```
factom-cli newtransaction newtrans
factom-cli addecoutput newtrans EC2DKSYyRcNWf7RS963VFYgMExoHRYLHVeCfQ9PGPmNzwrhnRpNG 49.5
```

**Comment by PaulSnow** [comment]
Fixed

**Comment by carryforward** [comment]
no dice.

when I run `factom-cli addecoutput newtrans EC2DKSYyRcNWf7RS963VFYgMExoHRYLHVeCfQ9PGPmNzwrhnRpNG 49.5`

after clearing databases, running setup, then making a newtrans, it still gives the error:
```
factom-cli addecoutput newtrans EC1m9mouvUQeEidmqpUYpYtXg8fvTYi6GNHaKg8KMLbdMBrFfmUa 49.8
Failed to add input
```

**Comment by PaulSnow** [comment]
Actually the ecoutput was added, there was just  a bogus error message coming back.  If you did it twice, you would see success (but that is because we replace existing outputs if the match existing outputs).

Got rid of the bogus error message.

**Comment by carryforward** [comment]
now none of the ec balances increase, even the ones in the wallet.

I even updated the remote server to the latest RC2.1, even though that shouldn't have anything to do with this.

**Comment by PaulSnow** [comment]
Not an address problem.  This is the minute marker "fix" not done right.

**Comment by carryforward** [comment]
done
