### ISSUE TITLE
API: duplicate TRANSACTION response has devolved

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#669]
Trying to create a transaction that is still open was giving the graceful response:

"Duplicate key: ' transaction01 '"

Now, it gives:

Failed to parse the response from factomd: {"Response":"Duplicate key: '%!(EXTRA string=transaction01, string=')","Success":false}{"Response":"Success building a transaction","Success":true}

**Comment by PaulSnow** [comment]
Fixed

**Comment by drobertbaker** [comment]
OK
