### ISSUE TITLE
API: able to create FACTOID WALLET ADDRESS NAME and ENTRY CREDIT WALLET ADDRESS NAME longer than 32 characters

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#673]
factom-cli generateaddress fct factoid-wallet-address-name890123
fct  =  EC3dgEEvsp4T789GsbwCW8VAAVVn6V9rkQbc1VC35CgN9tXdzCqM
factom-cli balance fct factoid-wallet-address-name890123
Address undefined or invalid

factom-cli generateaddress ec entry-credit-wallet-address-name01
ec  =  EC2FubrZkccGNQEjKLiHxCptndnALFvhrN2rrxu7WYEzB8afwoPS
factom-cli balance ec entry-credit-wallet-address-name01
Address undefined or invalid

**Comment by PaulSnow** [comment]
Fixed

**Comment by drobertbaker** [comment]
OK
