### ISSUE TITLE
oversized first entry should not be allowed

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#674]
When I create an oversized first entry, and pay for it, factomd will create a chain using it.

Maximum First entry size is 10275 bytes

https://github.com/FactomProject/FactomDocs/blob/master/factomDataStructureDetails.md#entry

**Comment by carryforward** [comment]
here is code to replicate:
http://pastebin.com/r0ABr8zT

**Comment by carryforward** [comment]
entry commit limiting code is here:

https://github.com/FactomProject/FactomCode/blob/RC2.1/process/processor.go#L487

**Comment by carryforward** [comment]
I was also able to place a 17 kib entry

**Comment by carryforward** [comment]
boundries between different sizes seem to be incorrect as well.  should be fixed with https://github.com/FactomProject/FactomCode/blob/RC2.1/process/processor.go#L487

**Comment by JackXLu** [comment]
fixed

**Comment by carryforward** [comment]
seems ok.  Some weirdness when I tried to make a chain with the same chainID using successively smaller entries.  

The behaviour is to block the operation, so i suppose it is safe.  something to look at in milestone 2.
