### ISSUE TITLE
chain reveal should satisfy commit

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#675]
If I commit a chain with a bogus chainid hash, the chain will still be created.

replication code here: http://pastebin.com/H8XJq7zT
see line 157

**Comment by carryforward** [comment]
might be in the same class as https://github.com/FactomProject/WorkItems/issues/368

**Comment by carryforward** [comment]
also creates chain with bogus weld: http://pastebin.com/Kpd6iLNy

**Comment by JackXLu** [comment]
fixed

**Comment by carryforward** [comment]
ok
