### ISSUE TITLE
First entry allows mismatch between chainId and chain name

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#676]
When a first entry is created, the chainID should be a hash of the Chain Name elements.

When a bogus ChainID is used, it still makes a new chain.

to replicate see: http://pastebin.com/NwVqnvTB
line 105

**Comment by ThePiachu** [comment]
I tried replicating the bug with the code, but I don't see the block on the blockchain. Does the bug relate to the block being embedded into the blockchain, or factomd returning that it accepted the block without error even though it won't incorporate it?

**Comment by carryforward** [comment]
ok, it looks like this was overfixed.  This rule should only apply when making a chain, when the entry is the first one in the chain.  

This rule seems to be applied to all entries, which kind of defeats the purpose.

**Comment by JackXLu** [comment]
Moved the validation code to processor so it won't apply to the regular entry reveals

**Comment by carryforward** [comment]
good
