### ISSUE TITLE
FactomRelay was disabled for MS1 - figure out why & what happens in P2P

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#678]
https://github.com/FactomProject/btcd/blob/dea7974137033023d0fbf5cfa3342e24556bedf8/peer.go#L1604

**Comment by drobertbaker** [comment]
unassigned m21

**Comment by PaulSnow** [comment]
Not needed?

**Comment by drobertbaker** [comment]
No one knows what FactomRelay is.
