### ISSUE TITLE
API: TRYing TO ADD ENTRY TO CHAIN USING FACTOID WALLET ADDRESS RATHER THAN ENTRY CREDIT WALLET ADDRESS gives "Server Error"

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#680]
factom-cli put -e 5 -e 5 -c $CHAINIDGOOD $FACTOIDWALLETADDRESSKEY03 <~/testing/testing/test-plans-and-scripts/Robert-API/entries/small-entry

Creating Entry: 03fd39c3d6c0a08302d1ba7868e2e652b5b2378c9361ea183d39b5b78f639257
Server Error

**Comment by PaulSnow** [comment]
I get no error at all.

**Comment by PaulSnow** [comment]
.Michael,  You should check the balance at the address and report an error if there isn't enough funds to cover the entry commit/reveal.

This command appears to succeed even when it doesn't.
