### ISSUE TITLE
Test versions

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#682]
Please test submit Entry, Chain, factoid transactions with different version numbers 0, 1, ...

**Comment by carryforward** [comment]
close, but no cigar.

The chain commit blocks the wrong version, but the entry can have the wrong version:
http://pastebin.com/PQ0jJv1d  line 116

http://pastebin.com/x048fSLT line 98

**Comment by JackXLu** [comment]
Added version check for entry reveal

**Comment by carryforward** [comment]
works
