### ISSUE TITLE
API: adding an entry of length 1024 bytes (no external ids) to a chain costs 2 entry credits

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#689]
1-1023 = 1
1024-2047 = 2
2048-3071 = 3
3072-4095 = 4
4096-5119 = 5
5120-6143 = 6
6144-7167 = 7
7168-8191 = 8
8192-9215 = 9
9216-10239 = 10
10240 = "Entry of 10241 bytes is too large"

~$ factom-cli mkchain ec-wallet-address-name01 ~/testing/testing/test-plans-and-scripts/Robert-API/entries/1024-4byte-entry
CHAINID=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

~$ factom-cli balance ec ec-wallet-address-name01
Balance of  ec-wallet-address-name01  =  2835

~$ factom-cli put -c e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 ec-wallet-address-name01 <~/testing/testing/test-plans-and-scripts/Robert-API/entries/1024-byte-entry
Creating Entry: 481e9f1eddb1a7cd368db3e5e1a2e0a7ef0f629fe76e009e9c36f699eb65ff96

~$ factom-cli balance ec ec-wallet-address-name01
Balance of  ec-wallet-address-name01  =  2833

~$ factom-cli put -c e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 ec-wallet-address-name01 <~/testing/testing/test-plans-and-scripts/Robert-API/entries/1023-byte-entry
Creating Entry: 76bb05acbbf9e64a505317c737874fc30127ab14e1f390987d0c30738dddef1b

~$ factom-cli balance ec ec-wallet-address-name01
Balance of  ec-wallet-address-name01  =  2832

~$ factom-cli put -c e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 ec-wallet-address-name01 <~/testing/testing/test-plans-and-scripts/Robert-API/entries/10240-byte-entry
Entry of 10241 bytes is too large

**Comment by JackXLu** [comment]
Please double check your input files:
jlu@ubuntu:~/Downloads$ wc -c 1023-byte-entry 
1024 1023-byte-entry
jlu@ubuntu:~/Downloads$ wc -c 1024-byte-entry 
1025 1024-byte-entry
jlu@ubuntu:~/Downloads$ wc -c 10240-byte-entry 
10241 10240-byte-entry
jlu@ubuntu:~/Downloads$

**Comment by drobertbaker** [comment]
Solved - final invisible LF functioning as EOF in character test files is not counted by many tools as a character. This made factom appear to be off by one in its character counts, where in fact it is not.
