### ISSUE TITLE
Entry and Chain commits are not processes with delayed/ future timestamps

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#692]
not really a problem now, but will be once we start with the p2p network and https://github.com/FactomProject/WorkItems/issues/368 starts.

I am running with 1 minute blocks, and I set the timestamp 100 seconds into the future or past, and the commit is not placed in the EC block.

**Comment by JackXLu** [comment]
changed the commit time window to 12 hours instead of 24 hours

move it back to milestone 2 because another ticket #697  is created

**Comment by carryforward** [comment]
now works

**Comment by carryforward** [comment]
ok, this is a reminder to better handle this along with #368 I'll open it back up

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/18/2016
