### ISSUE TITLE
IsTSValid function not working

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#697]
It won't pass the IsTSValid check if the time added is over 76 (see below)

       millitime = int((time.time() + 76)* 1000)  # time() gives floating point, so this tries to be millisecond     accurate

http://pastebin.com/Fp1qCLdy

Also I got a panic error after I ran the python scripts a few times:

panic: runtime error: index out of range

goroutine 20 [running]:
github.com/FactomProject/FactomCode/process.IsTSValid(0xc2087246e0, 0x20, 0x20, 0x55e0dc30, 0x1)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/replay.go:60 +0x359
github.com/FactomProject/FactomCode/process.serveMsgRequest(0x7ffff7fcd728, 0xc208598050, 0x0, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/processor.go:266 +0x1083
github.com/FactomProject/FactomCode/process.Start_Processor(0x7ffff7fb15a8, 0xc208047680, 0xc2080fa600, 0xc2080fa660, 0xc2080fa6c0, 0xc2080fa720)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/processor.go:207 +0x248
created by main.factomdMain
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:96 +0x90

goroutine 1 [chan receive, 41 minutes]:
github.com/FactomProject/btcd.btcdMain(0x0, 0x0, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/btcd.go:152 +0x741
github.com/FactomProject/btcd.Start_btcd(0x7ffff7fb15a8, 0xc208047680, 0xc2080fa600, 0xc2080fa660, 0xc2080fa6c0, 0xc2080fa720, 0xc2080f7c10, 0x8, 0xc2080f7ff0, 0xb, ...)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom.go:197 +0x283
main.factomdMain(0x0, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:126 +0x467
main.main()
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:87 +0x9ac

**Comment by PaulSnow** [comment]
After much dorking around, I get:

```
(development) replay_test $ ./Replay.py 

Add Entry Credits to this key: EC2fLinz6Qsr7Yb6aG59zQp1A79oo9kP1GQbNoe6pRVmriuwXjUy
It currently has a balance of 2796

Writing to the Factom API
entry:009e54c63c6ccf2f1e7bb6e86a4e026b63c5665dca2b649c1cb407d2e39d7e83f3001500056578746964000c616e6f74686572657874696468656c6c6f20776f726c6434
commit:00014f76bd5027faac4fbc14f543d690aa5716629728460cff8f17f825ea226106144eb7bd25850a76803ef880899cbe53ac6063aa92f47fd82647b68b299b7fc775118cbea96e10bb0cb505823851b265f58a7e7e4efbf3b66d119190a6dee87a80558cf49a1f7d1b0c276cdeaccc39e278c1e7733cb9fae7f5d10fcf622095636206db798b2d05
commit gives status: 200
entry:009e54c63c6ccf2f1e7bb6e86a4e026b63c5665dca2b649c1cb407d2e39d7e83f3001500056578746964000c616e6f74686572657874696468656c6c6f20776f726c6434
reveal gives status: 200
entry:009e54c63c6ccf2f1e7bb6e86a4e026b63c5665dca2b649c1cb407d2e39d7e83f3001500056578746964000c616e6f74686572657874696468656c6c6f20776f726c6434
wrote faac4fbc14f543d690aa5716629728460cff8f17f825ea226106144eb7bd2585
hello world4
```

**Comment by carryforward** [comment]
fixed
