### ISSUE TITLE
token sale words import checksum

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#698]
the 12 words have a checksum embedded into them.  When I type in the wrong words, instead of failing a checksum, it imports the private key.

the checksum should fail if incorrect words are entered.

**Comment by carryforward** [comment]
should be fixed in both walletapp and fctwallet

**Comment by ThePiachu** [comment]
Looks like the BIP39 package doesn't do any checksum validation - https://github.com/FactomProject/go-bip39/blob/master/bip39.go#L77 . It doesn't even have the code to reverse the mnemonic into []byte.
