### ISSUE TITLE
Factom-cli generateaddress is not working as expected

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#704]
jlu@ubuntu:~$ factom-cli generateaddress fct jack3
fct  =  FA39GYnRRVeSP48bqxHPzZoKhReD5p3xTKTunTLW3QtrRESEcxd7
jlu@ubuntu:~$ factom-cli getaddresses

  Factoid Addresses

      jack    FA2vGRwutdPdTHQa7kkpX3LkSgqKQ1MS2nur4UqbxqP5MGHcziWa             2.241088
     jack3    FA39GYnRRVeSP48bqxHPzZoKhReD5p3xTKTunTLW3QtrRESEcxd7          1250.0

  Entry Credit Addresses

    jackco    EC2x8oEKJSjsciQKAwd9TEfXJTs6BEX2da6Db3KKWMqC3DxtTSbE              0

**Comment by JackXLu** [comment]
It seems the balance increase by 50 every 10 minutes

**Comment by PaulSnow** [comment]
This is a fixed bug.  The coinbase reward payment was removed this afternoon.
