### ISSUE TITLE
Allow user to run factomd as a server with the master branch code

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#714]

**Comment by PaulSnow** [comment]
Need to make a compile time choice of a Production Server/Client  vs Development Server/Client.

Explore build tags in go for conditional compilation.

**Comment by JackXLu** [comment]
Hotfix1 will take the pub key from the server private key in config file if it's running as a server

**Comment by carryforward** [comment]
verified ok in hotfix branch
