### ISSUE TITLE
Check the total balance of factoids periodically

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#719]

**Comment by carryforward** [comment]
ec pubkey is 17ef7a21d1a616d65e6b73f3c6a7ad5c49340a6c2592872020ec60767ff00d7d

**Comment by carryforward** [comment]
also known as EC1whAxbYYsfQoAFLuzHCsz4Qz29WePBcrrGj5MqMQ1PR43wjiBH

**Comment by carryforward** [comment]
Should be good for the next 6 months now.
