### ISSUE TITLE
Factomd should allow address indexing by both the public key and address when possible

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#722]
I recently ran some tests. It looks like Factomd indexes balances only by the form they appear in the block as. For example, the public key 8cba3aeb7d16269da4f37d0c98979a7d9b23943774be232e817504ec8ab7e2a7 has a balance of 0.5 Factoids. The corresponding address, FA3DbvfudvvSaCAKNjUjh5fJX6WYbDJn1wgXGTFExr5WX8avy1gU appears to have a balance of 0. It would be better if factomd indexed the balances by both public key and address when possible.

**Comment by PaulSnow** [comment]
The public key and the Factoid key in your bug isn't the same.

**Comment by ThePiachu** [comment]
How about 

0c4efc84e96dde7eecc553c26d18767716cf2c2a3697cc34a0e0bf9183c51507

and

FA2Q5M8iTGLAtTZfNdtFaRHziyo6pFN3Hs192YsBBZvUJQGERuiF

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/19/2016
