### ISSUE TITLE
API: "factom-cli transactions" shows incorrect MilliTimestamp

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#723]
Transaction occurred at 5:55 p.m. Central time.

The time shown was:

MilliTimestamp: 0000014f956bc2b3 Sep 3, 2015 at 10:55am (UTC)

The time shown SHOULD be 10:55PM (UTC)

**Comment by PaulSnow** [comment]
Moved to a standard format.

**Comment by drobertbaker** [comment]
It's still doing this. I just made a transaction at 1:46 PM CST and got:

~$ factom-cli transactions

transaction01:  Fee Due: 0.013332   Currently will pay: 1.0

Transaction (size 143):
                 Version: 0000000000000002
          MilliTimestamp: 0000014ff66143b9 Sep 22, 2015 at 6:46am (UTC)
                # Inputs: 0001
               # Outputs: 0000
   # EntryCredit Outputs: 0000
      input:            1.0        FA2jK2HcLnRdS94dEcU27rF3meoJfpUcZPSinpb7AwQvPRY6RL1Q
                  0000000005f5e100 factoid-wallet-address-name01

RCD 1: 01 718b5edd2914acc2e4677f336c1a32736e5e9bde13663e6413894f57ec272e28
Signature Block: 
 signature:  signature: ec4ca4c4f7f6c5121e9d3bb2f53b46f7637acd9af1d1e65611283913804292e1790bc14b6b2c4844894b249f4bb39fe3114b7817cfb83fcde5f792dfaa06e102

It should be 6:46pm (UTC)

**Comment by drobertbaker** [comment]
The time stamp is showing an extraneous "+0000" on the end. Do you want that?

transaction01: Fee Due: 0.006666 Currently will pay: 0.0

WARNING: Currently your transaction fee may be too low

Transaction (size 10):
Version: 0000000000000002
MilliTimestamp: 0000015006c8c470 Fri, 25 Sep 2015 23:13:52 +0000
# Inputs: 0000
# Outputs: 0000
# EntryCredit Outputs: 0000

**Comment by PaulSnow** [comment]
The +0000 is a standard UTC timestamp indicator.  The alternative is (UTC)
 which is just as many characters.  When you get into other timezones with
daylight savings time, giving the hour offset works better than saying
(CST) or (CDT)...

**Comment by drobertbaker** [comment]
OK
