### ISSUE TITLE
Fix re-anchor due to double spending or bitcoin tx mutation

### ISSUE THREAD

**Issue by SirHalsell** [FactomProject/WorkItems#727]
this case is hard to test b/c it's hard to re-create a double spending or btc tx mutation. 

One proof is, when this code is deployed to prd server, and the dir block 122 is re-anchored successfully.

I've tested anchor locally and it worked well. So the min test is to ensure the anchor working in testnet.

**Comment by carryforward** [comment]
tested in the anchor_btcd branch
