### ISSUE TITLE
walletapp: export always returns the same (incorrect) private key

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#743]
===============> exportkey robert
Private Key:
   Fs1KWJrpLdfucvmYwN2nWrwepLn8ercpMbzXshd1g8zyhKXLVLWj
   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Public Key:
   FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb
   a675d5ad742ccc4f33f5769724e1522be33cc8b09e57e0e73a25c2227847811b

===============> exportkey testing
Private Key:
   Fs1KWJrpLdfucvmYwN2nWrwepLn8ercpMbzXshd1g8zyhKXLVLWj
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Public Key:
   FA2jK2HcLnRdS94dEcU27rF3meoJfpUcZPSinpb7AwQvPRY6RL1Q
   646f3e8750c550e4582eca5047546ffef89c13a175985e320232bacac81cc428

===============> import bob Fs1KWJrpLdfucvmYwN2nWrwepLn8ercpMbzXshd1g8zyhKXLVLWj
Could not find the input file Fs1KWJrpLdfucvmYwN2nWrwepLn8ercpMbzXshd1g8zyhKXLVLWj

**Comment by carryforward** [comment]
fixed: https://github.com/FactomProject/fctwallet/commit/f6ff14c4129bfc14bb51852c7e56b8e5f69be7f5

**Comment by carryforward** [comment]
test please

**Comment by drobertbaker** [comment]
OK
