### ISSUE TITLE
make the size of the factom database accessible for statistic analysis

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#744]

**Comment by PaulSnow** [comment]
Going to let Justin take a crack at this.

**Comment by hannemennah** [comment]
This can be done with the following bash script:

#!/bin/bash

 date +%s | tr -d '\n' >> ~/.factom/dbsize.csv
 echo -n "," >> ~/.factom/dbsize.csv
 du -s ~/.factom/ldb9/ | cut -f -1 >> ~/.factom/dbsize.csv

**Comment by hannemennah** [comment]
Explanation: 

1) Take the current time (formatted as a [Unix epoch time](https://en.wikipedia.org/wiki/Unix_time)), without the newline at the end
2) Put a comma after it (to separate the time from the database size)
3) Take the current size of the ~/.factom/ldb9/ folder (which contains all factom data) 

Append all of this to the ~/.factom/dbsize.csv file, for further analysis.

**Comment by hannemennah** [comment]
Final note: you can place this script into your /etc/cron.daily/ folder if you would like for it to automatically run once per day.

**Comment by drobertbaker** [comment]
OK
