### ISSUE TITLE
API: failed to sign transaction, on FULL server

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#746]
===============> balances

  Factoid Addresses

    robert    FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb           300.0

===============> 
===============> ^C~$ 

~$ ECWALLETADDRESSKEY01=$(factom-cli generateaddress ec ec-wallet-address-name01 | awk '{print $3}')
~$ echo ECWALLETADDRESSKEY01=$ECWALLETADDRESSKEY01
ECWALLETADDRESSKEY01=EC2woDfzchNAU74hFmUpaMqrDEC7FhYpPZEXBwqvZzVU919CbosV
~$ factom-cli newtransaction transaction04
Success building a transaction
~$ factom-cli addinput transaction04 FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb 10
Success adding Input
~$ factom-cli addecoutput transaction04 ec-wallet-address-name01 9
Success adding Entry Credit Output
~$ factom-cli sign transaction04
Failed to parse the response from factomd: Server Error

**Comment by PaulSnow** [comment]
Okay, so reproducing this bug takes a bit of guessing.  First guess is that you do not have the private key (an entry in your wallet) for the address FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb.    Maybe it has not been imported?

Assuming that was the problem, I ran the following commands:

factom-cli newtransaction t
factom-cli addinput t FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb 10
factom-cli  addecoutput t EC2woDfzchNAU74hFmUpaMqrDEC7FhYpPZEXBwqvZzVU919CbosV 9
factom-cli sign t

And I got the error:

Failed to parse the response from factomd: Server Error

Now assuming that was the error, I dug through the code and found where the error reporting was goofed up.   You now get this message:

Do not have all the private keys required to sign this transaction
Do not have the private key for: FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb

If you had multiple address for which you had no private keys, they would all be listed.

**Comment by drobertbaker** [comment]
I did the import via walletapp immediately before the commands I showed
you, but I didn't want to include it in the code I shared with you, because
I thought it was a bad idea to have private keys posted on github.

The executed code with the problem in the environment is still sitting on
my machine if you would like to play with it.

On Sat, Sep 19, 2015 at 7:05 PM, Paul Snow <notifications@github.com> wrote:

> Okay, so reproducing this bug takes a bit of guessing. First guess is that
> you do not have the private key (an entry in your wallet) for the address
> FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb. Maybe it has not been
> imported?
>
> Assuming that was the problem, I ran the following commands:
>
> factom-cli newtransaction t
> factom-cli addinput t FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb
> 10
> factom-cli addecoutput t
> EC2woDfzchNAU74hFmUpaMqrDEC7FhYpPZEXBwqvZzVU919CbosV 9
> factom-cli sign t
>
> And I got the error:
>
> Failed to parse the response from factomd: Server Error
>
> Now assuming that was the error, I dug through the code and found where
> the error reporting was goofed up. You now get this message:
>
> Do not have all the private keys required to sign this transaction
> Do not have the private key for:
> FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb
>
> If you had multiple address for which you had no private keys, they would
> all be listed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FactomProject/WorkItems/issues/746#issuecomment-141721337>
> .
>



-- 
Thanks,
D. Robert Baker
Process Integration Manager, factom
drobertbaker@factom.org

**Comment by PaulSnow** [comment]
We worked through this, and the problem is that the walletapp isn't the cli... Must import addresses in the cli.   Added proper error messages to avoid this problem in the future.
