### ISSUE TITLE
factom-cli / fctwallet does not properly import EC private keys

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#749]
with the command:

factom-cli newaddress ec im1 Es2Rf7iM6PdsqfYCo3D1tnAR65SkLENyWJG1deUzpRMQmbh9F3eG

it gives

"Invalid private key length"

**Comment by carryforward** [comment]
this is still an issue.

**Comment by carryforward** [comment]
This seems like an easy one to fix justin

**Comment by hannemennah** [comment]
Strangely, I wasn't able to replicate this issue:

$ factom-cli newaddress ec im1 Es2Rf7iM6PdsqfYCo3D1tnAR65SkLENyWJG1deUzpRMQmbh9F3eG
ec  =  EC2DKSYyRcNWf7RS963VFYgMExoHRYLHVeCfQ9PGPmNzwrcmgm2r

$ factom-cli balances

  Factoid Addresses
 sand    FA2jK2HcLnRdS94dEcU27rF3meoJfpUcZPSinpb7AwQvPRY6RL1Q           300.0
 ylw    FA3cih2o2tjEUsnnFR4jX1tQXPpSXFwsp3rhVp6odL5PNCHWvZV1             0.0

  Entry Credit Addresses

 im1    EC2DKSYyRcNWf7RS963VFYgMExoHRYLHVeCfQ9PGPmNzwrcmgm2r              0

I'll be testing further to see if I can get the same results you're getting, and we can discuss this later today in person.

**Comment by hannemennah** [comment]
(I also performed identical tests without factomd running, to see if that had an effect. Same results.)

**Comment by carryforward** [comment]
yep, looks like it was fixed.  weird.
