### ISSUE TITLE
Address transaction malleability problems

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#752]
Since Bitcoin transactions are subject to the malleability problem, we should be prepared for them while handling anchor transactions.

Since the changed transaction still contains a valid record, we should just use whichever transaction makes it into a block. Moreover, we should make sure we don't spend unconfirmed transaction outputs to avoid the problem of them being invalidated if a wrong transaction makes it into a block. Perhaps we should also anticipate small forks in Bitcoin that can change which transaction makes it into a block.

**Comment by PaulSnow** [comment]
We check for replay attacks using factoids against the Signature Hash (this is the hash we sign, and it doesn't include the signature).   See FactomCode/process/processor.go line 383.

This means no matter how the transaction is malleated, only one transaction is accepted.

**Comment by carryforward** [comment]
subset of #887
