### ISSUE TITLE
Create DB interface and use it

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#754]

**Comment by PaulSnow** [comment]
Not entirely certain what this means.   Jack and I had a discussion about database interfaces today... do you mean come to a decision about one interface?

**Comment by ThePiachu** [comment]
I think that was in regards to a discussion we had a few days ago. We wanted to create a straightforward DB interface that we would later use for both bolt and whatever else we decided to switch it up to. It would probably be a simpler interface than what we currently have for easier modularity - "save value by key", "load value by key", "delete value by key" and possibly something with caching. Something like this perhaps: https://github.com/FactomProject/factomexplorer/blob/GAE/app/database.go

**Comment by PaulSnow** [comment]
I believe that's a good approach.
