### ISSUE TITLE
factom-cli shows millitimestamp as AM rather than PM

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#756]
Here is one output:
```
~$ factom-cli transactions

a:  Fee Due: 0.012   Currently will pay: 0.012

Transaction (size 181):
                 Version: 0000000000000002
          MilliTimestamp: 0000014ffbef1d73 Sep 23, 2015 at 8:39am (UTC)

```
0x0000014ffbef1d73 / 1000
is a utc time of 1443040796, which corresponds to
Wed, 23 Sep 2015 20:39:56 GMT

**Comment by drobertbaker** [comment]
The time stamp is showing an extraneous "+0000" on the end. Do you want that?

transaction01:  Fee Due: 0.006666   Currently will pay: 0.0

WARNING: Currently your transaction fee may be too low

Transaction (size 10):
                 Version: 0000000000000002
          MilliTimestamp: 0000015006c8c470 Fri, 25 Sep 2015 23:13:52 +0000
                # Inputs: 0000
               # Outputs: 0000
   # EntryCredit Outputs: 0000

**Comment by PaulSnow** [comment]
That is a standard UTC indicator (timezone +0).  So yes, we want that.

**Comment by drobertbaker** [comment]
OK
