### ISSUE TITLE
API: can REQUEST ENTRY CREDIT BALANCE OF FACTOID WALLET ADDRESS

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#764]
~$ factom-cli getaddresses

  Factoid Addresses

    factoid-wallet-address-name01    FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb           150.0
    factoid-wallet-address-name02    FA32U76Yr4GgWuCt486VML8cQr5YXRtqpta5ZMmNE84kEh362hB2           149.0

  Entry Credit Addresses

         ec-wallet-address-name01    EC2DMGdyzDwf49JPEFk8tJ3mhUXLJR4y3B2HfrJASRasAECZChYP              0
         ec-wallet-address-name02    EC1mNEeGNvpZ9kbswRR6cZTruQ5gGKZ23kTgCeco9aaqSknihoEp              0

~$ factom-cli balance ec factoid-wallet-address-name01
Balance of  factoid-wallet-address-name01  =  0

Previously, this returned the result:
"Address undefined or invalid"

**Comment by PaulSnow** [comment]
Not needed with the graphical API

**Comment by drobertbaker** [comment]
This was fixed and somehow reverted. You did so well with this in the walletapp, could you have a look at it in the fctwallet, please?

**Comment by hannemennah** [comment]
This should be fixed in [this commit](https://github.com/FactomProject/fctwallet/commit/ef5306da788ab73505c438a788fe573b64e734d3), on the Hotfix4.1 branch. I believe this was a safe change, but please let me know if you notice any other strange behavior as a result of this update.

**Comment by drobertbaker** [comment]
OK
