### ISSUE TITLE
API: can REQUEST FACTOID BALANCE OF ENTRY CREDIT WALLET ADDRESS

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#765]
~$ factom-cli getaddresses

  Factoid Addresses

    factoid-wallet-address-name01    FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb           150.0
    factoid-wallet-address-name02    FA32U76Yr4GgWuCt486VML8cQr5YXRtqpta5ZMmNE84kEh362hB2           149.0

  Entry Credit Addresses

         ec-wallet-address-name01    EC2DMGdyzDwf49JPEFk8tJ3mhUXLJR4y3B2HfrJASRasAECZChYP              0
         ec-wallet-address-name02    EC1mNEeGNvpZ9kbswRR6cZTruQ5gGKZ23kTgCeco9aaqSknihoEp              0

~$ factom-cli balance fct ec-wallet-address-name01
Balance of  ec-wallet-address-name01  =              0.0

Previously, this returned the result:
“Address undefined or invalid: Cannot get a factoid balance on an Entry Credit Address”

**Comment by drobertbaker** [comment]
This was fixed and somehow reverted. You did so well with this in the walletapp, could you have a look at it in the fctwallet, please?

**Comment by hannemennah** [comment]
Duplicate of #764

**Comment by drobertbaker** [comment]
This is NOT a duplicate of #764, but the inverse problem. And it is still broken. Please review.

**Comment by hannemennah** [comment]
You are absolutely right, I should have read more closely! 

I assumed "fct" was what "GetType()" returned for factoid addresses... it turns out that it's "FA" instead. I [updated](https://github.com/FactomProject/fctwallet/commit/e50812f579b207932af35c3424b481bf07bb7ae4) the balance query accordingly.

Good catch as always Robert!

**Comment by drobertbaker** [comment]
OK
