### ISSUE TITLE
Updates for Exchanges

### ISSUE THREAD

**Issue by PaulSnow** [FactomProject/WorkItems#775]
+ Add block height to Transactions when printing transaction lists
+ Add lookup by transaction id (the hash of the transaction sans signatures)
+ Add call to get the current directory block height

**Comment by PaulSnow** [comment]
Turns out we were already putting the block height in the transactions.  

Added lookup by transaction id (same as with a lookup by address)

Added a call to get the current directory block height to the factom repository, and factomd.

**Comment by PaulSnow** [comment]
Done in Hotfix2

**Comment by drobertbaker** [comment]
OK
