### ISSUE TITLE
Factomd should handle versions properly

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#778]
/factomd appears to have some issues when it comes to version mismatch:

******************** - IMPORTANT - ****************************
      VERSION MISMATCH  -- Please upgrade your software!
***************************************************************

It looks like btcd and factomd versions are different (1005 vs 70002) and they get mixed up.

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/18/2016
