### ISSUE TITLE
Fix database error initializing a fresh factomd instance

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#779]
When we start, we get a blank database, and the database structure has lastDirBlkSha which is nil. The code asks for latest directory block sha, gets nil. Then, the code asks the database to load the block by that hash, and we get a panic because we're calling nil.bytes(). Alternative error is, when we get nil, we return nil, but then the code forwards the nil block in a msg.msg: {"ProtocolVersion":70002,"BlockLocatorHashes":[null,"cbd3d09db6defdc25dfc7d57f3479b339a077183cd67022e6d1ef6c041522b40"],"HashStop":null} , which causes another error down the line.

**Comment by PaulSnow** [comment]
fixed.
