### ISSUE TITLE
walletapp: labeling of "+" buttons

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#785]
Both buttons are labeled " New Transaction"

The "+" button next to the Input fields should be labeled "New Input".

The "+" button next to the Output fields should be labeled "New Output".

The "x" buttons have no labels at all.

They should be labeled "Delete Input" and "Delete Output" respectively.

**Comment by hannemennah** [comment]
[Fixed](https://github.com/FactomProject/fctwallet/commit/82fd6f59153904e12895020c24525308688f807c)
