### ISSUE TITLE
walletapp: rounding errors

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#787]
![screenshot from 2015-10-19 19 12 48](https://cloud.githubusercontent.com/assets/11637191/10594725/acf306fc-7695-11e5-8ef9-a40d77b74b0b.png)

The fee says 0.07999 and I'm paying 0.07999199. It's a no-go.
0.079992 is OK

**Comment by hannemennah** [comment]
Turns out it was just the "Required Fee" label being too small to show the "2". [Fixed](https://github.com/FactomProject/fctwallet/commit/31cb55244c7b5fb777edde66a832686180dca887).

**Comment by drobertbaker** [comment]
OK
