### ISSUE TITLE
walletapp: widen textbox

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#788]
![screenshot from 2015-10-19 19 32 47](https://cloud.githubusercontent.com/assets/11637191/10594966/644231a0-7698-11e5-8436-590c5b6ca97d.png)
The textbox is just a little too narrow to handle an 8 decimal place number. Please widen it to accommodate.

**Comment by hannemennah** [comment]
[Fixed](https://github.com/FactomProject/fctwallet/commit/31cb55244c7b5fb777edde66a832686180dca887)

**Comment by drobertbaker** [comment]
OK
