### ISSUE TITLE
walletapp: loading exported transactions

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#789]
If I try to load a transaction from a file to which just exported it, I get:

The output above is not a properly-JSON-formatted factoid transaction.

**Comment by hannemennah** [comment]
[Fixed here.](https://github.com/FactomProject/fctwallet/commit/012e0f6d38d2c27d7853d548674b546d80b5a77f) Please let me know if you still see anything weird going on with this functionality.

**Comment by drobertbaker** [comment]
OK
