### ISSUE TITLE
walletapp: sending entry credits to a factoid wallet address

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#791]
I applied:
1 input from a factoid wallet address
1 output to another factoid wallet address
and checked the EC circle.

The input factoid wallet address was docked.
The output factoid wallet address was not credited.
A non-existent entry credit address (EC2SJZgTpe7acQPaFduTruHKXmkNTQZbvT54JtySzYGgR6ZgT6b5) was credited, but doesn't show up on the list of balances.

If I individually look at the balance of this non-existent entry credit address, it has indeed been credited, but doesn't show on the list of balances. 

----------------------------------------------------------------------------------------------------------------------------------- 
Factoid Addresses

    factoid-wallet-address-name01    FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb           150.840016
    factoid-wallet-address-name02    FA2eEM9TBc3i2iDdnUXcXi9Ba1MRQgFj7L6QCZGsxcFrThgwJEr5           149.0

  Entry Credit Addresses

         ec-wallet-address-name01    EC22FAfD9AdCKVCoegNwArx84XehRQ1zZkxSVQdugE6BsYYSMy9Q              0
         ec-wallet-address-name02    EC2VoW8dQGAqas3DMydjPGafZ27Pxjqv8SWR7Jp3fPpmuvez7FQx              0
----------------------------------------------------------------------------------------------------------------------------------
Transaction transaction04:

	Input: factoid-wallet-address-name01 : 6.079992
	Output: factoid-wallet-address-name02 : 6 (ec) 

	Fee: 0.079992

Transaction transaction04 has been submitted to Factom.
----------------------------------------------------------------------------------------------------------------------------
Transaction:  transaction04 

 Transaction (size 181):
                 Version: 2
          Transaction ID: e225d1c2a7a1c03fa4ebed584729d3165291ea4c75ed78974539127ff16e5fba
          MilliTimestamp: 000001508c1317d5 Wed, 21 Oct 2015 20:24:32 +0000
                # Inputs: 0001
               # Outputs: 0000
   # EntryCredit Outputs: 0001
      input:       6.079992   FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb
   ecoutput:       6.0        **EC2SJZgTpe7acQPaFduTruHKXmkNTQZbvT54JtySzYGgR6ZgT6b5**
 RCD 1: 01  f06f190d3307f52ff56e2ea6874250cb8ce0332dcc809b80100493b1ff064c59

Required Fee:        0.079992
Fee You are paying: 0.079992
Transaction Size:    181
Transaction transaction04 Submitted
------------------------------------------------------------------------------------------------------------------------------------
 Factoid Addresses

    factoid-wallet-address-name01    FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb           144.760024
    factoid-wallet-address-name02    FA2eEM9TBc3i2iDdnUXcXi9Ba1MRQgFj7L6QCZGsxcFrThgwJEr5           149.0

  Entry Credit Addresses

         ec-wallet-address-name01    EC22FAfD9AdCKVCoegNwArx84XehRQ1zZkxSVQdugE6BsYYSMy9Q              0
         ec-wallet-address-name02    EC2VoW8dQGAqas3DMydjPGafZ27Pxjqv8SWR7Jp3fPpmuvez7FQx              0

--------------------------------------------------------------------------------------------------------------------------------------
Entry Credit Address EC2SJZgTpe7acQPaFduTruHKXmkNTQZbvT54JtySzYGgR6ZgT6b5 Balance: 900 EC

**Comment by drobertbaker** [comment]
Another example:

Factoid Addresses

    factoid-wallet-address-name01    FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb           133.60004
    factoid-wallet-address-name02    FA2eEM9TBc3i2iDdnUXcXi9Ba1MRQgFj7L6QCZGsxcFrThgwJEr5           150.0

  Entry Credit Addresses

         ec-wallet-address-name01    EC22FAfD9AdCKVCoegNwArx84XehRQ1zZkxSVQdugE6BsYYSMy9Q           1500
         ec-wallet-address-name02    EC2VoW8dQGAqas3DMydjPGafZ27Pxjqv8SWR7Jp3fPpmuvez7FQx              0

-----------------------------------------------------------------------------

Transaction transaction04:

	Input: factoid-wallet-address-name01 : 2.146652
	Output: factoid-wallet-address-name02 : 1 (ec) 
	Output: ec-wallet-address-name01 : 1 (ec) 

	Fee: 0.146652

Transaction transaction04 has been submitted to Factom.

-----------------------------------------------------------------------------

  Factoid Addresses

    factoid-wallet-address-name01    FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb           131.453388
    factoid-wallet-address-name02    FA2eEM9TBc3i2iDdnUXcXi9Ba1MRQgFj7L6QCZGsxcFrThgwJEr5           150.0

  Entry Credit Addresses

         ec-wallet-address-name01    EC22FAfD9AdCKVCoegNwArx84XehRQ1zZkxSVQdugE6BsYYSMy9Q           1650
         ec-wallet-address-name02    EC2VoW8dQGAqas3DMydjPGafZ27Pxjqv8SWR7Jp3fPpmuvez7FQx              0

**Comment by hannemennah** [comment]
Should be fixed now (same push as #790)

**Comment by drobertbaker** [comment]
OK
