### ISSUE TITLE
walletapp: not detecting entry credit address?

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#792]
Entry credit address not being detected (Name is undefined. (OUTPUTS))
So transaction doesn't happen.
I get the same result whether the factoid circle or the EC circle is checked.
------------------------------------------------------------------------------------------------------------------------------
 Factoid Addresses

    factoid-wallet-address-name01    FA3EPZYqodgyEGXNMbiZKE5TS2x2J9wF8J9MvPZb52iGR78xMgCb           143.680032
    factoid-wallet-address-name02    FA2eEM9TBc3i2iDdnUXcXi9Ba1MRQgFj7L6QCZGsxcFrThgwJEr5           150.0

  Entry Credit Addresses

         ec-wallet-address-name01    EC22FAfD9AdCKVCoegNwArx84XehRQ1zZkxSVQdugE6BsYYSMy9Q              0
         ec-wallet-address-name02    EC2VoW8dQGAqas3DMydjPGafZ27Pxjqv8SWR7Jp3fPpmuvez7FQx              0
-----------------------------------------------------------------------------------------------------------------------------------------
![screenshot from 2015-10-21 16 48 41](https://cloud.githubusercontent.com/assets/11637191/10651199/c2c4b6f4-7813-11e5-8ead-2f5a08514650.png)
![screenshot from 2015-10-21 16 49 11](https://cloud.githubusercontent.com/assets/11637191/10651198/c2c15608-7813-11e5-8d7a-52831dd0fef9.png)

**Comment by drobertbaker** [comment]
Here is use the entry credit address key with the factoid circle checked. It rightly complains but look WHERE it complains (under Required Fee)

![screenshot from 2015-10-21 17 00 50](https://cloud.githubusercontent.com/assets/11637191/10651489/6e03e9da-7815-11e5-9d7e-187b9dd82ff2.png)

The good news: When I use the entry credit address key with the entry credit circle checked, everything works fine.

**Comment by drobertbaker** [comment]
Another example of misplaced error message:

![screenshot from 2015-10-21 17 58 24](https://cloud.githubusercontent.com/assets/11637191/10652580/76e420c6-781d-11e5-8766-b941c99b07e0.png)

**Comment by hannemennah** [comment]
Should be fixed now.

**Comment by drobertbaker** [comment]
OK
