### ISSUE TITLE
walletapp: add "cover fee" button next to each input amount field

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#793]
clicking this button will add the required fee to the amount already present in that field (only if the input totals equal the output totals0

**Comment by hannemennah** [comment]
Implemented [here](https://github.com/FactomProject/fctwallet/commit/506564ef4b05e82148bb4241586609bb606de64d#diff-5473a55adc473b72405822a46c0d8d88).

**Comment by drobertbaker** [comment]
This is great functionality, but it still requires two clicks because adding the amount field itself increases the fee.

Also there is truncation in the amount field which no longer functions with the cover fee button.

**Comment by hannemennah** [comment]
The truncation should work as expected with the most recent commit. If you see it acting up, please let me know.

**Comment by drobertbaker** [comment]
Justin:
Please implement the solution we discussed for clicking the fee button
actually generating 2 clicks so that the shown fee will actually match the
real fee.

Additionally, we do want to go ahead with getting rid of the factoid and EC
radio buttons as we discussed, because you have successfully  obviated
their functionality.

On Fri, Oct 23, 2015 at 10:49 AM, Justin Hanneman <notifications@github.com>
wrote:

> Assigned #793 <https://github.com/FactomProject/WorkItems/issues/793> to
> @drobertbaker <https://github.com/drobertbaker>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FactomProject/WorkItems/issues/793#event-443952403>.
>



-- 
Thanks,
D. Robert Baker
Process Integration Manager, factom
drobertbaker@factom.org

**Comment by drobertbaker** [comment]
Justin:
Please implement the solution we discussed for clicking the fee button actually generating 2 clicks so that the shown fee will actually match the real fee.

Additionally, we do want to go ahead with getting rid of the factoid and EC radio buttons as we discussed, because you have successfully  obviated their functionality.

**Comment by hannemennah** [comment]
Done and done. Both of these were much harder to achieve than I had expected, but they should be working now.

**Comment by drobertbaker** [comment]
The "double-click" functionality doesn't seem to be working today. Can you review it please?

**Comment by hannemennah** [comment]
I've been unable to replicate the issue. Would you mind pulling the most recent commit and trying again? If you still see the problem, please let me know how you're encountering it.

**Comment by drobertbaker** [comment]
OK
