### ISSUE TITLE
Compile issue with base58

### ISSUE THREAD

**Issue by PaulSnow** [FactomProject/WorkItems#794]
Not entirely sure what this code is supposed to do.  The encoding for our private keys isn't likely to be understood by any library... Unless we wrote this one?

Error (patched at the moment to do nothing) is found in common/factoid/wallet/conversions.go
```
func PrivateKeyStringToHumanReadablePrivateKey(priv string, b1, b2 byte) (string, error) {
	priv = strings.TrimSpace(priv)

	h, err := hex.DecodeString(priv)
	if err != nil {
		return "", err
	}
	
	return string(h,fmt.Errorf("Issue with base58")
//	return base58.CheckEncodeWithVersionBytes(h, b1, b2), nil
}
```

**Comment by ThePiachu** [comment]
I updated btcutil to add the functionality:

https://github.com/FactomProject/btcutil/commit/8bd01a1e8673539f0d4cb4e4cccd9bf30586f7b6

At the moment I added the functionality mainly "for completeness" and for testing, but it could be useful for say, converting between mnemonic to human-readible private key for importing / exporting, or more general for import/export from a wallet file.
