### ISSUE TITLE
Improve EC handling

### ISSUE THREAD

**Issue by PaulSnow** [FactomProject/WorkItems#836]
Modify the +Fee button to trim unused Factoids from the EC credit outputs before adjusting the given input to pay the fee for the transaction.  Also need some kind of "EC Calculator" so if the user wishes to buy 100 ECs, then they need some help figuring out how many factoids that is.

The observation is that the user has a hard time calculating how many factoids to put on an EC output to buy a particular number of Entry Credits, and in some cases may spend more factoids than necessary.

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/15/2016
