### ISSUE TITLE
Create new server for new Factom Explorer instance

### ISSUE THREAD

**Issue by hannemennah** [FactomProject/WorkItems#848]
Create a new environment where a new Factom Explorer (built from the ground up) can be hosted, and provide access credentials.

**Comment by n1rvana** [comment]
I'd like to collaborate on this.

**Comment by michaelbeam** [comment]
hannemennah, n1rvana, please email me your ssh public keys so I can setup access on the servers you need.

**Comment by michaelbeam** [comment]
- create aws server
- generic system updates
- create dev users and setup ssh access
- setup golang and dev env
- install factomd and related packages (master v0.3.4)

**Comment by michaelbeam** [comment]
factomexplorer-dev `52.17.183.121`
