### ISSUE TITLE
anchor records document the wrong DBHeight

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#865]
investigate further

'''
brian@hawkins:~/go20/bin$ factom-cli get eblock c0eafe1e7175838882c230eec83771edb685f0a2daba6a52aa87e58aa134f250
BlockSequenceNumber: 201
ChainID: df3ade9eec4b08d5379cc64270c30ea7315d8a8a1a69efe2b98a60ecdd69e604
PrevKeyMR: 916eba759d41fd0879ec4ab2978025446758036ff0000695b287f56e511646dd
Timestamp: 1446841800
EBEntry {
    Timestamp 1446841980
    EntryHash f75ca015e13cb299970849d21138282422cf294c33ab0b1b16afbf82378a8c22
}
EBEntry {
    Timestamp 1446841980
    EntryHash d85e6a77a18d41805cef1f36a7354c03c681441543dbde0852834ed0f360e008
}
brian@hawkins:~/go20/bin$ factom-cli get entry f75ca015e13cb299970849d21138282422cf294c33ab0b1b16afbf82378a8c22
ChainID: df3ade9eec4b08d5379cc64270c30ea7315d8a8a1a69efe2b98a60ecdd69e604
Content:
{"AnchorRecordVer":1,"DBHeight":1224,"KeyMR":"f4f27f6653888807e938dd64484cd159c2bc7d3415cb5efe4a8561aec2818a76","RecordHeight":1225,"Bitcoin":{"Address":"mrM9rnFUTZfsxgw6awLr2kRYnLmGHTQ5H2","TXID":"9b2872b03276cdb815996398458974259a274d6e5f3e6278df1077eccb35ae77","BlockHeight":583510,"BlockHash":"00000000000006c284aac5758c4d4a408f6b2a7d0c29b4d886f0a66c833ea0c5","Offset":22}}012d47732abed1343f6d48ace936d269f7bd13f39bcd80fe73ed15de3ac0cff1de3edff98af97ba28d554ac74f96de0335095269d1de89d5915a350ed813ad0a
brian@hawkins:~/go20/bin$ factom-cli get entry d85e6a77a18d41805cef1f36a7354c03c681441543dbde0852834ed0f360e008
ChainID: df3ade9eec4b08d5379cc64270c30ea7315d8a8a1a69efe2b98a60ecdd69e604
Content:
{"AnchorRecordVer":1,"DBHeight":1225,"KeyMR":"f662f4996d19bb2ade7608831b237ea5f422a0cfbea1e500d6e0c779b8b94144","RecordHeight":1225,"Bitcoin":{"Address":"mrM9rnFUTZfsxgw6awLr2kRYnLmGHTQ5H2","TXID":"36cedcc95d214bd76a344fc982047e3c07e5ae71a1db0ca8bf05bff79dba74a1","BlockHeight":583511,"BlockHash":"00000000004b82a8e8e29e8221d184afe391d0d7f2d2e9425543c469fca5d62a","Offset":4}}b0cfa4565fc1857c8a6039d2ddc5ac27f42b8e7a45b122bf0584f99560353108680255f1e5017a8dcaf4620726eb4be7b38a98c6ccbc2c66b318d43558713a0f
'''

**Comment by carryforward** [comment]
When creating the anchor record, the value RecordHeight should be current block being built, not the block height of the previous block.  it should be the latest finished block + 1.  

This way I can go directly to the block height that I am interested in to validate it.  Right now, it is the number of the previous block.

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/19/2016
