### ISSUE TITLE
location of block files indeterminate

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#888]
in the config file it puts them in data/export/
https://github.com/FactomProject/FactomCode/blob/master/factomd/factomd.conf

in the compiled in config file it puts them in store/seed
https://github.com/FactomProject/FactomCode/blob/master/util/config.go

**Comment by carryforward** [comment]
I have updated Hotfix5 to have the default (with no factom.conf file) file paths for the ldb and block files match the locations in the default config file.

https://github.com/FactomProject/FactomCode/commit/5c093b3eaef758c248ae7cb8ca1bea0dc6315743

This will stop confusing situations where files get written to different locatins when a config file is added or removed.

factomd should now only make ~/.factom/ldb and ~/.factom/data/export/ directorys, and not ~/.factom/ldb9 and ~/.factom/store/seed/

beam is worried about strange failures when the config file is updated.

**Comment by drobertbaker** [comment]
no sign of ~/.factom/ldb9 and ~/.factom/store/seed/ and ~/.factom/ldb and ~/.factom/data/export/ are present
