### ISSUE TITLE
defactomizer: Intelligently handle arbitrary JSON-formatted data in entries

### ISSUE THREAD

**Issue by hannemennah** [FactomProject/WorkItems#889]
Because json.Unmarshal breaks with non-JSON-encoded data appended to the end of the entry, unless we're Unmarshalling specifically to a particular struct type.

http://stackoverflow.com/questions/17306358/golang-removing-fields-from-struct-or-hiding-them-in-json-response

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/15/2016
