### ISSUE TITLE
MortgageDemo: create "decrypt" helper function for data retrieval and usage

### ISSUE THREAD

**Issue by hannemennah** [FactomProject/WorkItems#901]
On encrypted (non-plaintext) chains, the data must be decrypted before any other parsing is possible.

**Comment by hannemennah** [comment]
Done.

**Comment by drobertbaker** [comment]
This issue was moved to FactomProject/FactomInc#64

**Comment by drobertbaker** [comment]
This issue was moved to FactomProject/FactomInc#65
