### ISSUE TITLE
make list of attack vectors

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#904]
Create list of attack vectors that Factom will be subject to, to aid in testing

**Comment by n1rvana** [comment]
1. DDOS -- hitting all the federated servers with bogus transactions/packets
2. P2P -- Pretending to be a real peer in the peer 2 peer network but generating false info
3. BGIP -- Attacking the network infrastructure directly (overflow attacks, BGIP specific DDOS attacks) -- this is mostly an issue if the federated servers are on the same network/cloud platform

These are the ones I can think of off hand.  Robert, do you have more context?  I would suggest this task next be assigned to Brian for input.

**Comment by drobertbaker** [comment]
OK
