### ISSUE TITLE
In Windows, factomd crashes at different instances when NodeMode is changed

### ISSUE THREAD

**Issue by VeenaGondkar** [FactomProject/WorkItems#906]
Setup: Windows 8.1
Scenario 1 : 
1.With default configuration  - Start factomd, fctwallet, run the command factom-cli properties
2.Change the NodeMode in factom.conf from NodeMode FULL to SERVER
3.restart factomd, fctwallet and run the command factom-cli properties.
4.Factomd crashes with invalid Admin block signature.
5.The check for Admin block is not initiated when factomd is run but only when factom-cli properties command is called.

Scenario 2: 
1.Change the NodeMode from SERVER to FULL (make sure one successful run on SERVER has gone thru).
2.start factomd. 
3.It crashes immediately with invalid Admin block signature.
4.The check for Admin block is initiated immediately when factomd is run.

This discrepancy between NodeModes needs to be checked.

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/18/2016
