### ISSUE TITLE
explorer shows factoid transaction without output or signature

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#908]
I validated this transaction, and it is formatted correctly in the blockchain.  The explorer does not display it properly though.

http://explorer.factom.org/entry/4039805875314d99aec49bc2220e168f17ae321f2c81c1976d12f6a3f1886616

The transaction decodes to have 107999300 factoshis as an input and 100000000 as an output.  the signature is 94f57ad9ad0c4b5cc2dd267276c615fbe33a2db2bccbb60b9a3db0914c87e1f917980a681708c9da28eca70c658f37b9f74fb84f3420f943b6b4f9a134f4bd0d

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/15/2016
