### ISSUE TITLE
Fix issue with base58

### ISSUE THREAD

**Issue by ThePiachu** [FactomProject/WorkItems#913]
https://github.com/FactomProject/factomd/blob/development/common/primitives/conversions.go#L107

**Comment by ThePiachu** [comment]
The issue has been fixed on development branch

https://github.com/FactomProject/btcutil/commit/8bd01a1e8673539f0d4cb4e4cccd9bf30586f7b6

But the change should also be mirrored on the main branch. This will break the factoid repo and possibly some other code as well.

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/19/2016
