### ISSUE TITLE
Set Block Size for Directory Block chain, Entry Block chain, Entry Credit chain and Factoid chain

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#92]
Currently there's no logic to limit the block size. Every block is sealed on the minute mark. Potentially the block can become too big for transfer or display...

**Comment by PaulSnow** [comment]
I think we can close this.  We are not going to have limits on the block sizes, even if they are too big to display.  Transfer is via Distributed Hash Table (torrents), so we are not limited there.

**Comment by PaulSnow** [comment]
don't need to do this
