### ISSUE TITLE
Blocks are created in wrong timing

### ISSUE THREAD

**Issue by jl8610** [FactomProject/WorkItems#922]
Blocks are created in every 15 sec when it should be in config file

Here's what's on our test server:

54.194.254.200

-rwxrwxr-x 1 factom factom    305 Dec 23 16:32 store.000009578.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:32 store.000009579.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:32 store.000009580.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:33 store.000009581.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:33 store.000009582.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:33 store.000009583.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:33 store.000009584.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:34 store.000009585.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:34 store.000009586.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:34 store.000009587.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:34 store.000009588.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:35 store.000009589.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:35 store.000009590.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:35 store.000009591.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:35 store.000009592.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:36 store.000009593.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:36 store.000009594.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:36 store.000009595.block*
-rwxrwxr-x 1 factom factom    305 Dec 23 16:36 store.000009596.block*

**Comment by jl8610** [comment]
Linux w530 4.2.5-1-ARCH # 1 SMP PREEMPT Tue Oct 27 08:13:28 THIS 2015 x86_64 GNU/Linux

**Comment by carryforward** [comment]
justin managed to replicate this and figured it out.
