### ISSUE TITLE
test exporting of seed with walletmgr

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#934]
make sure that the seed being printed by walletmgr is the same as the one used by the wallet.

**Comment by carryforward** [comment]
it exported the same seed as was in seedhash when the wallet was made.

https://github.com/FactomProject/factoid/blob/666a00af6f151830cb8be97abf566239d4a11425/wallet/scwallet.go#L307

**Comment by drobertbaker** [comment]
waiting on the creation of software to check the vailidity of the seed

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/15/2016
