### ISSUE TITLE
remove the setup API call

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#937]
This will only cause heartache to have multiple root seeds.  Disabling the API call should be enough to prevent people from making multiple seeds.   This will be in hotfix 5

**Comment by carryforward** [comment]
setup command now removed from walletapp, factom-cli, and fctwallet api in hotfix 5.

please test.

**Comment by VeenaGondkar** [comment]
setup command has been removed.

when the following command is executed 
curl -X POST http://localhost:8089/v1/factoid-setup/ -d "seed=randomseedgenerated"
response is
Page not found.
