### ISSUE TITLE
commit-chain does not return the error - encoding/hex: odd length hex string

### ISSUE THREAD

**Issue by VeenaGondkar** [FactomProject/WorkItems#941]
commit-chain does not return the error - encoding/hex: odd length hex string, if the length is not correct. just returns EOF. 

This needs to be consistent with commit-entry API which returns the error - encoding/hex: odd length hex string, if the length is not correct.

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/18/2016
