### ISSUE TITLE
write conflict on factom-d.log

### ISSUE THREAD

**Issue by mwanon** [FactomProject/WorkItems#950]
Text below is from the execution of factomd

Go compiler version:  go1.5.2
boltDBpath: C:\Users\matt/.factom/
2016/01/12 13:54:56 web.go serving :8088

'factomd initializeonly' will do just that.  Initialize and stop.

  CLIENT MODE 

13:54:58 2016-01-12 [WRN] BTCD: open C:\Users\matt.factom\NONE.conf: The system
 cannot find the file specified.
Seelog error: rename C:\Users\matt.factom\factom-d.log C:\Users\matt.factom\fa
ctom-d.log.1: The process cannot access the file because it is being used by ano
ther process.
peers.json is disabled for Milestone1

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/18/2016
