### ISSUE TITLE
Failing - factom-cli -s factomd.cloudapp.net:8088 properties

### ISSUE THREAD

**Issue by VeenaGondkar** [FactomProject/WorkItems#955]
$ factom-cli -s factomd.cloudapp.net:8088 properties
panic: Get http://localhost:8088/v1/directory-block-head/: dial tcp 127.0.0.1:8088: getsockopt: connection refused

goroutine 1 [running]:
github.com/FactomProject/fctwallet/Wallet/Utility.getDBHead(0x68)
    /home/factom/go/src/github.com/FactomProject/fctwallet/Wallet/Utility/transactionlist.go:35 +0x9d
github.com/FactomProject/fctwallet/Wallet/Utility.refresh(0x0, 0x0)
    /home/factom/go/src/github.com/FactomProject/fctwallet/Wallet/Utility/transactionlist.go:108 +0x24
github.com/FactomProject/fctwallet/Wallet/Utility.TotalFactoids(0x0, 0x0, 0x0)
    /home/factom/go/src/github.com/FactomProject/fctwallet/Wallet/Utility/transactionlist.go:184 +0x39
main.fctproperties(0xc82000a330, 0x1, 0x1)
    /home/factom/go/src/github.com/FactomProject/factom-cli/transaction.go:524 +0x799
main.main()
    /home/factom/go/src/github.com/FactomProject/factom-cli/main.go:89 +0xd60

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 8 [IO wait]:
net.runtime_pollWait(0x7f4326c4da08, 0x72, 0xc82000e200)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(_pollDesc).Wait(0xc82005adf0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(_pollDesc).WaitRead(0xc82005adf0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(_netFD).Read(0xc82005ad90, 0xc820138000, 0x1000, 0x1000, 0x0, 0x7f4326c48050, 0xc82000e200)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(_conn).Read(0xc82002e0b8, 0xc820138000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f4326c4dac8, 0xc82002e0b8, 0xc8200b6268, 0xc820138000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(_noteEOFReader).Read(0xc8200c0820, 0xc820138000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(_Reader).fill(0xc82001d260)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(_Reader).Peek(0xc82001d260, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(_persistConn).readLoop(0xc8200b6210)
    /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 9 [select]:
net/http.(_persistConn).writeLoop(0xc8200b6210)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(_Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/18/2016
