### ISSUE TITLE
Failing - factom-cli -s factomd.cloudapp.net getaddresses and balances

### ISSUE THREAD

**Issue by VeenaGondkar** [FactomProject/WorkItems#958]
$ factom-cli -s factomd.cloudapp.net balances
Error printing addresses
Command Failed:  Server Error
$ factom-cli -s factomd.cloudapp.net getaddresses
Error printing addresses
Command Failed:  Server Error

**Comment by drobertbaker** [comment]
transferred to Pivotal Tracker 1/18/2016
